Repository iiab/iiab, pull requests merged in 2018-09, with the labels that each got.

#1077 Kolibri and Calibre-Web virtualenv's (for combined testing)
  roles/calibre-web/defaults/main.yml
  roles/calibre-web/tasks/main.yml
  roles/kolibri/README.rst
  roles/kolibri/defaults/main.yml
  roles/kolibri/tasks/main.yml
Labels: enhancement

#1074 Virtual Environment for Kolibri (isolate Python pkg's etc)
  roles/kolibri/defaults/main.yml
  roles/kolibri/tasks/main.yml
Labels: enhancement

#1075 Virtual Environment for Calibre-Web (isolate Python pkg's etc)
  roles/calibre-web/defaults/main.yml
  roles/calibre-web/tasks/main.yml
Labels: enhancement

#1079 Experimental fix for serious OpenVPN flaw
  roles/openvpn/tasks/main.yml
  roles/openvpn/templates/xscenet.conf.j2
Labels: bug

#1080 Explanation added for OpenVPN Proposed Fix PR #1079
  roles/openvpn/tasks/main.yml
Labels: enhancement

#1082 Longer version #s for calibre_deb_pin_version e.g. 3.30+dfsg-1
  roles/calibre/defaults/main.yml
  roles/calibre/tasks/debs.yml
Labels: enhancement

#1083 roles/openvpn/tasks/main.yml clarified + 20 lines removed
  roles/openvpn/tasks/main.yml
Labels: enhancement

#1084 Comments tweaked in roles/openvpn/tasks/main.yml
  roles/openvpn/tasks/main.yml
Labels: enhancement

#1085 roles/openvpn/tasks/main.yml clarified, thx to @jvonau
  roles/openvpn/tasks/main.yml
Labels: enhancement

#1086 Typo in roles/openvpn/tasks/main.yml comment
  roles/openvpn/tasks/main.yml
Labels: bug, enhancement

#1088 roles/openvpn/tasks/main.yml further clarified, thx to @jvonau
  roles/openvpn/tasks/main.yml
Labels: enhancement

#1090 Fix iiab-remote-on|off which had longstanding (OpenVPN) issues
  roles/openvpn/tasks/main.yml
  roles/openvpn/templates/15-openvpn
  roles/openvpn/templates/announcer.j2
  roles/openvpn/templates/iiab-handle.j2
  roles/openvpn/templates/iiab-remote-off
  roles/openvpn/templates/iiab-remote-on.j2
  roles/openvpn/templates/up_wan.deprecated
Labels: bug, enhancement

#1091 Fix for Ansible install on Ubuntu, thx to @kananigit
  scripts/ansible
  scripts/ansible-2.6.x
Labels: bug

#1093 Nextcloud 13.x -> 14.x, as 14.0.0 is now released
  roles/nextcloud/defaults/main.yml
Labels: enhancement

#1095 fix .htaccess error nextcloud
  roles/nextcloud/templates/nextcloud.conf.j2
Labels: enhancement, question

#1097 Calibre unit file: Change TimeoutStartSec=400 to 600 & remove TimeoutStartSec=900
  roles/calibre/templates/calibre-serve.service.j2
Labels: bug, enhancement

#1103 Ansible fix/optimization for CentOS
  scripts/ansible
  scripts/ansible-2.6.x
Labels: bug, enhancement

#1104 Typo(s) in scripts/ansible and scripts/ansible-2.6.x
  scripts/ansible
  scripts/ansible-2.6.x
Labels: enhancement

#1105 Tweak to ansible install scripts diagnostics
  scripts/ansible
  scripts/ansible-2.6.x
Labels: bug

#1106 Ansible installer output cleanup resulting from PR #1105
  scripts/ansible
  scripts/ansible-2.6.x
Labels: enhancement

#1113 sync dhcpd so comes up at boot on rpi w
  roles/network/templates/dhcp/dhcpd.service
Labels: bug, enhancement

#1117 MIN_ANSIBLE_VER 2.5.8. -> 2.6.4
  iiab-install
Labels: enhancement

#1101 Calibre 3.30 -> 3.31 (awaiting raspbian .deb's)
  roles/calibre/defaults/main.yml
  scripts/calibre-install-pinned-rpi.sh
Labels: enhancement

#1119 Update Calibre-Web README with latest upstream fixes
  roles/calibre-web/README.rst
Labels: enhancement

#1121 Calibre-Web README fixes: prereqs, capitalization, punctuation
  roles/calibre-web/README.rst
Labels: enhancement

#1122 Calibre-Web README fixes: prereqs, capitalization, punctuation (part 2)
  roles/calibre-web/README.rst
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1127 Enable e-book conversion in Calibre-Web's app.db (betw PDF, EPUB, TXT, HTML, etc)
  roles/calibre-web/files/app.db
Labels: enhancement

#1128 Fully update Calibre-Web README's "Known Issues" for IIAB 6.6 release
  roles/calibre-web/README.rst
Labels: enhancement

#1046 iiab_base_ver: 6.6 to 6.7 in roles/0-init/defaults/main.yml
  roles/0-init/defaults/main.yml
Labels: enhancement, question

#1132 Calibre-Web's Ansible output cleaned up
  roles/calibre-web/tasks/main.yml
Labels: enhancement

#1133 kiwix-tools 0.6.0 -> 0.6.1-1
  roles/kiwix/defaults/main.yml
Labels: enhancement

#1134 Kiwix: Ansible syntax/comments modernized
  roles/kiwix/tasks/kiwix_install.yml
  roles/kiwix/tasks/main.yml
Labels: enhancement

#1138 Wrong variable name [in iiab-make-kiwix-lib]
  roles/kiwix/templates/iiab-make-kiwix-lib.py
Labels: bug

#1140 Interim fix for #1139 so Calibre & Admin Install can both install
  scripts/calibre-install-pinned-rpi.sh
Labels: bug

#1145 Backport of PR #1140 for IIAB 6.6, to fix #1139 sqlite3 so Calibre & Admin Console both install
  scripts/calibre-install-pinned-rpi.sh
Labels: bug

#1148 OpenVPN rapid support - implements #1141 for realistic remote support
  roles/1-prep/tasks/main.yml
  roles/4-server-options/tasks/main.yml
Labels: enhancement

#1150 De-emphasize old OSM approach: implements #1143 for faster/cleaner install
  roles/7-edu-apps/tasks/main.yml
  roles/httpd/files/osm.conf
  roles/httpd/tasks/main.yml
  roles/osm/templates/osm.conf.j2
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1154 OSM implementation options better explained
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1155 OpenVPN rapid support improved per @jvonau recommendation
  roles/1-prep/tasks/main.yml
  roles/3-base-server/tasks/main.yml
  roles/iiab-admin/README.rst
Labels: enhancement

#1156 Refine /opt/iiab/iiab/iiab-support.yml for ./install-support
  iiab-support.yml
Labels: enhancement

#1152 Remove etckeeper & clean roles/2-common/tasks/packages.yml
  roles/2-common/tasks/packages.yml
Labels: enhancement, question

#1153 MediaWiki 1.31.0 -> 1.31.1 (implements #1149 security fix)
  roles/mediawiki/defaults/main.yml
  roles/mediawiki/tasks/install.yml
  roles/mediawiki/tasks/main.yml
Labels: enhancement

#1161 wordpress_raise_php_limits variable for schools that use Wordpress intensively
  roles/wordpress/defaults/main.yml
  roles/wordpress/tasks/install.yml
  roles/wordpress/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1164 Run kolibri migrations at install
  roles/kolibri/README.rst
  roles/kolibri/tasks/main.yml
Labels: enhancement

#1166 Rename var apache_raise_php_limits to apache_high_php_limits [for WordPress & Moodle]
  roles/httpd/defaults/main.yml
  roles/httpd/tasks/main.yml
  roles/moodle/defaults/main.yml
  roles/wordpress/defaults/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1168 URL's & intro/explanation fixed in 3 local_vars files + defaults_vars.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: bug, enhancement

#1169 Ansible install scripts: cleaner output outlining prereqs/progress/results
  scripts/ansible
  scripts/ansible-2.6.x
Labels: enhancement

#1172 Fix 3 URL's that GoDaddy broke
  iiab-install
  roles/transmission/README.rst
Labels: enhancement

#1177 Kolibri's README.rst further clarified
  roles/kolibri/README.rst
Labels: enhancement
