Repository iiab/iiab, pull requests merged in 2018-10, with the labels that each got.

#1180 py-captive-portal - finishing touches on PR #1179
  roles/1-prep/templates/.iiab.env.j2.un~
  roles/1-prep/templates/iiab.env.j2
  roles/httpd/templates/010-iiab.conf.j2
  roles/network/files/mac.template
  roles/network/files/simple.template
  roles/network/tasks/captive_portal.yml
  roles/network/tasks/hosts.yml
  roles/network/templates/captive-portal/captive-portal.conf
  roles/network/templates/captive-portal/captive-portal.py.j2
  roles/network/templates/captive-portal/capture-wsgi.py
  roles/network/templates/captive-portal/checkurls
  roles/network/templates/captive-portal/iiab-catch
  roles/network/templates/captive-portal/iiab-uncatch
  roles/network/templates/captive-portal/py-captive-portal.service.j2
  roles/network/templates/gateway/iiab-gen-iptables
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1185 Beginnings of Captive Portal / dnsmasq cleanup, towards solving #1184
  roles/network/defaults/main.yml
  roles/network/tasks/NM.yml
  roles/network/tasks/avahi.yml
  roles/network/tasks/computed_network.yml
  roles/network/tasks/computed_services.yml
  roles/network/tasks/create_ifcfg.yml.deprecated
  roles/network/tasks/detected_network.yml
  roles/network/tasks/detected_redhat.yml
  roles/network/tasks/dhcpd.yml
  roles/network/tasks/edit_ifcfg.yml
  roles/network/tasks/enable_wan.yml
  roles/network/tasks/hosts.yml
  roles/network/tasks/main.yml
  roles/network/tasks/named.yml
  roles/network/tasks/redetect.yml
  roles/network/tasks/squid.yml
  roles/network/tasks/static.yml
  roles/network/tasks/wondershaper.yml
Labels: enhancement

#1186 Recommend Ansible 2.7.0 for IIAB 6.7
  scripts/ansible
  scripts/ansible-2.6.x
Labels: enhancement

#1188 Clarify dhcp_service variable in roles/network/defaults/main.yml
  roles/network/defaults/main.yml
Labels: enhancement

#1187 Consider Calibre 3.32 if it installs cleanly on Raspbian Lite
  roles/calibre/defaults/main.yml
  roles/calibre/tasks/debs.yml
Labels: enhancement, question

#1195 Clean roles/calibre/defaults/main.yml for Calibre 3.32
  roles/calibre/defaults/main.yml
Labels: enhancement

#1197 Delete roles/1-prep/templates/.iiab.env.j2.un~
  roles/1-prep/templates/.iiab.env.j2.un~
Labels: bug, question

#1199 Calibre 3.32+ fix
  roles/calibre/defaults/main.yml
Labels: bug

#1204 Tweaks to roles-needing-docs.py & unmaintained-roles.txt
  scripts/roles-needing-docs.py
  scripts/roles_needing_docs.py
  unmaintained-roles.txt
Labels: enhancement

#1207 Refining @jvonau's new fix for dhcp_service2
  roles/network/defaults/main.yml
  roles/network/tasks/computed_services.yml
  roles/network/tasks/rpi_debian.yml
Labels: enhancement

#1208 Expand /opt/iiab/iiab/unmaintained-roles.txt to include 4 more (that DO have READMEs)
  unmaintained-roles.txt
Labels: enhancement

#1209 calibre-bin 3.32 was updated upstream (and now works)
  roles/calibre/defaults/main.yml
Labels: bug

#1213 Proposed fix to http://box/books for Calibre-Web
  roles/calibre-web/templates/calibre-web.conf.j2
Labels: bug

#1211 IIAB's main README
  README.md
Labels: enhancement

#1220 Revert Calibre 3.32 to 3.31 until upstream dependencies are fixed
  roles/calibre/defaults/main.yml
Labels: bug

#1216 Check transmission_kalite_languages is undefined
  roles/transmission/tasks/main.yml
Labels: bug, enhancement

#1222 Check transmission_kalite_languages is not none (avoids null/empty list)
  roles/transmission/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: bug

#1225 MIN_ANSIBLE_VER 2.6.4 -> 2.6.5
  iiab-install
Labels: enhancement

#1227 Cleanup of all 3 local_vars.yml files & default_vars.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1230 local_vars.yml & default_vars.yml readability tweaks
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1233 Remove 5 deprecated files from top of /opt/iiab/iiab
  README.md.deprecated
  ansible.cfg.deprecated
  iiab.yml.deprecated
  runansible.deprecated
  runtags.deprecated
Labels: enhancement

#1234 Rename license files
  LICENSE
  LICENSE.md
  LICENSING.md
Labels: enhancement

#1235 TravisCI Refactoring: Remove patch for local_tmp and linting
  .travis.yml
Labels: enhancement

#1238 Fix copyright notice in LICENSING.md
  LICENSING.md
Labels: enhancement

#1239 [TravisCI] Test all maintained roles. tests/test.yml refactor
  .travis.yml
  tests/test.yml
Labels: enhancement

#1236 Add new fonts and icons
  roles/0-init/tasks/fl.yml
  roles/httpd/files/html/css/fa.all.min.css
  roles/httpd/files/html/css/open-sans.css
  roles/httpd/files/html/fonts/fa-solid-900.woff
  roles/httpd/files/html/fonts/fa-solid-900.woff2
  roles/httpd/files/html/fonts/open-sans-v15-latin-600.woff
  roles/httpd/files/html/fonts/open-sans-v15-latin-600.woff2
  roles/httpd/files/html/fonts/open-sans-v15-latin-700.woff
  roles/httpd/files/html/fonts/open-sans-v15-latin-700.woff2
  roles/httpd/files/html/fonts/open-sans-v15-latin-regular.woff
  roles/httpd/files/html/fonts/open-sans-v15-latin-regular.woff2
Labels: enhancement

#1245 MIN_ANSIBLE_VER 2.6.5 -> 2.6.6
  iiab-install
Labels: enhancement

#1247 Offer Calibre 3.33.1+ (or whatever is latest) if implementer opts in within local_vars.yml
  roles/calibre/defaults/main.yml
  roles/calibre/tasks/debs.yml
  scripts/calibre-install-latest-rpi-plus.sh
  scripts/calibre-install-latest-rpi.sh
  scripts/calibre-install-pinned-rpi.sh
Labels: enhancement

#1248 Calibre's newly removed by local_vars_medium.yml, but retain it in local_vars_big.yml
  vars/local_vars_big.yml
Labels: enhancement

#1251 Recommend Ansible 2.7.1
  scripts/ansible
  scripts/ansible-2.7.x
Labels: enhancement

#1255 Recommend Ansible 2.7.1, part 2
  scripts/ansible-2.6.x
Labels: enhancement

#1256 Fix Apache .conf & systemd unit files perms / ownership
  roles/calibre-web/tasks/main.yml
  roles/httpd/tasks/main.yml
  roles/network/tasks/captive_portal.yml
Labels: enhancement

#1259 Modernize package installations by removing squash_actions from ansible.cfg
  ansible.cfg
  roles/1-prep/tasks/main.yml
  roles/2-common/tasks/packages.yml
  roles/awstats/tasks/install.yml
  roles/calibre/tasks/main.yml
  roles/cups/tasks/main.yml
  roles/ejabberd/tasks/main.yml
  roles/iiab-admin/tasks/access.yml
  roles/mediawiki/tasks/install.yml
  roles/mongodb/tasks/main.yml
  roles/moodle/tasks/main.yml
  roles/munin/tasks/main.yml
  roles/mysql/tasks/main.yml
  roles/network/tasks/dansguardian.yml
  roles/network/tasks/named.yml
  roles/network/tasks/squid.yml
  roles/nextcloud/tasks/main.yml
  roles/nextcloud/tasks/nextcloud_enabled.yml
  roles/openvpn/tasks/main.yml
  roles/postgresql/tasks/main.yml
  roles/samba/tasks/main.yml
  roles/sugarizer/tasks/main.yml
  roles/transmission/tasks/main.yml
  roles/vnstat/tasks/main.yml
Labels: enhancement

#1260 Clean roles/elgg/tasks/main.yml to remove warnings
  roles/elgg/tasks/main.yml
Labels: enhancement

#1261 Clean roles/nextcloud/tasks/main.yml
  roles/nextcloud/tasks/main.yml
Labels: enhancement

#1263 PR #1261 Nextcloud quick fix
  roles/nextcloud/tasks/main.yml
Labels: bug

#1264 Clarify roles/elgg/tasks/main.yml
  roles/elgg/tasks/main.yml
Labels: enhancement

#1267 Clean URL in nextcloud/tasks/main.yml; clarify httpd/tasks/main.yml & 4-server-options/tasks/main.yml
  roles/4-server-options/tasks/main.yml
  roles/httpd/tasks/main.yml
  roles/nextcloud/defaults/main.yml
Labels: enhancement

#1269 Make Ansible output readable in: 2-common, packages, iptables, iiab-startup, 3-base-server, httpd, php-stem, 4-server-options, squid, dansguardian
  roles/2-common/tasks/iiab-startup.yml
  roles/2-common/tasks/iptables.yml
  roles/2-common/tasks/main.yml
  roles/2-common/tasks/packages.yml
  roles/3-base-server/tasks/main.yml
  roles/4-server-options/tasks/main.yml
  roles/httpd/tasks/main.yml
  roles/httpd/tasks/php-stem.yml
  roles/network/tasks/dansguardian.yml
  roles/network/tasks/squid.yml
Labels: enhancement

#1270 Fix for PR #1269
  roles/2-common/tasks/iiab-startup.yml
Labels: bug

#1272 Tweaks to PR #1271 (Ansible output)
  roles/awstats/tasks/install.yml
  roles/elgg/tasks/main.yml
  roles/nextcloud/tasks/main.yml
Labels: enhancement

#1273 Ansible output that educates en route (building on PRs #1271, #1272)
  roles/2-common/tasks/packages.yml
  roles/iiab-admin/tasks/access.yml
  roles/network/tasks/named.yml
  roles/network/tasks/squid.yml
  roles/nextcloud/tasks/main.yml
  roles/samba/tasks/main.yml
Labels: enhancement

#1274 Refinements to PR #1273
  roles/cups/tasks/main.yml
  roles/sugarizer/tasks/main.yml
Labels: enhancement
