Repository iiab/iiab, pull requests merged in 2018-07, with the labels that each got.

#866 Kiwix for i586 and i686 - towards resolving #864 & #865
  roles/kiwix/defaults/main.yml
  roles/kiwix/tasks/kiwix_install.yml
  roles/kiwix/tasks/main.yml
Labels: bug, help wanted

#874 Cleanup of Kiwix 0.6.0 (fixes reinstalls and readability)
  roles/kiwix/defaults/main.yml
  roles/kiwix/tasks/kiwix_install.yml
  roles/kiwix/tasks/main.yml
Labels: bug, enhancement

#875 Recommend Ansible 2.5.6 and 2.6.1
  scripts/ansible
  scripts/ansible-2.5.x
  scripts/ansible-2.6.x
Labels: enhancement

#879 Calibre with logins: implements #830 so teachers can add/remove/convert books & edit their metadata
  roles/calibre/defaults/main.yml
  roles/calibre/tasks/main.yml
  roles/calibre/templates/calibre-serve.service.j2
  roles/calibre/templates/users.sqlite
Labels: enhancement

#881 /library/calibre must be created prior to placing users.sqlite in there
  roles/calibre/tasks/create-db.yml
  roles/calibre/tasks/main.yml
Labels: bug

#882 Sugarizer: fixes part of #869 (comments must be on LEFT, in systemd unit files)
  roles/sugarizer/templates/sugarizer.service.j2
Labels: bug

#885 Deprecate Ansible 2.5.x recommendation
  scripts/ansible
  scripts/ansible-2.5.x-deprecated
  scripts/ansible-2.6.x
Labels: enhancement

#886 Revert "Avoiding OS's ancient version(s) of Calibre (blocks install on Ubuntu 16.04, slows others)"
  roles/calibre/tasks/main.yml
Labels: bug

#887 Mandate Ansible 2.5.6 as an absolute minimum
  iiab-install
Labels: enhancement

#888 sugarizer-server tweaks arising since Sugarizer 1.0
  roles/mongodb/tasks/main.yml
  roles/mongodb/templates/mongodb.service
  roles/sugarizer/defaults/main.yml
  roles/sugarizer/tasks/main.yml
  roles/sugarizer/templates/sugarizer.ini
Labels: bug, enhancement

#889 KA Lite 0.17.4 -> 0.17.5
  roles/kalite/defaults/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_big_vpn.yml
  vars/local_vars_medium.yml
  vars/local_vars_medium_vpn.yml
  vars/local_vars_min.yml
  vars/local_vars_min_vpn.yml
Labels: enhancement

#890 Kalite 0.17.5 quick fix to PR #889
  roles/kalite/tasks/main.yml
Labels: bug

#870 tweaking iptables for captive portal
  roles/network/defaults/main.yml
  roles/network/tasks/captive_portal.yml
  roles/network/tasks/enable_services.yml
  roles/network/tasks/main.yml
  roles/network/templates/captive_portal/captive_portal.py.j2
  roles/network/templates/captive_portal/captive_portal.service.j2
  roles/network/templates/gateway/iiab-gen-iptables
  roles/network/templates/network/dnsmasq.conf.j2
  vars/default_vars.yml
Labels: enhancement

#891 PR870 cleanup for understandability (dnsmasq, Captive Portal)
  roles/network/defaults/main.yml
  roles/network/tasks/captive_portal.yml
  roles/network/tasks/enable_services.yml
  vars/default_vars.yml
Labels: enhancement

#892 Sugarizer: faster and tighter git clone/pull using "depth: 1"
  roles/sugarizer/tasks/main.yml
Labels: enhancement

#893 Delete link (our understanding of Ansible was flawed)
  roles/httpd/tasks/main.yml
Labels: bug

#895 Kiwix-tools code for i586
  roles/kiwix/defaults/main.yml
Labels: bug

#896 Update local_vars.yml and default_vars.yml defaults
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_big_vpn.yml
  vars/local_vars_medium.yml
  vars/local_vars_medium_vpn.yml
  vars/local_vars_min.yml
  vars/local_vars_min_vpn.yml
Labels: enhancement

#897 Correct URI for IIAB license file
  roles/httpd/files/html/credits.html
Labels: enhancement

#900 Tighter playbook for Sugarizer 1.0
  roles/sugarizer/defaults/main.yml
  roles/sugarizer/tasks/main.yml
Labels: enhancement

#901 "npm install" fails with sudo, when installing Sugarizer 1.x
  roles/sugarizer/tasks/main.yml
Labels: bug

#905 npm install --unsafe-perm=true permits sudo install of Sugarizer 1.0+
  roles/sugarizer/tasks/main.yml
Labels: bug, enhancement

#904 [Debian 10] [Fixes #902] Generate correct os_ver for Debian 10/Buster Release
  scripts/local_facts.fact
  vars/debian-10.yml
Labels: enhancement

#903 Add Kolibri role for IIAB 6.6 Preview
  roles/kolibri/README.rst
  roles/kolibri/defaults/main.yml
  roles/kolibri/tasks/main.yml
  roles/kolibri/templates/kolibri.service.j2
Labels: enhancement

#906 Kolibri cleanup, default_vars.yml, local_vars.yml, roles/7-edu-apps/tasks/main.yml
  roles/7-edu-apps/tasks/main.yml
  roles/kolibri/README.rst
  roles/kolibri/defaults/main.yml
  roles/kolibri/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_big_vpn.yml
  vars/local_vars_medium.yml
  vars/local_vars_medium_vpn.yml
  vars/local_vars_min.yml
  vars/local_vars_min_vpn.yml
Labels: enhancement

#907 Revert kolibri_exec_path to usr /usr/local/bin for now
  roles/kolibri/defaults/main.yml
  roles/kolibri/tasks/main.yml
Labels: question

#909 KA Lite playbook cleaned up to modern Ansible syntax/style
  roles/kalite/tasks/assessment.yml
  roles/kalite/tasks/enable.yml
  roles/kalite/tasks/install-f18.yml
  roles/kalite/tasks/main.yml
  roles/kalite/tasks/setup.yml
Labels: enhancement

#914 Clean up daemon-reload in {2-common, KA Lite, Kolibri}
  roles/2-common/tasks/udev.yml
  roles/kalite/tasks/main.yml
  roles/kolibri/tasks/main.yml
Labels: enhancement

#916 Open kolibri port in iptables, for on-campus browsing on WAN side of IIAB (e.g. http://192.168.0.x:8009)
  roles/network/tasks/debian.yml
  roles/network/tasks/down-debian.yml
  roles/network/tasks/ifcfg_mods.yml
  roles/network/tasks/restart.yml
  roles/network/templates/gateway/iiab-gen-iptables
  vars/default_vars.yml
Labels: bug

#918 Fixes #917 [Kolibri systemd service says “active (exited)” instead of “active (running)”]
  roles/kolibri/templates/kolibri.service.j2
Labels: bug, enhancement

#919 MongoDB: many improvements for reliability
  roles/mongodb/defaults/main.yml
  roles/mongodb/tasks/main.yml
  roles/mongodb/templates/mongod.conf.j2
  roles/mongodb/templates/mongodb.service.j2
Labels: bug, enhancement

#924 Modernize syntax/readability of homepage+osm playbooks
  roles/homepage/tasks/main.yml
  roles/osm/tasks/main.yml
Labels: enhancement

#925 php-stem fixes search @ http://box/modules/es-wikihow
  roles/httpd/tasks/main.yml
  roles/httpd/tasks/php-stem.yml
Labels: bug, enhancement

#929 Louder Warning: keep "dns_jail_enabled: False" until AFTER install!
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_big_vpn.yml
  vars/local_vars_medium.yml
  vars/local_vars_medium_vpn.yml
  vars/local_vars_min.yml
  vars/local_vars_min_vpn.yml
Labels: enhancement

#931 /etc/iiab/local_vars.yml puts /opt/iiab/iiab/vars/local_vars.yml out of its misery
  CONTRIBUTING.md
  iiab-base.yml
  iiab-from-console.yml
  iiab-install
  iiab-network.yml
  iiab-stages.yml
  iiab.yml.deprecated
  install-support
  roles/4-server-options/README.rst
  roles/calibre/defaults/main.yml
  roles/calibre/templates/calibre.conf
  roles/kalite/defaults/main.yml
  roles/kolibri/defaults/main.yml
  roles/network/defaults/main.yml
  roles/rachel/README.rst
  run-one-role.yml
  scripts/ansible
  scripts/ansible-2.6.x
  vars/default_vars.yml
Labels: enhancement

#932 Deleting link requires 1 param not 2; named.yml cleanup
  roles/network/tasks/named.yml
Labels: bug, enhancement

#936 Elgg 2.3.7 -> 2.3.8
  roles/elgg/defaults/main.yml
Labels: enhancement

#937 Sync'd /opt/iiab/iiab/CONTRIBUTING.md with github.com/iiab/iiab/wiki/IIAB-Contributors-Guide
  CONTRIBUTING.md
Labels: enhancement

#939 Clarify ./iiab-install output, showing current working dir
  iiab-install
Labels: enhancement

#940 Clarify ./iiab-install output, showing caller/command's params too
  iiab-install
Labels: enhancement

#943 Comment out "mongod --repair" as interim workaround to #942 [MongoDB/Sugarizer]
  roles/mongodb/templates/mongodb.service.j2
Labels: bug

#945 Revert "Comment out "mongod --repair" as interim workaround to #942 [MongoDB/Sugarizer]"
  roles/mongodb/templates/mongodb.service.j2
Labels: question

#946 MongoDB+Sugarizer's systemd cleaned/clarified, to help diagnose #942 ?
  roles/mongodb/tasks/main.yml
  roles/sugarizer/tasks/main.yml
Labels: enhancement

#949 Calibre 3.27.1 glitch so remove from MEDIUM-sized local_vars.yml
  vars/local_vars_medium.yml
  vars/local_vars_medium_vpn.yml
Labels: bug

#950 Fix Calibre 3.27.1 on RPi (#948) using python-pyqt5 from debian testing
  roles/calibre/tasks/debs.yml
  scripts/calibre-install-latest-rpi-plus.sh
  scripts/calibre-install-latest-rpi.sh
  scripts/calibre-install-latest.sh
Labels: bug

#951 Revert "Calibre 3.27.1 glitch so remove from MEDIUM-sized local_vars.yml"
  vars/local_vars_medium.yml
  vars/local_vars_medium_vpn.yml
Labels: bug

#955 TEMP Fixes #954 [download.nextcloud.com's SSL/TLS cert expired 2018-07-22 preventing MEDIUM+BIG IIAB installs]
  roles/nextcloud/tasks/main.yml
Labels: bug

#956 Revert "TEMP Fixes #954 [download.nextcloud.com's SSL/TLS cert expired 2018-07-22 preventing MEDIUM+BIG IIAB installs]"
  roles/nextcloud/tasks/main.yml
Labels: bug

#957 Fix for #942 ? "mongod --repair" if /library/dbdata/mongodb/mongod.lock absent
  roles/mongodb/defaults/main.yml
  roles/mongodb/tasks/main.yml
  roles/mongodb/templates/iiab-mongodb-repair-if-no-lock.j2
  roles/mongodb/templates/mongodb.service.j2
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_big_vpn.yml
  vars/local_vars_medium.yml
  vars/local_vars_medium_vpn.yml
  vars/local_vars_min.yml
  vars/local_vars_min_vpn.yml
Labels: bug

#962 iiab-install code cleanup (clarifies that /etc/iiab/local_vars.yml MUST already be in place)
  iiab-install
Labels: enhancement

#966 Label unused files as .deprecated in /opt/iiab/iiab
  runansible.deprecated
  runtags.deprecated
Labels: enhancement

#967 Vpnnext
  roles/nextcloud/templates/nextcloud.conf.j2
  vars/default_vars.yml
Labels: enhancement

#959 Add concurrency to iiab-make-kiwix-lib
  roles/kiwix/templates/iiab-make-kiwix-lib
  roles/kiwix/templates/iiab-make-kiwix-lib.py
Labels: bug, enhancement

#970 Ansible minimum version: 2.5.6 -> 2.5.7
  iiab-install
Labels: enhancement

#971 Calibre 3.28 (from "raspbian testing" w/o Debian .deb's) permits IIAB to boot+work in Zero W
  roles/calibre/tasks/debs.yml
Labels: enhancement

#975 Quick cleanup or 0-init/tasks/main.yml
  roles/0-init/tasks/main.yml
Labels: enhancement

#978 Recommend Ansible 2.6.2
  scripts/ansible
  scripts/ansible-2.6.x
Labels: enhancement
