Repository iiab/iiab, pull requests merged in 2018-02, with the labels that each got.

#670 AWStats indentation/syntax per new Ansible documentation
  roles/awstats/tasks/install.yml
  roles/awstats/tasks/main.yml
Labels: enhancement

#659 need sqlite3 for rachel maps
  roles/httpd/tasks/main.yml
Labels: bug, enhancement

#672 comments clarified: Ansible 2.4.2 override for now
  scripts/ansible
Labels: bug, enhancement

#673 documentation/indendation/syntax cleanup of usb-lib
  roles/usb-lib/README.rst
  roles/usb-lib/tasks/main.yml
Labels: enhancement

#674 indentation/syntax per new Ansible docs in 0-init; descriptions for all 9 stages
  roles/0-init/defaults/main.yml
  roles/0-init/tasks/fl.yml
  roles/0-init/tasks/hostname.yml
  roles/0-init/tasks/iiab_ini.yml
  roles/0-init/tasks/main.yml
  roles/0-init/tasks/tz.yml
  roles/1-prep/README.rst
  roles/2-common/README.rst
  roles/3-base-server/README.rst
  roles/4-server-options/README.rst
  roles/5-xo-services/README.rst
  roles/6-generic-apps/README.rst
  roles/7-edu-apps/README.rst
  roles/8-mgmt-tools/README.rst
  roles/9-local-addons/README.rst
Labels: enhancement

#675 1-prep: raspberry_pi_2.yml -> raspberry_pi.yml; indentation/syntax per new Ansible docs
  roles/1-prep/tasks/main.yml
  roles/1-prep/tasks/raspberry_pi.yml
  roles/1-prep/tasks/raspberry_pi_2.yml
Labels: enhancement

#676 2-common: indentation/syntax per new Ansible docs
  roles/2-common/tasks/iptables.yml
  roles/2-common/tasks/main.yml
  roles/2-common/tasks/net_mods.yml
  roles/2-common/tasks/prep.yml
  roles/2-common/tasks/udev.yml
Labels: enhancement

#677 3-base-server: indentation/syntax per new Ansible docs
  roles/3-base-server/tasks/main.yml
Labels: enhancement

#678 Stages 4-9: main.yml indentation/syntax per new Ansible docs
  roles/4-server-options/tasks/main.yml
  roles/5-xo-services/tasks/main.yml
  roles/6-generic-apps/tasks/main.yml
  roles/7-edu-apps/tasks/main.yml
  roles/8-mgmt-tools/tasks/main.yml
  roles/9-local-addons/tasks/main.yml
Labels: enhancement

#679 FQDN fix in 0-init/tasks/hostname.yml
  roles/0-init/tasks/hostname.yml
Labels: bug

#680 4-server-options explained more clearly (mandatory stuff might belong in 3-base-server)
  roles/4-server-options/README.rst
  roles/4-server-options/tasks/main.yml
Labels: enhancement

#681 Tech Docs: README's for Stage 5-9 further clarified
  roles/5-xo-services/README.rst
  roles/6-generic-apps/README.rst
  roles/7-edu-apps/README.rst
  roles/8-mgmt-tools/README.rst
  roles/9-local-addons/README.rst
Labels: enhancement

#682 automount USB exFAT sticks (& possibly portable NTFS disks too)
  roles/usb-lib/tasks/main.yml
  roles/usb-lib/templates/usbmount.rules.j2
  roles/usb-lib/templates/usbmount@.service.j2
Labels: enhancement

#668 do not ignore gui request for fixed ip
  roles/network/tasks/computed_network.yml
Labels: bug

#686 phpMyAdmin 4.7.7 -> 4.7.8 security fix
  roles/phpmyadmin/defaults/main.yml
Labels: enhancement

#691 kiwix-tools 2017-12-27 -> 2018-02-26
  roles/kiwix/defaults/main.yml
Labels: bug, enhancement

#692 some confusion about alias name, add the other one
  roles/awstats/templates/apache.conf
Labels: bug, enhancement
