Repository iiab/iiab, pull requests merged in 2018-08, with the labels that each got.

#980 Use Kiwix default URI box.lan/kiwix
  roles/kiwix/README.rst
  roles/kiwix/defaults/main.yml
  roles/kiwix/templates/kiwix.conf.j2
Labels: enhancement

#982 Elgg code cleanup, in preparation for 3.0.0 later this year?
  roles/elgg/README.rst
  roles/elgg/defaults/main.yml
  roles/elgg/tasks/main.yml
Labels: enhancement

#985 Simplify kiwix config
  roles/kiwix/defaults/main.yml
  roles/kiwix/templates/kiwix.conf.j2
Labels: enhancement

#984 php-stem cleanup for Debian 9 x86_64? (Do Debian 10, Ubuntu 18.04 & i686 presumably all fail?)
  roles/httpd/tasks/php-stem.yml
Labels: bug

#988 Consistent naming of *.deprecated files in /opt/iiab/iiab
  README.md.deprecated
Labels: enhancement

#990 Kiwix README Cleanup
  roles/kiwix/README.rst
Labels: enhancement

#996 Use openvpn_handle variable to set /etc/iiab/handle
  roles/openvpn/defaults/main.yml
  roles/openvpn/tasks/main.yml
  roles/openvpn/templates/announcer
  roles/openvpn/templates/iiab-handle.j2
  roles/openvpn/templates/iiab-vpn.j2
  roles/openvpn/templates/openvpn_handle.j2
  roles/openvpn/templates/party-line.conf.j2
  roles/openvpn/templates/xscenet.conf.j2
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_big_vpn.yml
  vars/local_vars_medium.yml
  vars/local_vars_medium_vpn.yml
  vars/local_vars_min.yml
  vars/local_vars_min_vpn.yml
Labels: enhancement

#997 Clarify openvpn_handle variable and /etc/iiab/openvpn_handle
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_big_vpn.yml
  vars/local_vars_medium.yml
  vars/local_vars_medium_vpn.yml
  vars/local_vars_min.yml
  vars/local_vars_min_vpn.yml
Labels: enhancement

#998 OpenVPN announcer fixes/cleanup
  roles/openvpn/tasks/main.yml
  roles/openvpn/templates/announcer
  roles/openvpn/templates/announcer.j2
Labels: bug, enhancement

#1000 OpenVPN resiliency improvements
  roles/openvpn/defaults/main.yml
  roles/openvpn/tasks/main.yml
  roles/openvpn/templates/15-openvpn
  roles/openvpn/templates/announcer.j2
  roles/openvpn/templates/iiab-handle.j2
  roles/openvpn/templates/iiab-remote-on.j2
  roles/openvpn/templates/iiab-vpn.conf.in.deprecated
  roles/openvpn/templates/iiab-vpn.j2.deprecated
  roles/openvpn/templates/party-line.conf.j2.deprecated
  roles/openvpn/templates/start.j2
  roles/openvpn/templates/start.j2.deprecated
  roles/openvpn/templates/up_wan
  roles/openvpn/templates/xsce-vpn.conf.in.deprecated
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_big_vpn.yml
  vars/local_vars_medium.yml
  vars/local_vars_medium_vpn.yml
  vars/local_vars_min.yml
  vars/local_vars_min_vpn.yml
Labels: enhancement

#1001 OpenVPN code readability
  roles/openvpn/tasks/main.yml
  roles/openvpn/templates/15-openvpn
  roles/openvpn/templates/announce
  roles/openvpn/templates/up_wan
  roles/openvpn/templates/xscenet.conf.j2
Labels: enhancement

#1003 openvpn_handle variable explained
  roles/openvpn/tasks/main.yml
Labels: enhancement

#1005 Remove TWO duplicate credits.html files (a 4th copy remains in github.com/iiab/iiab-admin-console)
  roles/httpd/files/html/credits.html
  roles/httpd/files/html/html/credits.html
Labels: enhancement

#1009 Ansible 2.6.2 -> 2.6.3
  iiab-install
  scripts/ansible
  scripts/ansible-2.6.x
Labels: enhancement

#1012 Strengthen keyserver.ubuntu.com warning, as this still fails regularly when installing Ansible
  scripts/ansible
  scripts/ansible-2.6.x
Labels: enhancement

#1013 Keys
  roles/iiab-admin/tasks/admin-user.yml
  roles/openvpn/tasks/main.yml
Labels: enhancement

#1014 OpenVPN documentation cleanup
  roles/openvpn/tasks/main.yml
Labels: enhancement

#1015 Calibre 3.29 has serious dependency problems on Raspbian
  roles/calibre/tasks/debs.yml
  scripts/calibre-install-latest-rpi-plus.sh
  scripts/calibre-install-latest-rpi.sh
  scripts/calibre-install-latest.sh
  scripts/calibre-install-unstable.sh
Labels: bug, enhancement

#1016 httpd playbook output clarified
  roles/httpd/tasks/html.yml
  roles/httpd/tasks/main.yml
Labels: enhancement

#1017 Deprecate Teamviewer & unused vars in default_vars.yml, local_vars.yml
  roles/teamviewer/defaults/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_big_vpn.yml
  vars/local_vars_medium.yml
  vars/local_vars_medium_vpn.yml
  vars/local_vars_min.yml
  vars/local_vars_min_vpn.yml
Labels: enhancement

#1018 Hostapd tweak
  roles/network/templates/hostapd/hostapd.service.j2
Labels: enhancement

#1019 More fully deprecate sugar-stats
  roles/8-mgmt-tools/tasks/main.yml
  roles/network/tasks/main.yml
Labels: enhancement

#1020 More fully deprecate TeamViewer playbook
  roles/8-mgmt-tools/tasks/main.yml
Labels: enhancement

#1021 More fully deprecate TeamViewer playbook (part 2)
  roles/8-mgmt-tools/tasks/main.yml
Labels: bug

#1022 Tweaks to OpenVPN & httpd code comments
  roles/httpd/tasks/main.yml
  roles/openvpn/templates/announcer.j2
Labels: bug, enhancement

#1024 phpMyAdmin 4.8.2 -> 4.8.3 security fix
  roles/phpmyadmin/defaults/main.yml
Labels: bug, enhancement

#1026 Clean up a central copy of credits.html (not 4!)
  roles/httpd/files/html/credits.html
  roles/httpd/files/html/html/credits.html
Labels: enhancement

#851 http://box/sugarizer fix on RPi & All OS's? (Sugarizer 1.0+)
  roles/sugarizer/tasks/main.yml
  roles/sugarizer/templates/sugarizer.conf
  roles/sugarizer/templates/sugarizer.js
Labels: bug, enhancement

#1029 Make all 5 Calibre install scripts consistent
  scripts/calibre-install-latest-rpi-plus.sh
  scripts/calibre-install-latest-rpi.sh
  scripts/calibre-install-latest.sh
  scripts/calibre-install-packages.sh
  scripts/calibre-install-unstable.sh
Labels: enhancement

#1030 Ansible verbiage tweak
  scripts/ansible
  scripts/ansible-2.6.x
Labels: enhancement

#1042 15 -> 30min: double allotted time for Nextcloud download & "kalite manage"
  roles/kalite/tasks/setup.yml
  roles/nextcloud/tasks/main.yml
Labels: bug, enhancement

#1043 roles/calibre-web/README.rst more readable!
  roles/calibre-web/README.rst
Labels: enhancement

#1044 BitTorrent tool "Transmission" eases KA Lite downloads
  roles/8-mgmt-tools/tasks/main.yml
  roles/network/templates/gateway/iiab-gen-iptables
  roles/transmission/README.rst
  roles/transmission/defaults/main.yml
  roles/transmission/tasks/main.yml
  roles/transmission/templates/settings.json.j2
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_big_vpn.yml
  vars/local_vars_medium.yml
  vars/local_vars_medium_vpn.yml
  vars/local_vars_min.yml
  vars/local_vars_min_vpn.yml
Labels: enhancement

#1045 Calibre-Web "Known Issues" clarified for IIAB 6.6 final release
  roles/calibre-web/README.rst
Labels: enhancement

#1049 Tweak roles/calibre-web/README.rst
  roles/calibre-web/README.rst
Labels: enhancement

#1054 kiwix-tools 0.6.0 -> 0.6.1
  roles/kiwix/defaults/main.yml
Labels: enhancement

#1056 Update http://box/maps & http://box/osm to point to new Vector Maps
  roles/osm/tasks/main.yml
  roles/osm/templates/osm.conf.j2
Labels: enhancement

#1057 Pin Calibre (to 3.30 for now) avoiding dependency hell on each new Calibre release
  roles/calibre/defaults/main.yml
  roles/calibre/tasks/debs.yml
  roles/calibre/tasks/main.yml
  scripts/calibre-install-pinned-rpi.sh
Labels: enhancement

#1058 Deprecate Unmaintained roles for IIAB 6.6 release
  roles/0-init/tasks/main.yml
  roles/6-generic-apps/tasks/main.yml
  roles/7-edu-apps/tasks/main.yml
  roles/8-mgmt-tools/tasks/main.yml
  roles/9-local-addons/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1059 Quick Doc Cleanups: KA Lite, Calibre-Web, Transmission
  roles/calibre-web/tasks/main.yml
  roles/kalite/README.rst
  roles/kalite/tasks/main.yml
  roles/transmission/README.rst
Labels: enhancement

#1060 http://box/kiwix was failing
  roles/kiwix/templates/kiwix.conf.j2
Labels: bug, enhancement

#1061 Transmission (BitTorrent) network activity caused SLOW IIAB installs :/
  roles/8-mgmt-tools/tasks/main.yml
  roles/9-local-addons/tasks/main.yml
  roles/transmission/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: bug, enhancement

#1062 Ansible deprecating internet_access_test|failed (so try internet_access_test.failed)
  roles/0-init/tasks/main.yml
Labels: bug, enhancement
