Repository iiab/iiab, pull requests merged in 2018-12, with the labels that each got.

#1318 Allow systemd-resolved AND dnsmasq to work (for Ubuntu especially)
  roles/network/tasks/dnsmasq.yml
  roles/network/tasks/named.yml
  roles/network/templates/network/dnsmasq-iiab
Labels: bug, enhancement

#1327 Cap3 [captive-portal under Apache; disconnected from wsgi & iptables]
  roles/captive-portal/tasks/main.yml
  roles/captive-portal/templates/001-captive-portal.conf
  roles/captive-portal/templates/capture-wsgi.py
  roles/network/templates/gateway/iiab-gen-iptables
Labels: enhancement

#1329 Document "js_menu_install: False" for those who want legacy Dynamic Menuing
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1328 Officially transition from Nextcloud 14 to 15
  roles/nextcloud/defaults/main.yml
Labels: enhancement

#1333 Captive Portal docs revised (local_vars.yml, default_vars.yml, FAQ.IIAB.IO)
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: bug, enhancement

#1334 captive-portal tweak (code maintainability, not functional changes)
  roles/captive-portal/tasks/main.yml
  roles/captive-portal/templates/captive-portal.service.j2.deprecated
Labels: enhancement

#1335 captive-portal is no longer a systemd service
  roles/captive-portal/templates/iiab-catch
  roles/captive-portal/templates/iiab-uncatch
Labels: bug

#1337 Recommend Ansible 2.7.5
  iiab-install
  scripts/ansible
  scripts/ansible-2.6.x
  scripts/ansible-2.7.x
Labels: enhancement

#1342 Elgg 2.3.10
  roles/elgg/defaults/main.yml
Labels: enhancement

#1343 kiwix-tools 0.8.0 -> 0.8.0-2
  roles/kiwix/defaults/main.yml
Labels: enhancement
