Repository iiab/iiab, pull requests merged in 2018-04, with the labels that each got.

#728 Elgg 2.3.5 -> 2.3.6 LTS (with 3.0.0 on the horizon)
  roles/elgg/defaults/main.yml
Labels: enhancement

#732 Prune bitrot from /opt/iiab/iiab/ansible.cfg
  ansible.cfg
  ansible.cfg.deprecated
Labels: enhancement

#734 use stock OS provided deb on RPI's
  roles/calibre/tasks/debs.yml
Labels: enhancement

#726 fix6.5 - auto-enable hostapd (during Ethernet install of IIAB)
  roles/0-init/tasks/main.yml
  roles/httpd/tasks/main.yml
  roles/network/defaults/main.yml
  roles/network/tasks/computed_network.yml
  roles/network/tasks/hostapd.yml
  roles/network/tasks/ifcfg_mods.yml
  roles/network/tasks/main.yml
  roles/network/tasks/rpi_debian.yml
Labels: bug, enhancement

#735 Ubuntu fix to clean install scripts/ansible-2.4.x OR scripts/ansible-2.5.x OR scripts/ansible
  scripts/ansible
  scripts/ansible-2.2.0-deprecated
  scripts/ansible-2.4.x
  scripts/ansible-2.5.x
Labels: bug, enhancement

#737 calibre: revert PR734 for now (playbook fails every time)
  roles/calibre/tasks/debs.yml
Labels: bug

#742 scripts/ansible* cleanup - see github.com/jvonau/iiab/issues/18
  scripts/ansible
  scripts/ansible-2.4.x
  scripts/ansible-2.5.x
Labels: enhancement

#741 fix enabling hostapd
  iiab-network
  roles/network/tasks/NM-debian.yml
  roles/network/tasks/debian.yml
  roles/network/tasks/enable_services.yml
  roles/network/tasks/hostapd.yml
  roles/network/tasks/ifcfg_mods.yml
  roles/network/tasks/main.yml
  roles/network/tasks/restart.yml
  roles/network/tasks/rpi_debian.yml
  roles/network/tasks/sysd-netd-debian.yml
Labels: bug

#739 cal-rpi2: refine Calibre install approaches for each OS
  roles/calibre/defaults/main.yml
  roles/calibre/tasks/debs.yml
  roles/calibre/tasks/main.yml
  scripts/calibre-install-latest-rpi.sh
  scripts/calibre-install-latest.sh
  scripts/calibre-install-unstable.sh
  vars/default_vars.yml
  vars/ubuntu-18.yml
Labels: enhancement

#746 Speedup by squashing package installs in ansible.cfg (condenses loop)
  ansible.cfg
Labels: enhancement

#749 DokuWiki 2017-02-19e -> 2018-04-22
  roles/dokuwiki/defaults/main.yml
  roles/dokuwiki/tasks/install.yml
Labels: bug, enhancement

#757 Fixes for Ubuntu 18.04
  scripts/local_facts.fact
  vars/ubuntu-18.yml
Labels: bug, enhancement

#758 vars/ubuntu-18.yml requires "postgresql_version: 10" not 10.3
  vars/ubuntu-18.yml
Labels: bug

#760 Ubuntu 18.04's PostgreSQL 10.3 requires Moodle encrypt (hash) its password
  roles/moodle/tasks/main.yml
Labels: bug

#763 Minor refactor of {iiab-vpn, iiab-remote-off, iiab-remote-on} for readability
  roles/openvpn/templates/iiab-remote-off
  roles/openvpn/templates/iiab-remote-on
  roles/openvpn/templates/iiab-vpn
Labels: enhancement

#764 #!/bin/sh -> #!/bin/bash for iiab-make-kiwix-lib
  roles/kiwix/templates/iiab-make-kiwix-lib
Labels: enhancement

#762 ubuntu-changes: Nextcloud & Sugarizer tweaks for Ubuntu 18.04
  roles/0-init/tasks/main.yml
  roles/nextcloud/tasks/main.yml
  roles/sugarizer/tasks/main.yml
Labels: bug, enhancement

#766 Sugarizer on Ubuntu 18.04 conditionals: ubuntu-18 -> is_ubuntu_18
  roles/sugarizer/tasks/main.yml
Labels: bug
