Repository iiab/iiab, pull requests merged in 2018-05, with the labels that each got.

#769 NM not playing nice on ubuntu-16, use older method
  roles/network/tasks/main.yml
  roles/network/templates/dhcp/dhcpd.service
  roles/network/templates/hostapd/hostapd.service.j2
  vars/default_vars.yml
  vars/ubuntu-16.yml
Labels: bug

#768 Moodle 3.1 -> 3.5 LTS TESTING (on Moodle's master branch for now)
  roles/moodle/defaults/main.yml
  roles/moodle/tasks/main.yml
  roles/moodle/templates/moodle_installer
Labels: enhancement

#771 use py-installer.yml for Ubuntu 18.04 (to install the latest Calibre)
  roles/calibre/tasks/main.yml
Labels: enhancement

#772 Remove br0 in Appliance Mode for NetworkManager (e.g. if no internal WiFi)
  roles/network/defaults/main.yml
  roles/network/tasks/NM-debian.yml
  roles/network/tasks/dhcpd.yml
  roles/network/tasks/sysd-netd-debian.yml
  roles/network/templates/dhcp/dhcpd.service
  roles/network/templates/network/systemd-br0-network.j2
Labels: bug, enhancement

#777 DokuWiki 2018-04-22 -> 2018-04-22a (hotfix)
  roles/dokuwiki/defaults/main.yml
Labels: enhancement

#781 ejabberd-iiab.service 755->644; ejabberd-iiab.init 644->755
  roles/ejabberd/tasks/main.yml
Labels: bug

#783 admin-console needs $HOME set
  ansible.cfg
Labels: admin console, bug

#784 host_country_code: US moved to local_vars.yml; download_timeout: 100 -> 200 for Haiti
  roles/network/defaults/main.yml
  vars/default_vars.yml
  vars/medium.localvars
Labels: enhancement

#788 recurse into apache log directory with www-data
  roles/awstats/tasks/install.yml
Labels: bug

#791 Static deb9 (fixed IP address, for Ubuntu 16.04 too)
  roles/2-common/tasks/packages.yml
  roles/network/defaults/main.yml
  roles/network/tasks/NM-debian.yml
  roles/network/tasks/debian.yml
  roles/network/tasks/sysd-netd-debian.yml
  roles/network/templates/network/NM-static.j2
  roles/network/templates/network/cloud-init.j2
  roles/network/templates/network/debian-auto.j2
  roles/network/templates/network/systemd-static-net.j2
  roles/network/templates/network/systemd.j2
Labels: enhancement

#793 missing .j2
  roles/network/tasks/debian.yml
Labels: bug

#794 missing %}
  roles/network/templates/network/systemd.j2
Labels: bug

#795 allow backout from static to dhcp
  roles/network/tasks/debian.yml
Labels: enhancement

#797 6 local_vars files -> GitHub
  iiab-install
  runansible
  vars/local_vars_big.yml
  vars/local_vars_big_vpn.yml
  vars/local_vars_medium.yml
  vars/local_vars_medium_vpn.yml
  vars/local_vars_min.yml
  vars/local_vars_min_vpn.yml
  vars/local_vars_olpc.yml
Labels: enhancement

#792 Moodle 3.5beta+ (master) -> MOODLE_35_STABLE
  roles/moodle/tasks/main.yml
Labels: enhancement

#800 really call hostname.yml (U18 hostname was "ubuntu18base" even after reboot)
  roles/0-init/tasks/hostname.yml
  roles/0-init/tasks/main.yml
Labels: bug

#801 vars/local_vars* - change runtags to runrole in comments
  vars/local_vars_big.yml
  vars/local_vars_big_vpn.yml
  vars/local_vars_medium.yml
  vars/local_vars_medium_vpn.yml
  vars/local_vars_min.yml
  vars/local_vars_min_vpn.yml
Labels: enhancement

#802 Recommend Ansible 2.5.3 for all
  scripts/ansible
  scripts/ansible-2.5.x
Labels: enhancement

#805 handle systemd-networkd having enabled-runtime
  roles/network/tasks/detected_network.yml
  roles/network/tasks/sysd-netd-debian.yml
Labels: bug

#808 OSM - pin Flask to version 0.12.4
  roles/osm/tasks/main.yml
Labels: bug, enhancement

#809 load php-sqlite on ubuntu
  ansible.cfg
  roles/httpd/tasks/main.yml
Labels: bug

#813 Move .ansible/tmp from /library/working -> /root (proposed fix for #812)
  ansible.cfg
Labels: bug

#818 kiwix-tools 0.5.0 (2018-04-23) -> 2018-05-24 fixes FT search w/ internal index
  roles/kiwix/defaults/main.yml
Labels: bug

#819 kiwix-tools 0.5.0 (2018-04-23) -> 2018-05-24 fixes FT search w/ internal index
  roles/kiwix/defaults/main.yml
Labels: bug

#820 Elgg 2.3.6 -> 2.3.7
  roles/elgg/defaults/main.yml
Labels: enhancement

#821 phpMyAdmin 4.8.0.1 -> 4.8.1
  roles/phpmyadmin/defaults/main.yml
Labels: enhancement
