Repository iiab/iiab, pull requests merged in 2018-06, with the labels that each got.

#832 Recommend Ansible 2.5.3 -> 2.5.4
  scripts/ansible
  scripts/ansible-2.5.x
Labels: enhancement

#833 install Calibre via Debian .debs insteads of Raspbian .debs (fixes 831)
  roles/calibre/tasks/debs.yml
  scripts/calibre-install-latest-rpi.sh
  scripts/calibre-install-latest.sh
  scripts/calibre-install-unstable.sh
Labels: bug

#834 install Calibre via Debian .debs insteads of Raspbian .debs (fixes 831)
  roles/calibre/tasks/debs.yml
  roles/elgg/defaults/main.yml
  roles/phpmyadmin/defaults/main.yml
  scripts/ansible
  scripts/ansible-2.5.x
  scripts/calibre-install-latest-rpi.sh
  scripts/calibre-install-latest.sh
  scripts/calibre-install-unstable.sh
Labels: bug

#825 Fallback to old gateway info when WAN is not detected
  roles/4-server-options/tasks/main.yml
  roles/network/tasks/computed_network.yml
  roles/network/tasks/dnsmasq.yml
  roles/network/tasks/enable_services.yml
  roles/network/templates/network/dnsmasq.conf.j2
Labels: bug

#838 iiab_base_ver: 6.5 to 6.6 in roles/0-init/defaults/main.yml
  roles/0-init/defaults/main.yml
Labels: enhancement

#839 Latest Calibre(s) insertable-tho-not-runnable in RPi Zero W: use pkgs from Calibre 3.23
  roles/calibre/tasks/debs.yml
  scripts/calibre-install-latest-rpi.sh
  scripts/calibre-install-latest.sh
  scripts/calibre-install-packages.sh
Labels: enhancement

#836 MediaWiki 1.30.0 -> 1.31.0 LTS
  roles/mediawiki/defaults/main.yml
  roles/mediawiki/templates/LocalSettings.php.j2
Labels: enhancement

#843 Stale Ansible Warnings Strengthened
  scripts/ansible
  scripts/ansible-2.4.x-deprecated
  scripts/ansible-2.5.x
Labels: enhancement

#844 Fix LocalSettings.php [and auto-generate it during MediaWiki installs]
  roles/mediawiki/tasks/install.yml
  roles/mediawiki/templates/LocalSettings.php.j2
Labels: bug

#845 kiwix-tools 2018-05-24 -> 0.6.0 (2018-06-20)
  roles/kiwix/defaults/main.yml
Labels: enhancement

#846 Extend systemd Timeout so Calibre can boot in RPi Zero W
  roles/calibre/templates/calibre-serve.service.j2
Labels: bug, enhancement

#847 scripts/ansible needs dirmngr only; prereqs not needed: python-pip python-setuptools python-wheel patch
  scripts/ansible
  scripts/ansible-2.5.x
Labels: enhancement

#848 Calibre 3.26.0 permits revert of PR833 & PR839
  roles/calibre/tasks/debs.yml
  scripts/calibre-install-packages.sh
Labels: enhancement

#814 Sugarizer v1.0 migration
  roles/0-init/tasks/main.yml
  roles/mongodb/tasks/main.yml
  roles/mongodb/templates/mongod.conf
  roles/mongodb/templates/mongodb
  roles/mongodb/templates/mongodb.service
  roles/mongodb/templates/mongodb~HEAD
  roles/network/templates/gateway/iiab-gen-iptables
  roles/sugarizer/defaults/main.yml
  roles/sugarizer/meta/main.yml
  roles/sugarizer/tasks/main.yml
  roles/sugarizer/templates/sugarizer.conf
  roles/sugarizer/templates/sugarizer.ini
  roles/sugarizer/templates/sugarizer.service.j2
  vars/default_vars.yml
Labels: enhancement

#849 phpMyAdmin 4.8.1 -> 4.8.2 security fix
  roles/phpmyadmin/defaults/main.yml
Labels: bug, enhancement

#850 Recommend Ansible 2.5.5+
  scripts/ansible
  scripts/ansible-2.5.x
Labels: enhancement

#858 Revise Ansible recommendation from 2.5.5 to 2.6.0
  scripts/ansible
  scripts/ansible-2.5.x
  scripts/ansible-2.6.x
Labels: enhancement

#862 Remove Travis tag
  README.md
Labels: bug
