Repository iiab/iiab, pull requests merged in 2018-03, with the labels that each got.

#687 Wip Feb 21 - restart kiwix on abort / add Indian language codes
  roles/httpd/files/html/assets/lang_codes.json
  roles/kiwix/templates/kiwix-serve.service.j2
Labels: enhancement

#683 perhaps debian moved hwclock from /usr/sbin to /sbin
  roles/1-prep/templates/92-rtc-i2c.rules
Labels: bug, question

#701 phpMyAdmin 4.7.8 -> 4.7.9 maintenance fix
  roles/phpmyadmin/defaults/main.yml
Labels: enhancement

#703 introduce default & local vars "mediawiki_install: False" and "mediawiki_enabled: False"
  vars/default_vars.yml
  vars/medium.localvars
Labels: enhancement

#702 MediaWiki - introduce new role as part of IIAB
  roles/6-generic-apps/tasks/main.yml
  roles/mediawiki/defaults/main.yml
  roles/mediawiki/tasks/install.yml
  roles/mediawiki/tasks/main.yml
  roles/mediawiki/templates/LocalSettings.php.j2
  roles/mediawiki/templates/mediawiki.conf.j2
Labels: enhancement

#704 refactor roles/pathagar/tasks/main.yml per new Ansible syntax/style
  roles/pathagar/tasks/main.yml
Labels: enhancement

#707 MediaWiki documentation/style tweaks
  roles/mediawiki/tasks/install.yml
Labels: enhancement

#708 /mediawiki corrected/clarified in local_vars.yml
  vars/medium.localvars
Labels: bug, enhancement

#713 NM correct permissions, lockout of hostapd, fix boot race
  roles/network/tasks/NM-debian.yml
  roles/network/templates/dhcp/dhcpd.service
  roles/network/templates/hostapd/hostapd.service.j2
Labels: bug, enhancement

#717 kiwix-tools 2018-02-26 -> 0.4.0 for armhf & linux64
  roles/kiwix/defaults/main.yml
  roles/kiwix/tasks/kiwix_install.yml
  roles/kiwix/tasks/main.yml
Labels: enhancement

#719 basic cleanup/refactoring of ./runtags & roles/1-prep/templates/iiab.env.j2
  roles/1-prep/templates/iiab.env.j2
  runtags
Labels: enhancement

#722 delay usbmount's actions during boot to be as late as possible
  roles/usb-lib/templates/usbmount@.service.j2
Labels: bug, enhancement
