Repository iiab/iiab, pull requests merged in 2019-01, with the labels that each got.

#1348 mysql -> mariadb & ssh -> openssh-server in vars/ubuntu-18.yml & others
  roles/0-init/tasks/main.yml
  roles/2-common/tasks/packages.yml
  roles/sshd/tasks/main.yml
  vars/centos-7.yml
  vars/debian-10.yml
  vars/debian-8.yml
  vars/debian-9.yml
  vars/fedora-18.yml
  vars/fedora-22.yml
  vars/raspbian-8.yml
  vars/raspbian-9.yml
  vars/ubuntu-16.yml
  vars/ubuntu-17.yml
  vars/ubuntu-18.yml
Labels: bug

#1336 Netplan - WIP
  roles/network/tasks/dnsmasq.yml
  roles/network/tasks/enable_services.yml
  roles/network/tasks/main.yml
  roles/network/tasks/netplan.yml
  roles/network/tasks/sysd-netd-debian.yml
  roles/network/templates/hostapd/hostapd.service.j2
  roles/network/templates/network/cloud-init.j2
  roles/network/templates/network/dnsmasq.service.u18
  roles/network/templates/network/netplan.j2
Labels: enhancement

#1349 Update iiab-hotspot-on & -off commands from dhcpd to dnsmasq
  roles/network/templates/network/iiab-hotspot-off
  roles/network/templates/network/iiab-hotspot-on
Labels: bug, enhancement

#1350 fix WiFi as gateway
  roles/network/tasks/restart.yml
Labels: bug

#1317 Create Lokole admin user during setup
  roles/lokole/defaults/main.yml
  roles/lokole/tasks/install.yml
Labels: enhancement

#1305 Expand Lokole documentation
  roles/lokole/README.rst
  roles/lokole/The Lokole-IIAB User's Manual.pdf
Labels: enhancement

#1352 Redefine default_vars.yml from MEDIUM-sized to MIN-sized
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1353 Lokole: change admin to Admin per IIAB app norms
  roles/lokole/defaults/main.yml
Labels: enhancement

#1354 Revert "Lokole: change admin to Admin per IIAB app norms"
  roles/lokole/defaults/main.yml
Labels: bug

#1357 roles/lokole/README.rst readability improvements
  roles/lokole/README.rst
Labels: enhancement

#1363 Captive Portal: patch capture-wsgi.py to test Android 7.x, 8.x, 9.x
  roles/captive-portal/templates/capture-wsgi.py
Labels: bug, enhancement

#1364 dnsmasq hack (in roles/captive-portal/tasks/main.yml) so iiab-install runs on Ubuntu 16.04
  roles/captive-portal/tasks/main.yml
Labels: bug, enhancement, question

#1365 phpMyAdmin 3.8.3 -> 4.8.4
  roles/phpmyadmin/defaults/main.yml
Labels: enhancement

#1369 Set squid_install: & squid_enabled: False in BIG-sized local_vars.yml
  roles/0-init/tasks/main.yml
  roles/4-server-options/tasks/main.yml
  roles/7-edu-apps/tasks/main.yml
  roles/8-mgmt-tools/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1370 Address TODOs in Lokole documentation
  roles/lokole/README.rst
Labels: enhancement

#1372 Force minor upgrades of Nextcloud if /opt/nextcloud/version.php removed
  roles/nextcloud/tasks/main.yml
Labels: bug

#1374 Remove DansGuardian from BIG-sized local_vars.yml to fix #1373
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: bug

#1378 Calibre-Web: document that "variable" calibreweb_port: 8083 has no effect
  roles/calibre-web/defaults/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: bug, enhancement

#1379 box.lan NOT iiab-server.lan
  roles/network/tasks/hosts.yml
Labels: enhancement

#1380 Install /etc/tmpfiles.d/iiab.conf during IIAB install process, for Ubermix
  roles/1-prep/files/iiab.conf
  roles/1-prep/tasks/main.yml
Labels: enhancement

#1385 Detect Ubermix using /etc/lsb-release; clean /etc/tmpfiles.d/iiab.conf; force 'apt -y remove "libgeos-*"' for KA Lite
  roles/1-prep/files/iiab.conf
  roles/1-prep/tasks/main.yml
  roles/kalite/tasks/install.yml
Labels: bug

#1386 Fixes for 2019's Debian 10 "Buster" + 3 outstanding issues incl workarounds
  roles/nextcloud/tasks/main.yml
  vars/centos-7.yml
  vars/debian-10.yml
  vars/debian-8.yml
  vars/debian-9.yml
  vars/default_vars.yml
  vars/fedora-18.yml
  vars/fedora-22.yml
  vars/raspbian-8.yml
  vars/raspbian-9.yml
  vars/ubuntu-16.yml
  vars/ubuntu-17.yml
  vars/ubuntu-18.yml
Labels: admin console, enhancement

#1388 DokuWiki 2018-04-22a -> 2018-04-22b
  roles/dokuwiki/defaults/main.yml
Labels: enhancement

#1396 1-prep: detect Ubermix (using grep) WITHOUT alarmist red errors
  roles/1-prep/tasks/main.yml
Labels: bug, enhancement

#1397 move fl.yml
  roles/0-init/tasks/first_run.yml
  roles/1-prep/tasks/main.yml
  roles/2-common/tasks/fl.yml
  roles/2-common/tasks/main.yml
Labels: enhancement

#1399 Clarify that fl.yml signifies "file layout"
  roles/2-common/tasks/fl.yml
  roles/2-common/tasks/main.yml
Labels: enhancement

#1402 Don't auto reinstall named, dhcpd when install is False
  roles/network/tasks/main.yml
Labels: bug, enhancement

#1404 Document @jvonau PR #1403, unifying install of Node.js & npm across playbooks
  roles/nodejs/tasks/main.yml
  roles/nodered/meta/main.yml
  roles/nodered/tasks/main.yml
  roles/sugarizer/meta/main.yml
  roles/sugarizer/tasks/main.yml
Labels: enhancement

#1403 Create nodejs as a shared role for sugarizer and nodered
  roles/nodejs/tasks/main.yml
  roles/nodered/meta/main.yml
  roles/nodered/tasks/main.yml
  roles/sugarizer/meta/main.yml
  roles/sugarizer/tasks/main.yml
Labels: enhancement

#1407 Move dnsmasq config file to /etc/dnsmasq.d/
  roles/network/tasks/enable_services.yml
Labels: enhancement

#1409 Recommend Ansible 2.7.5 -> 2.7.6
  iiab-install
  scripts/ansible
  scripts/ansible-2.6.x
  scripts/ansible-2.7.x
Labels: enhancement

#1412 Apache2 Reverse proxy subdirectory /kolibri
  roles/kolibri/defaults/main.yml
  roles/kolibri/tasks/main.yml
  roles/kolibri/templates/kolibri.conf.j2
  roles/kolibri/templates/kolibri.service.j2
Labels: enhancement

#1416 ejabberd flaky so don't install it by default, even in BIG-sized local_vars.yml
  vars/local_vars_big.yml
Labels: enhancement

#1424 Sugarizer 1.0.1 -> 1.1.0
  roles/sugarizer/defaults/main.yml
Labels: enhancement

#1426 phpMyAdmin 4.8.4 -> 4.8.5
  roles/phpmyadmin/defaults/main.yml
Labels: bug, enhancement

#1427 Lokole 0.1.26 -> 0.1.35
  roles/lokole/defaults/main.yml
Labels: enhancement

#1433 Kiwix 0.8.0-2 -> 0.9.0
  roles/kiwix/defaults/main.yml
Labels: enhancement

#1439 fix for usbmount 0.0.14 condition (Debian 10 logic accidentally broke Raspbian)
  roles/2-common/tasks/packages.yml
Labels: bug

#1440 Resolving issue #1050: fix Appliance Mode & expose Calibre-Web port 8083 consistently with others
  roles/network/tasks/computed_services.yml
  roles/network/templates/gateway/iiab-gen-iptables
Labels: bug, enhancement
