Repository iiab/iiab, pull requests merged in 2019-07, with the labels that each got.

#1803 Lokole 0.4.2 -> 0.4.3
  roles/lokole/defaults/main.yml
Labels: enhancement

#1804 Use --no-cache-dir during pip install of Lokole
  roles/lokole/tasks/install.yml
Labels: enhancement

#1806 Ansible output fixed for internetarchive & Minetest
  roles/internetarchive/tasks/main.yml
  roles/minetest/tasks/rpi_minetest_install.yml
Labels: enhancement, question

#1808 MediaWiki 1.32.2 -> 1.32.3
  roles/mediawiki/defaults/main.yml
Labels: enhancement

#1809 MediaWiki 1.32.3 -> 1.33.0
  roles/mediawiki/defaults/main.yml
Labels: enhancement

#1813 Fix for MySQL timing out on boot: put TimeoutStartSec=180 in mariadb.service
  roles/mysql/defaults/main.yml
  roles/mysql/tasks/main.yml
  vars/default_vars.yml
Labels: bug

#1817 AzuraCast doc tweaks
  roles/azuracast/tasks/install.yml
  roles/azuracast/tasks/main.yml
Labels: enhancement

#1819 Nextcloud 15 is required for older OS's that lack PHP 7.1 e.g. Ubuntu 16.04, Raspbian 9, Debian 9
  roles/nextcloud/defaults/main.yml
  roles/nextcloud/tasks/main.yml
Labels: bug

#1820 Check for PHP 7.1+ automatically, for Nextcloud 15/16
  roles/internetarchive/tasks/main.yml
  roles/nextcloud/defaults/main.yml
  roles/nextcloud/tasks/enable_or_disable.yml
  roles/nextcloud/tasks/install.yml
  roles/nextcloud/tasks/main.yml
  roles/nodejs/tasks/main.yml
  roles/sugarizer/tasks/main.yml
Labels: enhancement

#1823 Map Pack description + extra_description explanations for teachers [OSM]
  roles/osm-vector-maps/templates/iiab-update-map
Labels: enhancement

#1824 Better Map Pack descriptions, building on PR #1823
  roles/osm-vector-maps/templates/iiab-update-map
Labels: enhancement

#1825 1m & 1km details are often visible, don't sell us short! [OSM]
  roles/osm-vector-maps/templates/iiab-update-map
Labels: enhancement

#1828 WIP: Stop Kolibri during reinstalls, for #1782
  roles/kolibri/tasks/main.yml
Labels: bug, help wanted

#1829 Wan file
  roles/network/tasks/detected_network.yml
  roles/network/tasks/restart.yml
Labels: bug

#1834 Don't clobber http://box/maps redirect if it already exists :)
  roles/osm-vector-maps/tasks/main.yml
Labels: bug

#1835 Tighten up PR #1834 [OSM redirect for http://box/maps, on initial install only!]
  roles/osm-vector-maps/tasks/main.yml
Labels: enhancement

#1836 Enable http://box/map too, per #1496 + osm-vector-maps/README.md
  roles/osm-vector-maps/README.md
  roles/osm-vector-maps/templates/osm-vector-maps.conf
Labels: enhancement

#1837 osm-vector-maps playbook: reload Apache at end
  roles/osm-vector-maps/tasks/main.yml
Labels: bug

#1840 Add logic to install a given commit from the Lokole repository
  roles/lokole/tasks/install.yml
Labels: enhancement

#1841 Update Kolibri's README.rst for IIAB 7.0
  roles/kolibri/README.rst
Labels: enhancement

#1842 Ugly workaround so that IIAB installs on Debian 10 Buster (which suddenly removed monit)
  roles/monit/tasks/install.yml
  roles/monit/tasks/main.yml
Labels: bug

#1843 9-local-addons/tasks/main.yml playbooks in alphabetical order
  roles/9-local-addons/tasks/main.yml
Labels: enhancement

#1844 Lokole 0.4.3 -> 0.4.4 to work around #1830 "Settings" glitch
  roles/lokole/defaults/main.yml
Labels: bug

#1847 Make ansible happy [so box.lan resolves on Debian 10 Buster]
  roles/0-init/tasks/hostname.yml
  roles/network/tasks/hosts.yml
Labels: bug

#1850 Debian 10: bypass Sugarizer install for now, as MongoDB is unavailable
  roles/sugarizer/tasks/install.yml
  roles/sugarizer/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: bug

#1852 Fix #1850: Fully bypass Sugarizer (AND MongoDB) on Debian 10+
  roles/0-init/tasks/main.yml
  roles/mongodb/tasks/install.yml
  roles/mongodb/tasks/main.yml
  vars/default_vars.yml
Labels: bug

#1848 Warn implementers: kiwix_install: True is REQUIRED, if you install IIAB's Admin Console
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1816 Recommend Ansible 2.8.1 -> 2.8.2 and 2.7.11 -> 2.7.12
  scripts/ansible
  scripts/ansible-2.7.x
  scripts/ansible-2.8.x
Labels: enhancement

#1857 Moodle 3.5.x -> 3.7.x, for new OS's that contain PHP 7.3, for #1658
  roles/moodle/defaults/main.yml
Labels: bug, enhancement

#1859 Need to reload systemd daemon when adding apache config files
  roles/lokole/tasks/install.yml
Labels: bug

#1863 Calibre-Web 0.6.3 -> 0.6.4
  roles/calibre-web/defaults/main.yml
Labels: enhancement

#1864 Calibre-Web 0.6.4 -> V0.6.4
  roles/calibre-web/defaults/main.yml
Labels: bug

#1865 3 customizable Calibre-Web URL's: http://box/books, http://box/libros, http://box/livres
  roles/calibre-web/defaults/main.yml
  roles/calibre-web/tasks/main.yml
  roles/calibre-web/templates/calibre-web.conf.j2
  roles/calibre/defaults/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1853 Activate local-only mode [Lokole "offline" email]
  roles/lokole/README.rst
  roles/lokole/templates/webapp_secrets.sh.j2
Labels: bug, question

#1872 kiwix reports size in K
  roles/kiwix/templates/iiab-make-kiwix-lib.py
Labels: bug

#1876 Lokole README path/filename fix + tweaks/refinements
  roles/lokole/README.rst
Labels: enhancement

#1878 lots of stuff to fix kiwix lang codes used for kiwix_versions and menu defs
  roles/kiwix/templates/iiab-make-kiwix-lib.py
Labels: bug

#1880 Udev cleanup
  roles/2-common/tasks/udev.yml
Labels: enhancement

#1886 Don't supply patch_auto for debian-10
  roles/network/tasks/debian.yml
Labels: enhancement

#1887 Turn Captive portal off, as it was creating too many problems w/ Android 8/9
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
Labels: bug

#1888 Download Raspberry Pi resources and make available offline
  roles/httpd/templates/refresh-wiki-docs.sh
Labels: enhancement

#1891 Take 2: Add Lokole PDF (User's Guide) to http://box/info offline docs
  roles/httpd/templates/refresh-wiki-docs.sh
  roles/lokole/Lokole-IIAB_Users_Manual.pdf
  roles/lokole/README.rst
  roles/lokole/tasks/install.yml
Labels: enhancement

#1892 Inline docs for roles/httpd/templates/refresh-wiki-docs.sh
  roles/httpd/templates/refresh-wiki-docs.sh
Labels: enhancement

#1893 don't force templates, only create once in squid.yml
  roles/network/tasks/squid.yml
  roles/network/templates/squid/squid-iiab.conf.j2
Labels: bug

#1895 Clarify that IIAB offers 19 levels of zoom
  roles/osm-vector-maps/templates/iiab-update-map
Labels: enhancement

#1897 Elgg 2.3.13 -> 2.3.14
  roles/elgg/defaults/main.yml
Labels: enhancement

#1900 Recommend Ansible 2.8.3
  scripts/ansible
  scripts/ansible-2.8.x
Labels: enhancement

#1903 Revert #1886, test for Debian 9+
  roles/network/tasks/debian.yml
  roles/network/templates/network/debian-auto.j2
Labels: bug

#1906 use 'not' in place of '!='
  roles/network/tasks/computed_network.yml
  roles/network/tasks/hosts.yml
Labels: bug

#1908 Gitea 1.8.3 -> 1.9.0
  roles/gitea/defaults/main.yml
Labels: enhancement
