Repository iiab/iiab, pull requests merged in 2019-10, with the labels that each got.

#1976 7.1 release cycle for Q4 2019
  vars/default_vars.yml
Labels: enhancement

#1982 internetarchive - quicker/smaller install; update to also check install; concurrency 1
  roles/internetarchive/tasks/main.yml
Labels: enhancement

#1983 Warn implementers: DansGuardian is NO LONGER AVAILABLE in Debian Buster etc
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1988 Move Calibre & Calibre-Web installs to VERY END of iiab-install's 9 stages
  roles/9-local-addons/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: bug, enhancement

#1989 internetarchive: Branding in main.yml
  roles/internetarchive/tasks/main.yml
Labels: enhancement

#1978 Kolibri belt tightening / refactoring, thanks to Benjamin Bach
  roles/kolibri/tasks/main.yml
Labels: enhancement

#1991 MediaWiki 1.33.0 -> 1.33.1
  roles/mediawiki/defaults/main.yml
Labels: enhancement

#1990 Install common Apache modules in roles/httpd, for {http://box/kiwix, http://box/kolibri, http://box/nodered, etc}
  roles/activity-server/tasks/main.yml
  roles/awstats/tasks/install.yml
  roles/httpd/tasks/main.yml
  roles/kiwix/tasks/kiwix_install.yml
  roles/kolibri/tasks/main.yml
  roles/nodered/tasks/main.yml
Labels: enhancement

#1992 Gitea 1.9.3 -> 1.9.4
  roles/gitea/defaults/main.yml
Labels: bug, enhancement

#1995 Build on + revise @jvonau's PR #1994 ("Combine iiab-support & install-support")
  iiab-support
  install-support
  install-support.yml
  roles/openvpn/tasks/main.yml
  roles/openvpn/templates/iiab-handle.j2.deprecated
  roles/openvpn/templates/iiab-vpn.conf.in.deprecated
  roles/openvpn/templates/iiab-vpn.j2.deprecated
  roles/openvpn/templates/party-line.conf.j2.deprecated
  roles/openvpn/templates/xsce-vpn.conf.in.deprecated
  vars/debian-10.yml
  vars/default_vars.yml
  vars/raspbian-10.yml
  vars/ubuntu-19.yml
Labels: enhancement

#1994 Combine iiab-support & install-support
  iiab-support
  install-support
  install-support.yml
  roles/openvpn/tasks/main.yml
Labels: enhancement

#2000 Enhance /usr/bin/iiab-diagnostics so (1) it can be run by non-root users (2) it prompts users to auto-publish to a pastebin (3) output much improved + more readable!
  roles/0-init/tasks/first_run.yml
  roles/0-init/tasks/main.yml
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
Labels: enhancement

#2001 (1) clarify Kolibri installation / migration requirements (2) eliminate manual chown step (per @benjaoming)
  roles/kolibri/tasks/main.yml
Labels: enhancement

#2002 httpd: php_version: 7.2 -> 7.3; lokole: bcrypt -> python3-bcrypt; osm-vector-maps: python-geojson -> python3-geojson for Ubuntu 19.10 [Node.js should install via curl soon after release on 2019-10-17; cmdsrv requires python-systemd -> python3-systemd ?]
  roles/lokole/tasks/install.yml
  roles/osm-vector-maps/tasks/main.yml
  vars/ubuntu-19.yml
Labels: enhancement

#2004 calibre_via_debs: False [was True] + calibre_via_python: True [was False] in vars/debian-10.yml
  vars/debian-10.yml
Labels: enhancement

#2007 internetarchive: Update README
  roles/internetarchive/README.md
Labels: enhancement

#2012 Clarif that KA Lite's assessment.yml is (long ago) deprecated
  roles/kalite/tasks/assessment.yml.deprecated
Labels: enhancement

#2011 For now, keep python-geojson on OS's prior to Ubuntu 19.10 (can python3-geojson be made to work?) [OSM]
  roles/osm-vector-maps/tasks/main.yml
Labels: enhancement

#2014 KA Lite playbook cleaner / readability
  roles/kalite/README.rst
  roles/kalite/tasks/enable.yml
  roles/kalite/tasks/install.yml
  roles/kalite/tasks/main.yml
  roles/kalite/tasks/setup.yml
Labels: enhancement

#2006 Recommend Ansible 2.8.5 -> 2.9.0; update scripts/ansible-2.8.x & scripts/ansible-2.9.x
  iiab-install
  scripts/ansible
  scripts/ansible-2.8.x
  scripts/ansible-2.9.x
Labels: enhancement

#2023 Gitea 1.9.4 -> 1.9.5
  roles/gitea/defaults/main.yml
Labels: enhancement

#2024 Python3-2 [Ansible]
  ansible.cfg
  iiab-install
  iiab-network
  iiab-support
  roles/2-common/tasks/packages.yml
  roles/3-base-server/tasks/main.yml
  roles/4-server-options/tasks/main.yml
  roles/calibre-web/tasks/main.yml
  roles/kalite/tasks/install.yml
  roles/moodle/tasks/main.yml
  roles/mysql/tasks/main.yml
  roles/mysql/templates/my.cnf.j2
  roles/pbx/tasks/freepbx_dependencies.yml
  runrole
  scripts/ansible
  scripts/ansible-2.8.x
  scripts/ansible-2.9.x
Labels: enhancement

#2025 Fix PR #2024: Install package python-virtualenv for KA Lite and Calibre-Web
  iiab-install
  roles/2-common/tasks/packages.yml
Labels: bug
