Repository iiab/iiab, pull requests merged in 2019-02, with the labels that each got.

#1441 Make vars/<OS>.yml files less confusing (with dnsmasq, we can generally ignore "dns_service: named" & "dns_service: bind9")
  vars/centos-7.yml
  vars/debian-10.yml
  vars/debian-8.yml
  vars/debian-9.yml
  vars/fedora-18.yml
  vars/fedora-22.yml
  vars/raspbian-8.yml
  vars/raspbian-9.yml
  vars/ubuntu-16.yml
  vars/ubuntu-17.yml
  vars/ubuntu-18.yml
Labels: enhancement

#1430 sugarizer v1.1.0 + sugarizer-server dev branch on Node.js 10.x [FAILURE to reach MongoDB]
  roles/awstats/tasks/install.yml
  roles/awstats/tasks/main.yml
  roles/calibre/tasks/main.yml
  roles/cups/tasks/main.yml
  roles/kolibri/tasks/main.yml
  roles/lokole/tasks/main.yml
  roles/mediawiki/tasks/install.yml
  roles/mongodb/defaults/main.yml
  roles/mongodb/tasks/main.yml
  roles/mongodb/templates/mongod.conf.j2
  roles/monit/tasks/main.yml
  roles/moodle/tasks/main.yml
  roles/mosquitto/tasks/main.yml
  roles/nodejs/tasks/main.yml
  roles/nodered/tasks/main.yml
  roles/nodered/templates/node-red.service.j2
  roles/sshd/tasks/main.yml
  roles/sugarizer/defaults/main.yml
  roles/sugarizer/tasks/main.yml
  roles/sugarizer/templates/sugarizer.conf
  roles/sugarizer/templates/sugarizer.conf.j2
  roles/sugarizer/templates/sugarizer.ini.j2.deprecated
  roles/sugarizer/templates/sugarizer.js.deprecated
  roles/sugarizer/templates/sugarizer.service
  roles/transmission/tasks/main.yml
  roles/vnstat/tasks/main.yml
  roles/wordpress/tasks/install.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1447 Enforce Node.js precondition (that no other version is installed)
  roles/nodejs/tasks/main.yml
Labels: enhancement

#1455 Update netplan.j2
  roles/network/templates/network/netplan.j2
Labels: bug

#1458 default_vars.yml fell out of sync with local_vars_min.yml's iiab_usb_lib_show_all: True
  vars/default_vars.yml
Labels: enhancement

#1460 Recommend Ansible 2.7.7
  iiab-install
  scripts/ansible
  scripts/ansible-2.6.x
  scripts/ansible-2.7.x
Labels: enhancement

#1461 Minetest (Minecraft clone) for RPi, building on PR #1454
  roles/9-local-addons/tasks/main.yml
  roles/minetest/README.rst
  roles/minetest/defaults/main.yml
  roles/minetest/tasks/calc_vars.yml
  roles/minetest/tasks/main.yml
  roles/minetest/tasks/minetest_install.yml
  roles/minetest/tasks/minetest_install_mods.yml
  roles/minetest/tasks/rpi_minetest_install.yml
  roles/minetest/templates/minetest-serve.service.j2
  roles/minetest/templates/minetest.conf.j2
  roles/network/templates/gateway/iiab-gen-iptables
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1464 Ansible syntax/indentation norms for Minetest
  roles/minetest/tasks/main.yml
Labels: enhancement

#1463 New READMEs for roles/0-init & roles/network
  roles/0-init/README.rst
  roles/0-init/tasks/main.yml
  roles/network/README.rst
Labels: enhancement

#1405 Asterisk (with chan_dongle) and FreePBX
  roles/6-generic-apps/tasks/main.yml
  roles/network/tasks/hosts.yml
  roles/pbx/README.rst
  roles/pbx/defaults/main.yml
  roles/pbx/meta/main.yml
  roles/pbx/tasks/asterisk.yml
  roles/pbx/tasks/asterisk_dependencies.yml
  roles/pbx/tasks/chan_dongle.yml
  roles/pbx/tasks/freepbx.yml
  roles/pbx/tasks/freepbx_dependencies.yml
  roles/pbx/tasks/main.yml
  roles/pbx/templates/freepbx.conf.j2
  roles/pbx/templates/freepbx.service.j2
  roles/pbx/templates/odbc.ini.j2
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1471 Minetest
  roles/minetest/defaults/main.yml
  roles/minetest/tasks/main.yml
  roles/minetest/tasks/minetest_install.yml
  roles/minetest/tasks/minetest_install_mods.yml
  roles/minetest/tasks/rpi_minetest_install.yml
  roles/minetest/templates/minetest-serve.service.j2
Labels: enhancement

#1472 Minetest doc cleanup
  roles/minetest/README.rst
  vars/default_vars.yml
Labels: enhancement

#1475 Add /sugar RedirectMatch to /sugarizer — for http://box/sugar
  roles/sugarizer/templates/sugarizer.conf.j2
Labels: enhancement

#1476 Node-RED reverse proxy — for http://box/nodered
  roles/nodered/README.rst
  roles/nodered/defaults/main.yml
  roles/nodered/tasks/main.yml
  roles/nodered/templates/nodered.conf.j2
  roles/nodered/templates/settings.js.j2
  roles/sugarizer/tasks/main.yml
Labels: enhancement

#1479 Node-RED / nodered tweak: daemon-reload not nec when restarting Apache
  roles/nodered/tasks/main.yml
Labels: enhancement

#1473 Minetest README.rst, default_vars.yml, defaults/main.yml, local_vars_big.yml
  roles/minetest/README.rst
  roles/minetest/defaults/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
Labels: enhancement

#1487 Minetest doc tweaks
  roles/minetest/README.rst
Labels: enhancement

#1488 Minetest typo blocked RPi (service renamed minetest-serve -> minetest-server)
  roles/minetest/tasks/rpi_minetest_install.yml
Labels: bug

#1478 PBX fixes [open Asterisk ports on WAN using iptables, problem reinstalling FreePBX?]
  roles/network/templates/gateway/iiab-gen-iptables
  roles/pbx/defaults/main.yml
  roles/pbx/tasks/asterisk.yml
  roles/pbx/tasks/freepbx.yml
  roles/pbx/tasks/freepbx_enable.yml
  roles/pbx/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
Labels: bug, enhancement

#1491 Docs: pbx/README.rst, tasks/asterisk.yml, tasks/freepbx.yml, minetest/README.rst
  roles/minetest/README.rst
  roles/pbx/README.rst
  roles/pbx/tasks/asterisk.yml
  roles/pbx/tasks/freepbx.yml
Labels: enhancement

#1492 Minetest doc typo
  roles/minetest/README.rst
Labels: bug

#1494 Clarify that Asterisk/FreePBX (appear to!) work on Raspbian/RPi -- in defaults_vars.yml & 3 local_vars files
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1477 Update sugarizer-server (dev branch) for new docs & small improvements
  roles/sugarizer/defaults/main.yml
Labels: enhancement

#1497 Conditionally force correct version of Node.js &/or Node-RED e.g. on graphical desktop OS's like Raspbian Desktop & Ubermix
  roles/nodejs/tasks/main.yml
  roles/nodered/defaults/main.yml
  roles/nodered/tasks/main.yml
  roles/nodered/templates/nodered.service.j2
Labels: bug, enhancement

#1507 Document FreePBX restart issue on RPi & remove 'pbx' from BIG-sized for now (& Node-RED doc tweak)
  roles/nodered/README.rst
  roles/nodered/defaults/main.yml
  roles/pbx/README.rst
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: bug, enhancement

#1514 Lokole 0.1.36 -> 0.1.38
  roles/lokole/defaults/main.yml
Labels: enhancement

#1515 Recommend Ansible 2.7.8
  iiab-install
  scripts/ansible
  scripts/ansible-2.6.x
  scripts/ansible-2.7.x
Labels: enhancement

#1518 Captive Portal: works on Windows 7,8,10, with no network wire
  roles/captive-portal/templates/capture-wsgi.py
Labels: enhancement

#1523 Possible fix for dnsmasq during WiFi installs for #1519
  roles/network/tasks/restart.yml
Labels: bug, enhancement

#1524 iiab_base_ver: 6.7 to 7.0 in roles/0-init/defaults/main.yml
  roles/0-init/defaults/main.yml
Labels: enhancement

#1453 Change iiab.j2 to rpi.j2 to fix iiab-network dup route failings?
  roles/network/tasks/rpi_debian.yml
  roles/network/templates/network/iiab.j2.deprecated
Labels: bug, wontfix

#1525 WiFi dnsmasq fix for #1519 - always create br0 on RPi
  roles/network/tasks/detected_network.yml
  roles/network/tasks/restart.yml
  roles/network/tasks/rpi_debian.yml
Labels: bug, enhancement

#1526 iiab-hotspot-on & iiab-hotspot-off should keep dnsmasq running
  roles/network/templates/network/iiab-hotspot-off
  roles/network/templates/network/iiab-hotspot-on
Labels: bug, enhancement
