Repository iiab/iiab, pull requests merged in 2019-09, with the labels that each got.

#1936 Kolibri systemd unit file...solves its failure-to-start on RPi 3 B+ especially? #1932
  roles/kolibri/templates/kolibri.service.j2
Labels: enhancement

#1940 Ethernet DHCP IP (for field updates) then fallback to Static IP (for offline schools)
  roles/network/defaults/main.yml
  roles/network/templates/network/dhcpcd.conf.j2
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1941 Nextcloud Liberation Front: Unblock Nextcloud in 192.168.1.* schools & all others!
  roles/nextcloud/README.md
  roles/nextcloud/templates/nextcloud.conf.j2
Labels: bug

#1942 New variable "nextcloud_allow_public_ips: False" in local_vars.yml
  roles/httpd/defaults/main.yml
  roles/httpd/tasks/main.yml
  roles/moodle/defaults/main.yml
  roles/nextcloud/README.md
  roles/nextcloud/defaults/main.yml
  roles/nextcloud/tasks/enable_or_disable.yml
  roles/nextcloud/templates/nextcloud.conf.j2
  roles/wordpress/defaults/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1944 Prune Elgg from MEDIUM-sized IIAB installs
  vars/local_vars_medium.yml
Labels: enhancement

#1945 php-imagick for Nextcloud on Debian/Raspbian
  roles/nextcloud/tasks/install.yml
Labels: enhancement

#1946 kiwix-tools 3.0.1 -> 3.0.1-2 towards fixing Fulltext Search (we hope!)
  roles/kiwix/defaults/main.yml
Labels: bug

#1947 Edits to Nextcloud documentation
  roles/nextcloud/README.md
Labels: enhancement

#1948 Gitea 1.9.2 -> 1.9.3
  roles/gitea/defaults/main.yml
Labels: enhancement

#1954 kiwix-tools 3.0.1-2 -> 3.0.1-4
  roles/kiwix/defaults/main.yml
Labels: enhancement

#1955 kiwix-tools 3.0.1-4 -> 3.0.1-5
  roles/kiwix/defaults/main.yml
Labels: enhancement

#1956 phpMyAdmin 4.9.0.1 -> 4.9.1
  roles/phpmyadmin/defaults/main.yml
Labels: enhancement

#1961 Expose Bluetooth vars in local_vars.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1957 Nextcloud 16 -> 17 on "2019-09-26"
  roles/nextcloud/defaults/main.yml
Labels: enhancement

#1962 Remove bitrot from local_vars.yml & Clarify lesser-used vars in default_vars.yml (active & ongoing deprecation = critical for readability!)
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: bug, enhancement

#1963 kiwix-tools 3.0.1-5 -> 3.0.1-6
  roles/kiwix/defaults/main.yml
Labels: enhancement

#1966 Sugarizer v1.1.0 -> v1.2.0
  roles/sugarizer/defaults/main.yml
Labels: enhancement

#1967 Check internet_available before running iiab-refresh-wiki-docs (in stage 4)
  roles/4-server-options/tasks/main.yml
Labels: enhancement

#1969 OSM Vector Map Packs - Fix Instructions
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: bug

#1970 Enable http://box/kolibri without trailing slash too
  roles/kiwix/defaults/main.yml
  roles/kiwix/templates/kiwix.conf.j2
  roles/kolibri/defaults/main.yml
  roles/kolibri/templates/kolibri.conf.j2
Labels: enhancement

#1972 Fix kolibri.conf.j2 in PR #1970
  roles/kolibri/templates/kolibri.conf.j2
Labels: bug

#1968 Install Kolibri w/ apt (.deb file) instead of pip (.pex file)
  roles/kiwix/tasks/kiwix_install.yml
  roles/kiwix/templates/iiab-make-apache-config.py
  roles/kolibri/defaults/main.yml
  roles/kolibri/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement, question

#1973 MediaWiki password strengthening clarification
  roles/mediawiki/defaults/main.yml
Labels: enhancement

#1974 Update IIAB's primary README.md
  README.md
Labels: enhancement
