Repository iiab/iiab, pull requests merged in 2019-06, with the labels that each got.

#1713 Gitea 1.7.6 -> 1.8.2 once again works on Raspberry Pi?!
  roles/gitea/defaults/main.yml
Labels: enhancement

#1722 phpMyAdmin 4.8.5 -> 4.9.0.1
  roles/phpmyadmin/defaults/main.yml
Labels: enhancement

#1727 Recommend Ansible 2.8.1
  scripts/ansible
  scripts/ansible-2.8.x
Labels: enhancement

#1730 Elgg 2.3.12 -> 2.3.13 (pending d.iiab.io/packages)
  roles/elgg/defaults/main.yml
Labels: enhancement

#1735 Revert to Kolibri 0.12.3, due to Kolibri 0.12.4 bug
  roles/kolibri/defaults/main.yml
  roles/kolibri/tasks/main.yml
Labels: bug

#1732 Ncat
  roles/openvpn/tasks/main.yml
  vars/debian-10.yml
  vars/default_vars.yml
  vars/raspbian-10.yml
  vars/ubuntu-19.yml
Labels: enhancement

#1724 Map redirect [for http://box/maps to show the latest, OSM]
  roles/osm-vector-maps/templates/iiab-update-map
Labels: enhancement

#1716 Bluetooth PAN and Terminal servers
  roles/4-server-options/tasks/main.yml
  roles/bluetooth/README.rst
  roles/bluetooth/defaults/main.yml
  roles/bluetooth/tasks/main.yml
  roles/bluetooth/tasks/rpi_install.yml
  roles/bluetooth/templates/bt-agent.service.j2
  roles/bluetooth/templates/bt-pan.service.j2
  roles/bluetooth/templates/bt-term.service.j2
  roles/bluetooth/templates/iiab-bt-pan-discoverable-on.j2
  roles/bluetooth/templates/iiab-bt-pan-off.j2
  roles/bluetooth/templates/iiab-bt-pan-on.j2
  roles/bluetooth/templates/iiab-bt-term-off.j2
  roles/bluetooth/templates/iiab-bt-term-on.j2
  roles/bluetooth/templates/network.conf.j2
  roles/network/templates/network/iiab-hotspot-off
  roles/network/templates/network/iiab-hotspot-on
  vars/default_vars.yml
Labels: enhancement

#1740 Gitea 1.8.2 -> 1.8.3 "7 upstream bug fixes"
  roles/gitea/defaults/main.yml
Labels: enhancement

#1742 MediaWiki 1.32.1 -> MediaWiki 1.32.2
  roles/mediawiki/defaults/main.yml
Labels: enhancement

#1745 Update computed_services.yml [dnsmasq should/generally run, by default]
  roles/network/tasks/computed_services.yml
  roles/network/templates/network/dhcpcd.conf.j2
Labels: bug, enhancement

#1750 network role should restart dnsmasq in appliance mode too!
  roles/network/tasks/restart.yml
Labels: bug

#1760 Fix bug in KA Lite parsing of regex for ifconfig output
  roles/kalite/tasks/install.yml
Labels: bug

#1761 FreePBX fixes and changes
  roles/network/tasks/hosts.yml
  roles/network/templates/gateway/iiab-gen-iptables
  roles/pbx/README.rst
  roles/pbx/defaults/main.yml
  roles/pbx/tasks/freepbx.yml
  roles/pbx/templates/71-freepbx-framework.patch
  roles/pbx/templates/freepbx.conf.j2
  vars/default_vars.yml
Labels: bug

#1764 freepbx_http_port should be pbx_http_port
  roles/pbx/tasks/freepbx.yml
  roles/pbx/templates/freepbx.conf.j2
Labels: bug

#1765 Dnsmasq fixes
  roles/network/tasks/computed_network.yml
  roles/network/tasks/detected_network.yml
  roles/network/tasks/enable_services.yml
  roles/network/templates/network/dnsmasq.sh.j2
Labels: enhancement

#1763 WIP: iiab-diagnostics friendly community tooling, to build relationships between dev teams, implementers & educators
  roles/0-init/tasks/main.yml
  roles/1-prep/templates/iiab-network-reset
  roles/all-vars/tasks/main.yml
  run-one-role.yml
  runrole
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
Labels: enhancement, pizza

#1733 Initial checkin of AzuraCast role [for online radio stations]
  roles/6-generic-apps/tasks/main.yml
  roles/azuracast/README.rst
  roles/azuracast/defaults/main.yml
  roles/azuracast/tasks/install.yml
  roles/azuracast/tasks/main.yml
  roles/azuracast/templates/docker-compose.override.yml.j2
  roles/azuracast/templates/env.j2
  roles/kalite/tasks/install.yml
  roles/network/templates/gateway/iiab-gen-iptables
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1768 Do not copy dnsmasq restart script if we are on RPi
  roles/network/tasks/enable_services.yml
Labels: bug

#1769 Ansible deprecations
  scripts/ansible-2.2.0-deprecated
  scripts/ansible-2.4.x-deprecated
  scripts/ansible-2.5.x-deprecated
  scripts/ansible-2.6.x-deprecated
Labels: enhancement

#1773 Fix #1747 | dnsmasq and systemd-resolved race issues
  roles/network/templates/network/systemd-br0-network.j2
Labels: bug

#1752 Add client config that works when DNS does not [OpenVPN]
  roles/openvpn/templates/xscenet.conf.j2
  vars/default_vars.yml
Labels: enhancement

#1776 osm-vector-maps cleanup of unused clutter
  roles/osm-vector-maps/files/en-map_test.json
Labels: enhancement

#1780 Mitra
  roles/internetarchive/README.md
  roles/internetarchive/templates/internetarchive.service.j2
Labels: enhancement

#1779 Fixing ./iiab-network on Ubuntu 16.04 (and other OS's possibly?)
  roles/network/tasks/enable_services.yml
  roles/network/templates/network/dnsmasq.sh.j2
Labels: bug, help wanted, question

#1781 Doc tweaks for 7.0
  roles/4-server-options/tasks/main.yml
  roles/bluetooth/defaults/main.yml
  roles/osm-vector-maps/tasks/main.yml
Labels: enhancement

#1777 sugarizer-server-1.1.0 -> sugarizer-server-1.1.1
  roles/sugarizer/defaults/main.yml
Labels: bug
