Repository iiab/iiab, pull requests merged in 2019-03, with the labels that each got.

#1547 Kolibri 0.12.0 is now released for pip etc. Update its README with latest issues
  roles/kolibri/README.rst
Labels: enhancement

#1551 Fix iiab-admin published password warnings for Raspbian Desktop 2018-11-13 especially
  roles/iiab-admin/defaults/main.yml
  roles/iiab-admin/tasks/main.yml
  roles/iiab-admin/templates/sshpwd-lxde-iiab.sh
  roles/iiab-admin/templates/sshpwd-profile-iiab.sh
  vars/default_vars.yml
Labels: bug

#1553 @aidan-fitz's Gitea [lightweight self-hosted Git service] with bits of documentation polish
  roles/6-generic-apps/tasks/main.yml
  roles/gitea/README.rst
  roles/gitea/defaults/main.yml
  roles/gitea/tasks/install.yml
  roles/gitea/tasks/main.yml
  roles/gitea/templates/app.ini.j2
  roles/gitea/templates/gitea.conf.j2
  roles/gitea/templates/gitea.service.j2
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1565 make sure ImageMagick is installed and configured for PDFs
  roles/calibre-web/tasks/main.yml
Labels: bug

#1566 Revert "make sure ImageMagick is installed and configured for PDFs"
  roles/calibre-web/tasks/main.yml
Labels: bug

#1567 make idempotent [install ImageMagick for Calibre-Web thumbnail previews of PDFs]
  roles/calibre-web/tasks/main.yml
Labels: enhancement

#1571 Recommend Ansible 2.7.9
  iiab-install
  scripts/ansible
  scripts/ansible-2.6.x
  scripts/ansible-2.7.x
Labels: enhancement

#1554 Gitea: configure clone URLs
  roles/gitea/defaults/main.yml
  roles/gitea/tasks/install.yml
  roles/gitea/templates/app.ini.j2
Labels: enhancement, question

#1578 kiwix-tools 0.9.0 -> 1.1.0
  roles/kiwix/defaults/main.yml
Labels: enhancement

#1584 Gitea 1.7.4 -> 1.7.5
  roles/gitea/defaults/main.yml
Labels: enhancement

#1585 Tweaks to get BIG-sized IIAB (almost!) working on Ubuntu 19.04 Beta
  roles/nodejs/tasks/main.yml
  vars/ubuntu-19.yml
Labels: enhancement
