Repository iiab/iiab, pull requests merged in 2019-04, with the labels that each got.

#1573 Expand Gitea documentation
  roles/gitea/README.rst
  roles/gitea/templates/gitea.service.j2
Labels: enhancement

#1589 Recommend Ansible 2.7.10
  iiab-install
  scripts/ansible
  scripts/ansible-2.6.x
  scripts/ansible-2.7.x
Labels: enhancement

#1592 Elgg 2.3.10 -> 2.3.11 LTS (defer 3.0.1 for now??)
  roles/elgg/defaults/main.yml
Labels: enhancement

#1594 debian 10 needs auto just like 9
  roles/network/tasks/debian.yml
Labels: bug

#1598 kiwix-tools 1.1.0 -> 1.2.0
  roles/kiwix/defaults/main.yml
Labels: enhancement

#1602 Explain osm_vector vars in {MIN, MEDIUM, BIG} local_vars.yml
  roles/osm-vector/defaults/main.yml
  roles/osm-vector/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1607 Elgg 2.3.11 -> 2.3.12
  roles/elgg/defaults/main.yml
Labels: enhancement

#1609 Gitea 1.7.5 -> 1.8.0
  roles/gitea/defaults/main.yml
Labels: enhancement

#1613 Nextcloud 15 -> 16
  roles/nextcloud/defaults/main.yml
Labels: enhancement

#1614 nextcloud-16.0.0.tar.bz2 needed for now: latest-16.tar.bz2 ain't ready :(
  roles/nextcloud/defaults/main.yml
Labels: bug, enhancement

#1616 Revert to Nextcloud 16 to 15 (i.e. 15.0.7 for now)
  roles/nextcloud/defaults/main.yml
Labels: enhancement

#1620 fix: nextcloud-16.0.0.tar.bz2 -> latest-15.tar.bz2
  roles/nextcloud/defaults/main.yml
Labels: bug

#1621 Cleaner Admin Console "Continent Picker" to download & install OSM vector maps
  roles/osm-vector/files/osm_functions.js
Labels: enhancement
