Repository iiab/iiab, pull requests merged in 2019-08, with the labels that each got.

#1909 kiwix-tools 2.0.0 -> 2.1.0
  roles/kiwix/defaults/main.yml
Labels: enhancement

#1913 TimeoutStartSec=180 in kiwix-serve.service, for #1905
  roles/kiwix/templates/kiwix-serve.service.j2
Labels: bug, question

#1914 kiwix-serve systemd cleanup, for PR #1913
  roles/kiwix/tasks/kiwix_install.yml
Labels: bug, enhancement

#1917 calibreweb_version: V0.6.4 -> 0.6.4 as it was re-released 5h ago
  roles/calibre-web/defaults/main.yml
Labels: bug

#1918 ignore docker interfaces for LAN device count
  roles/network/tasks/detected_network.yml
Labels: bug

#1920 Node speed
  roles/nodejs/tasks/main.yml
Labels: enhancement, question

#1921 Skip yarn add if installed, but allow yarn upgrade if set in local_vars.yml
  iiab-install
  roles/0-init/tasks/first_run.yml
  roles/0-init/tasks/main.yml
  roles/internetarchive/defaults/main.yml
  roles/internetarchive/tasks/main.yml
  roles/yarn/tasks/main.yml
  runrole
Labels: enhancement

#1924 'internetarchive' role requires sudo, to fix PR #1921
  roles/internetarchive/tasks/main.yml
Labels: bug

#1923 Introduce variable pi_swap_file_size: 1024
  roles/1-prep/tasks/raspberry_pi.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1926 Partial revert of PR #1921, attempting to get 'internetarchive' to install on 1st pass
  roles/internetarchive/tasks/main.yml
Labels: bug

#1927 Another Desperate Attempt to fix PR #1921...this time with yarn?
  roles/internetarchive/tasks/main.yml
  roles/yarn/tasks/main.yml
Labels: bug

#1928 Gitea 1.9.0 -> 1.9.1
  roles/gitea/defaults/main.yml
Labels: enhancement

#1929 Hostapd enabled
  roles/network/tasks/hostapd.yml
Labels: bug, enhancement

#1930 Recommend Ansible 2.8.4 (& 2.7.13 if nec)
  scripts/ansible
  scripts/ansible-2.7.x
  scripts/ansible-2.8.x
Labels: enhancement

#1935 kiwix-tools 2.1.0 -> 3.0.1
  roles/kiwix/defaults/main.yml
Labels: enhancement
