Repository iiab/iiab, pull requests merged in 2019-05, with the labels that each got.

#1628 Disable Calibre-Web in MEDIUM-sized & BIG-sized IIAB installs, until #1624 is fixed
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
Labels: bug, help wanted

#1633 Run netplan.yml on Ubuntu 18.04 and higher
  roles/network/tasks/main.yml
Labels: bug, enhancement

#1634 Revise template for /etc/netplan to mitigate 2+ min stall during Ubuntu 19.04 boot
  roles/network/templates/network/netplan.j2
Labels: bug, enhancement

#1636 Increase hostapd_wait from 1 to 5 seconds (?) for dnsmasq
  roles/network/defaults/main.yml
Labels: bug, question

#1637 apt-key fails within scripts/ansible when br0 present, so: keyserver.ubuntu.com -> hkp://keyserver.ubuntu.com:80
  scripts/ansible
  scripts/ansible-2.6.x
  scripts/ansible-2.7.x
Labels: bug

#1640 Cleanup of roles/openvpn/defaults/main.yml
  roles/openvpn/defaults/main.yml
Labels: enhancement

#1639 Unmenu for OSM vector maps
  roles/4-server-options/tasks/main.yml
  roles/osm-vector-maps/defaults/main.yml
  roles/osm-vector-maps/files/countries.json
  roles/osm-vector-maps/files/en-map_test.json
  roles/osm-vector-maps/files/map_functions.js
  roles/osm-vector-maps/files/test-index.redirect
  roles/osm-vector-maps/tasks/main.yml
  roles/osm-vector-maps/templates/iiab-update-map
  roles/osm-vector-maps/templates/index.html
  roles/osm-vector-maps/templates/main.js
  roles/osm-vector-maps/templates/osm-vector-maps.conf
  roles/osm-vector/defaults/main.yml
  roles/osm-vector/files/test-index.redirect
  roles/osm-vector/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1641 osm-vector-maps vars consolidated in 1 place
  roles/osm-vector-maps/defaults/main.yml
  vars/default_vars.yml
Labels: enhancement

#1645 ./install-support prompts for openvpn_handle & confirms resulting 10.8.0.* IP address
  iiab-support.yml
  install-support
  roles/openvpn/templates/iiab-handle.j2
Labels: enhancement

#1654 ./install-support -> /usr/bin/iiab-support UX (1) validates openvpn_handle (2) displays 10.8.0.x + usage TIPS + alternatives like ngrok/TeamViewer
  install-support
  install-support.yml
  roles/1-prep/tasks/main.yml
  roles/openvpn/tasks/main.yml
  roles/openvpn/templates/iiab-handle.j2
  roles/openvpn/templates/iiab-remote-on.j2
  roles/openvpn/templates/iiab-support
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1657 Sugarizer Server 1.1.0 in /opt/iiab/sugarizer-server-1.1.0
  roles/sugarizer/defaults/main.yml
  roles/sugarizer/tasks/main.yml
Labels: enhancement

#1660 Take Two: Create scripts/ansible-2.8.x; Deprecate scripts/ansible-2.6.x
  scripts/ansible-2.6.x-deprecated
  scripts/ansible-2.8.x
Labels: enhancement

#1661 Fix PPA URL's from ansible-2.7 -> ansible-2.8
  scripts/ansible-2.8.x
Labels: bug

#1666 Lokole 0.1.39 -> 0.4.0 (for rural/offline email e.g. with intermittent access)
  roles/lokole/defaults/main.yml
Labels: bug, enhancement

#1667 Nextcloud 15.0.x on Debian 9 & Raspbian 9 (PHP 7.1+ is missing) -- but Nextcloud 16.0.y on all others distros
  roles/nextcloud/defaults/main.yml
  roles/nextcloud/tasks/main.yml
Labels: enhancement

#1668 Revert "Disable Calibre-Web in MEDIUM-sized & BIG-sized IIAB installs, until #1624 is fixed"
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
Labels: bug

#1669 Recommend Ansible 2.8.0
  scripts/ansible
Labels: enhancement

#1670 /usr/bin/iiab-support (better) explains OpenVPN
  roles/openvpn/templates/iiab-support
Labels: enhancement

#1671 /usr/bin/iiab-support code readability tweaks
  roles/openvpn/templates/iiab-support
Labels: enhancement

#1672 Gitea 1.8.0 -> 1.8.1
  roles/gitea/defaults/main.yml
Labels: enhancement

#1674 Revert Gitea 1.8.1 to 1.7.6 for RPi, until Aidan clarifies next step
  roles/gitea/defaults/main.yml
Labels: bug

#1665 Open Samba ports if enabled
  roles/network/templates/gateway/iiab-gen-iptables
  vars/default_vars.yml
Labels: enhancement, good 1st issue

#1676 /opt/iiab/iiab/vars/default_vars.yml readability
  vars/default_vars.yml
Labels: enhancement

#1679 Move osm-vector-maps install from 4-server-options to 7-edu-apps stage
  roles/4-server-options/tasks/main.yml
  roles/7-edu-apps/tasks/main.yml
Labels: enhancement

#1681 kiwix-tools 1.2.0 -> 1.2.1
  roles/kiwix/defaults/main.yml
Labels: enhancement

#1683 Register map
  roles/osm-vector-maps/templates/iiab-update-map
Labels: enhancement

#1684 Lokole 0.4.0 -> 0.4.1
  roles/lokole/defaults/main.yml
Labels: enhancement

#1688 Lokole 0.4.1 -> 0.4.2
  roles/lokole/defaults/main.yml
Labels: enhancement

#1677 Making IIAB's firewall (iptables) understandable to newbie implementers
  roles/network/tasks/avahi.yml
  roles/network/templates/gateway/iiab-gen-iptables
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1690 Recommend 2.7.11 if running scripts/ansible-2.7.x
  scripts/ansible-2.7.x
Labels: enhancement

#1691 Fix Typo: enable masquerade only when "$lan" != "none" (typo fixed)
  roles/network/templates/gateway/iiab-gen-iptables
Labels: bug

#1692 iptables firewall: further clarify http-or-https (for Admin Console's box.lan/admin too)
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: bug, enhancement

#1693 iptables firewall: Apply @jvonau's "$lan" != "none" to forwarding not just masquerading
  roles/network/templates/gateway/iiab-gen-iptables
Labels: enhancement

#1694 Clean roles/0-init & roles/network for Ansible 2.8 ('| bool'). Prep for Ubuntu 18/19+
  roles/0-init/defaults/main.yml
  roles/0-init/tasks/hostname.yml
  roles/0-init/tasks/main.yml
  roles/network/tasks/avahi.yml
  roles/network/tasks/computed_network.yml
  roles/network/tasks/dansguardian.yml
  roles/network/tasks/debian.yml
  roles/network/tasks/detected_network.yml
  roles/network/tasks/dhcpd.yml
  roles/network/tasks/down-debian.yml
  roles/network/tasks/hostapd.yml
  roles/network/tasks/ifcfg_mods.yml
  roles/network/tasks/main.yml
  roles/network/tasks/named.yml
  roles/network/tasks/netplan.yml
  roles/network/tasks/redetect.yml
  roles/network/tasks/restart.yml
  roles/network/tasks/squid.yml
  roles/network/tasks/sysd-netd-debian.yml
Labels: enhancement

#1695 Making IIAB (PRE-)release version number a bit more visible
  roles/0-init/defaults/main.yml
  vars/default_vars.yml
Labels: enhancement

#1698 Making network vars more findable via roles/network/defaults/main.yml
  roles/network/defaults/main.yml
  roles/network/templates/gateway/iiab-gen-iptables
Labels: enhancement

#1617 Mitra - 'internetarchive' & 'yarn' Ansible playbooks for IIAB
  roles/9-local-addons/tasks/main.yml
  roles/internetarchive/README.md
  roles/internetarchive/defaults/main.yml
  roles/internetarchive/meta/main.yml
  roles/internetarchive/tasks/main.yml
  roles/internetarchive/templates/internetarchive.conf
  roles/internetarchive/templates/internetarchive.service.j2
  roles/network/templates/gateway/iiab-gen-iptables
  roles/yarn/README.rst
  roles/yarn/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#1700 Install pkg pastebinit on all IIAB's
  roles/2-common/tasks/packages.yml
Labels: enhancement

#1706 kiwix-tools 1.2.1 -> 2.0.0
  roles/kiwix/defaults/main.yml
Labels: enhancement

#1701 hostapd fails to start if wifi connected to wan
  roles/network/templates/network/iiab-hotspot-on
Labels: bug

#1709 IIAB should use Calibre-Web 0.6.3 instead of master branch
  roles/calibre-web/defaults/main.yml
  roles/calibre-web/tasks/main.yml
Labels: enhancement

#1697 Not just is_ubuntu_18: make U19/U20 viable [Debian 10 already OK?] [extends use of php{{ php_version }}-sqlite3 to future OS's for now...somewhat controversially]
  roles/calibre/tasks/debs.yml
  roles/httpd/tasks/main.yml
Labels: enhancement
