Repository iiab/iiab, pull requests merged in 2020-03, with the labels that each got.

#2272 kiwix-tools 3.0.2 -> 3.0.3
  roles/kiwix/defaults/main.yml
Labels: enhancement

#2279 (1) recommend Ansible 2.9.6+ (2) mandate Ansible 2.8.10+ (3) mandate kernel 4.19.97+ on Raspbian
  iiab-install
  scripts/ansible
  scripts/ansible-2.8.x
  scripts/ansible-2.9.x
Labels: enhancement

#2278 remove quotes
  roles/network/tasks/computed_network.yml
Labels: bug

#2281 Gitea 1.11.2
  roles/gitea/defaults/main.yml
Labels: enhancement

#2263 Update RPi minetest to 5.1.1 for compatibility with latest raspbian
  roles/minetest/tasks/rpi_minetest_install.yml
  vars/raspbian-10.yml
Labels: enhancement

#2282 Usbmount fixes
  roles/usb_lib/templates/usbmount.rules.j2
  roles/usb_lib/templates/usbmount@.service.j2
Labels: enhancement

#2275 Kill off is_rpi
  iiab-configure
  roles/0-DEPRECATED-ROLES/nodogsplash/tasks/main.yml
  roles/0-init/defaults/main.yml
  roles/0-init/tasks/iiab_ini.yml
  roles/0-init/tasks/main.yml
  roles/1-prep/tasks/raspberry_pi.yml
  roles/2-common/tasks/packages.yml
  roles/4-server-options/tasks/main.yml
  roles/calibre/tasks/debs.yml
  roles/calibre/tasks/install.yml
  roles/iiab-admin/tasks/main.yml
  roles/kalite/tasks/install-old.yml.unused
  roles/kalite/tasks/install.yml
  roles/minetest/tasks/calc_vars.yml
  roles/minetest/tasks/provision.yml
  roles/mongodb/tasks/install.yml
  roles/network/tasks/computed_network.yml
  roles/network/tasks/debian.yml
  roles/network/tasks/detected_network.yml
  roles/network/tasks/enable_services.yml
  roles/network/tasks/hostapd.yml
  roles/network/tasks/main.yml
  roles/network/templates/network/dhcpcd.conf.j2
  roles/nodered/tasks/install.yml
  roles/nodered/tasks/rpi_desk.yml
  roles/nodered/templates/nodered.service.j2
  roles/www_back_end/tasks/php-stem.yml
  scripts/local_facts.fact
  vars/default_vars.yml
  vars/raspbian-10.yml
  vars/raspbian-8.yml
  vars/raspbian-9.yml
Labels: enhancement

#2240 Cal py3 [Calibre-Web: move to Python 3] ...uncovers 2 Calibre-Web issues: slow shutdown & "Perform Update" button risks
  roles/calibre-web/defaults/main.yml
  roles/calibre-web/tasks/install.yml
  roles/calibre-web/templates/calibre-web.service.j2
Labels: enhancement, question

#2283 is_rpi to rpi_model in /etc/iiab/iiab.ini
  roles/0-init/tasks/iiab_ini.yml
  roles/0-init/tasks/main.yml
Labels: enhancement

#2289 Rtc
  roles/0-init/defaults/main.yml
  roles/1-prep/tasks/main.yml
  roles/1-prep/tasks/raspberry_pi.yml
Labels: enhancement

#2291 ubuntu 20 ansible workaround
  scripts/ansible
  scripts/local_facts.fact
Labels: enhancement

#2294 U20test / Ubuntu 20.04 to offer PHP 7.3 and 7.4 [Nextcloud PHP deps, php-stem on U20, ap0 prep, KA Lite on Ubermix, etc]
  roles/0-init/tasks/main.yml
  roles/1-prep/tasks/main.yml
  roles/kalite/tasks/install.yml
  roles/kiwix/tasks/install.yml
  roles/network/tasks/computed_network.yml
  roles/network/tasks/detected_network.yml
  roles/nextcloud/tasks/install.yml
  roles/www_base/tasks/php-stem.yml
Labels: enhancement

#2299 phpMyAdmin 5.0.1 -> 5.0.2 security fixes
  roles/phpmyadmin/defaults/main.yml
Labels: enhancement

#2301 Aarch64
  roles/1-prep/tasks/raspberry_pi.yml
  roles/gitea/defaults/main.yml
  roles/lokole/tasks/install.yml
Labels: enhancement

#2302 Move 'rtc_id: ds3231' from vars/*.yml to vars/local_vars_*.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
  vars/raspbian-10.yml
  vars/raspbian-8.yml
  vars/raspbian-9.yml
Labels: enhancement

#2303 MediaWiki 1.34.0 -> 1.34.1
  roles/mediawiki/defaults/main.yml
Labels: enhancement

#2307 Install python2 for KA Lite, if Raspbian/Debian > 10 or Ubuntu > 19
  roles/kalite/tasks/install.yml
Labels: bug

#2308 Sugarizer 1.2.0 -> 1.3.0 (Sugarizer Server remains at 1.2.0)
  roles/sugarizer/defaults/main.yml
Labels: enhancement

#2309 NGINX: fancyindex instead of autoindex, for http://box/usb (for larger font on smartphones etc)
  roles/nginx/templates/iiab.conf.j2
Labels: enhancement

#2313 U20 [PHP 7.4 for Ubuntu 20.04]
  roles/nginx/tasks/install.yml
  roles/www_base/tasks/main.yml
  vars/ubuntu-20.yml
Labels: enhancement

#2314 pin to older python2 versions for kalite on U-20
  roles/kalite/tasks/install.yml
Labels: bug
