Repository iiab/iiab, pull requests merged in 2020-01, with the labels that each got.

#2091 Gitea 1.10.0 -> 1.10.2
  roles/gitea/defaults/main.yml
Labels: bug

#2095 Fix Gitea 404s fix with NGINX (#2057)
  roles/gitea/templates/gitea-nginx.conf.j2
  roles/nginx/README.md
Labels: bug

#2093 Gitea: minimal code cleanup
  roles/gitea/tasks/main.yml
Labels: enhancement

#2094 How does one use vars iiab_home_url & captiveportal_splash_page ?
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement, question

#2098 Begin deprecating DokuWiki, per #2056
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: bug

#2100 Experimentally enable Captive Portal, for IIAB 7.1 testing
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2101 Clarify PR #2100 Captive Portal in local_vars.yml, default_vars.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2104 Deprecate "kolibri setdefault language <en>"
  roles/kolibri/tasks/install.yml
Labels: bug

#2106 fix #1419 rename xsce stuff to iiab
  roles/httpd/templates/010-iiab.conf.j2
  roles/network/templates/network/br0.j2
  roles/network/templates/network/ifcfg-WAN.j2
  roles/network/templates/network/ifcfg-slave.j2
  roles/network/templates/network/ifcfg.j2
  roles/network/templates/network/wifi-slave.j2
  roles/rachel/README.rst
Labels: enhancement

#2111 Nextcloud minimal cleanup for code readability
  roles/nextcloud/tasks/enable_or_disable.yml
  roles/nextcloud/tasks/main.yml
  roles/nextcloud/tasks/setup.yml
Labels: enhancement

#2113 Nextcloud: download the very latest (latest.tar.bz2)
  roles/nextcloud/defaults/main.yml
Labels: enhancement

#2114 Explain #2112 Nextcloud workaround for 1000X faster download
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2115 Document fast download option in nextcloud/defaults/main.yml
  roles/nextcloud/defaults/main.yml
Labels: enhancement

#2116 Cleanup of Nextcloud download speedup/workaround/explanation
  roles/nextcloud/defaults/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2118 phpMyAdmin 5.0.0 -> 5.0.1
  roles/phpmyadmin/defaults/main.yml
Labels: enhancement

#2126 runrole - remove installed lockout
  runrole
Labels: enhancement

#2128 Avoid iiab.ini Ansible warnings by using "{{ item.value | string }}"
  roles/0-init/tasks/iiab_ini.yml
  roles/0-init/tasks/main.yml
  roles/2-common/tasks/xo.yml
  roles/activity-server/tasks/main.yml
  roles/ajenti/tasks/main.yml
  roles/authserver/tasks/main.yml
  roles/awstats/tasks/enable.yml
  roles/bluetooth/tasks/enable.yml
  roles/calibre-web/tasks/enable.yml
  roles/calibre/tasks/enable.yml
  roles/cups/tasks/main.yml
  roles/docker/tasks/main.yml
  roles/dokuwiki/tasks/enable.yml
  roles/elgg/tasks/enable.yml
  roles/gitea/tasks/enable.yml
  roles/idmgr/tasks/main.yml
  roles/iiab-admin/tasks/main.yml
  roles/internetarchive/tasks/enable.yml
  roles/kalite/tasks/enable.yml
  roles/kiwix/tasks/kiwix_enable.yml
  roles/kolibri/tasks/enable.yml
  roles/lokole/tasks/enable.yml
  roles/mediawiki/tasks/enable.yml
  roles/minetest/tasks/enable.yml
  roles/mongodb/tasks/enable.yml
  roles/monit/tasks/install.yml
  roles/moodle-1.9/moodle/tasks/main.yml
  roles/moodle/tasks/enable.yml
  roles/mosquitto/tasks/enable.yml
  roles/munin/tasks/enable.yml
  roles/mysql/tasks/main.yml
  roles/network/tasks/computed_network.yml
  roles/network/tasks/computed_services.yml
  roles/network/tasks/detected_network.yml
  roles/network/tasks/enable_services.yml
  roles/network/tasks/squid.yml
  roles/network/tasks/wondershaper.yml
  roles/nextcloud/tasks/enable.yml
  roles/nextcloud/tasks/main.yml
  roles/nodered/tasks/enable.yml
  roles/nodogsplash/tasks/rpi.yml
  roles/openvpn/tasks/main.yml
  roles/osm/tasks/main.yml
  roles/owncloud/tasks/main.yml
  roles/pathagar/tasks/main.yml
  roles/phpmyadmin/tasks/main.yml
  roles/postgresql/tasks/main.yml
  roles/rachel/tasks/main.yml
  roles/samba/tasks/main.yml
  roles/schooltool/tasks/main.yml
  roles/sugar-stats/tasks/main.yml
  roles/sugarizer/tasks/enable.yml
  roles/teamviewer/tasks/main.yml
  roles/transmission/tasks/main.yml
  roles/usb-lib/tasks/main.yml
  roles/vnstat/tasks/main.yml
  roles/wordpress/tasks/enable.yml
  roles/xovis/tasks/main.yml
Labels: bug

#2127 Refine @jvonau's softcode - subset of #2102 (WIP)
  roles/2-common/tasks/main.yml
  roles/awstats/tasks/enable.yml
  roles/awstats/tasks/install.yml
  roles/awstats/templates/cron.d.awstats.deprecated
  roles/calibre-web/tasks/enable.yml
  roles/calibre-web/templates/calibre-web-nginx.conf.j2
  roles/gitea/tasks/enable.yml
  roles/gitea/tasks/install.yml
  roles/kiwix/defaults/main.yml
  roles/kiwix/tasks/install.yml
  roles/kiwix/tasks/kiwix_enable.yml
  roles/kiwix/tasks/main.yml
  roles/kolibri/tasks/enable.yml
  roles/mediawiki/tasks/enable.yml
  roles/nginx/README.md
  roles/nginx/tasks/install.yml
  roles/nginx/tasks/main.yml
  roles/nginx/tasks/only_nginx.yml
  roles/nginx/tasks/uses_apache.yml
  roles/nginx/templates/dokuwiki-nginx.conf
  roles/nginx/templates/server.conf
  roles/osm-vector-maps/tasks/main.yml
  roles/sugarizer/tasks/enable.yml
  roles/sugarizer/tasks/install.yml
  roles/wordpress/tasks/enable.yml
  roles/wordpress/tasks/install.yml
Labels: enhancement

#2129 Clarify "Add 'XYZ_installed: True' to {{ iiab_state_file }}" in 30 playbooks
  roles/azuracast/tasks/install.yml
  roles/bluetooth/tasks/install.yml
  roles/calibre-web/tasks/install.yml
  roles/calibre/tasks/install.yml
  roles/captiveportal/tasks/main.yml
  roles/cups/tasks/main.yml
  roles/dokuwiki/tasks/install.yml
  roles/elgg/tasks/install.yml
  roles/gitea/tasks/install.yml
  roles/internetarchive/tasks/install.yml
  roles/kalite/tasks/setup.yml
  roles/kiwix/tasks/enable.yml
  roles/kiwix/tasks/install.yml
  roles/kolibri/tasks/install.yml
  roles/lokole/tasks/install.yml
  roles/mediawiki/tasks/install.yml
  roles/minetest/tasks/provision.yml
  roles/mongodb/tasks/install.yml
  roles/moodle/tasks/install.yml
  roles/mosquitto/tasks/install.yml
  roles/munin/tasks/install.yml
  roles/network/tasks/dansguardian.yml
  roles/network/tasks/dhcpd.yml
  roles/network/tasks/named.yml
  roles/network/tasks/squid.yml
  roles/network/tasks/wondershaper.yml
  roles/nextcloud/tasks/install.yml
  roles/nodered/tasks/install.yml
  roles/samba/tasks/main.yml
  roles/sugarizer/tasks/install.yml
  roles/wordpress/tasks/install.yml
Labels: enhancement

#2130 (1) Wordpress quick cleanup (2) need help understanding wordpress/tasks/main.yml
  roles/wordpress/tasks/main.yml
  roles/wordpress/tasks/setup.yml
Labels: enhancement, question

#2132 Quick doc fixes: MediaWiki, NGINX, WordPress
  roles/mediawiki/defaults/main.yml
  roles/mediawiki/tasks/enable.yml
  roles/mediawiki/tasks/main.yml
  roles/nginx/README.md
  roles/wordpress/tasks/main.yml
Labels: enhancement, question

#2133 Softcode/Tighten nginx/tasks/only_nginx.yml & nginx/tasks/uses_apache.yml
  roles/nginx/tasks/only_nginx.yml
  roles/nginx/tasks/uses_apache.yml
Labels: enhancement, question

#2135 NGINX & Apache: bug fix & Stage 9 a bit cleaner
  roles/3-base-server/tasks/main.yml
  roles/9-local-addons/tasks/main.yml
  roles/httpd/tasks/enable.yml
  roles/nginx/tasks/uses_apache.yml
Labels: bug

#2137 Refine @jvonau's "Move nginx shims to roles" #2131
  roles/0-init/tasks/main.yml
  roles/dokuwiki/defaults/main.yml
  roles/dokuwiki/tasks/enable.yml
  roles/dokuwiki/tasks/install.yml
  roles/dokuwiki/templates/dokuwiki-nginx.conf.j2
  roles/elgg/tasks/enable.yml
  roles/elgg/tasks/install.yml
  roles/elgg/tasks/setup.yml
  roles/elgg/templates/elgg-nginx.conf.j2
  roles/elgg/templates/elggdb.sql.j2
  roles/lokole/tasks/enable.yml
  roles/lokole/tasks/install.yml
  roles/lokole/templates/lokole-nginx.conf.j2
  roles/moodle/tasks/install.yml
  roles/moodle/templates/moodle-nginx.conf.j2
  roles/nextcloud/tasks/enable.yml
  roles/nextcloud/tasks/install.yml
  roles/nextcloud/templates/nextcloud-nginx.conf.j2
  roles/nginx/README.md
  roles/nginx/tasks/main.yml
  roles/nginx/templates/elgg-nginx.conf
  roles/nginx/templates/lokole-nginx.conf.j2
  roles/nginx/templates/nodered-nginx.conf.j2
  roles/nodered/tasks/enable.yml
  roles/nodered/tasks/install.yml
  roles/nodered/templates/nodered-nginx.conf.j2
  roles/pbx/defaults/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2138 25 of 26 install.yml's + 10 others tasks/*.yml now write to /etc/iiab/iiab_state.yml
  roles/awstats/tasks/install.yml
  roles/azuracast/tasks/install.yml
  roles/bluetooth/tasks/install.yml
  roles/calibre-web/tasks/install.yml
  roles/calibre/tasks/install.yml
  roles/captiveportal/tasks/main.yml
  roles/cups/tasks/main.yml
  roles/dokuwiki/tasks/install.yml
  roles/elgg/tasks/install.yml
  roles/gitea/tasks/install.yml
  roles/httpd/tasks/install.yml
  roles/internetarchive/tasks/install.yml
  roles/kalite/tasks/install.yml
  roles/kalite/tasks/setup.yml
  roles/kiwix/tasks/install.yml
  roles/kolibri/tasks/install.yml
  roles/lokole/tasks/install.yml
  roles/mediawiki/tasks/install.yml
  roles/minetest/tasks/provision.yml
  roles/mongodb/tasks/install.yml
  roles/monit/tasks/install.yml
  roles/moodle/tasks/install.yml
  roles/mosquitto/tasks/install.yml
  roles/munin/tasks/install.yml
  roles/network/tasks/dansguardian.yml
  roles/network/tasks/dhcpd.yml
  roles/network/tasks/named.yml
  roles/network/tasks/squid.yml
  roles/network/tasks/wondershaper.yml
  roles/nextcloud/tasks/install.yml
  roles/nginx/tasks/install.yml
  roles/nginx/tasks/main.yml
  roles/nodered/tasks/install.yml
  roles/samba/tasks/main.yml
  roles/sugarizer/tasks/install.yml
  roles/teamviewer/tasks/install.yml
  roles/wordpress/tasks/install.yml
Labels: enhancement

#2140 moodle/tasks/enable.yml for NGINX & WordPress tweaks (WIP)
  roles/moodle/tasks/enable.yml
  roles/wordpress/tasks/enable.yml
Labels: enhancement

#2142 (1) Quick clean high-level roles: NGINX, Apache, network, OpenVPN, numbered roles (stages) & defaults_vars.yml (2) Add vars/ubuntu-20.yml for Ubuntu 20.04 pre-releases (3) Fix http://box/mediawiki
  roles/0-init/tasks/main.yml
  roles/1-prep/tasks/main.yml
  roles/2-common/tasks/main.yml
  roles/3-base-server/tasks/main.yml
  roles/4-server-options/tasks/main.yml
  roles/5-xo-services/tasks/main.yml
  roles/6-generic-apps/tasks/main.yml
  roles/7-edu-apps/tasks/main.yml
  roles/8-mgmt-tools/tasks/main.yml
  roles/9-local-addons/tasks/main.yml
  roles/httpd/defaults/main.yml
  roles/mediawiki/defaults/main.yml
  roles/mediawiki/tasks/enable.yml
  roles/mediawiki/templates/mediawiki-nginx.conf.j2
  roles/network/tasks/main.yml
  roles/nginx/defaults/main.yml
  roles/nginx/tasks/disable.yml.deprecated
  roles/nginx/tasks/only_nginx.yml.deprecated
  roles/nginx/tasks/uses_apache.yml.deprecated
  roles/nginx/templates/dokuwiki-nginx.conf.deprecated
  roles/nginx/templates/kalite-nginx.conf.unused
  roles/nginx/templates/mediawiki-nginx.conf.j2.deprecated
  roles/nginx/templates/wordpress-nginx.conf.deprecated
  roles/openvpn/tasks/main.yml
  vars/default_vars.yml
  vars/ubuntu-20.yml
Labels: enhancement

#2147 (1) Clean Munin (2) rm excess '| bool' (casts to boolean) (3) Experimentally comment out Ansible tags (4) Fix 3 /etc/iiab/iiab.ini descriptions
  roles/2-common/tasks/iptables.yml
  roles/2-common/tasks/xo.yml
  roles/all-vars/tasks/main.yml
  roles/awstats/tasks/main.yml
  roles/azuracast/tasks/main.yml
  roles/calibre-web/tasks/enable.yml
  roles/cups/tasks/main.yml
  roles/docker/tasks/main.yml
  roles/dokuwiki/tasks/main.yml
  roles/ejabberd/tasks/main.yml
  roles/ejabberd_xs/tasks/main.yml
  roles/gitea/tasks/enable.yml
  roles/gitea/tasks/install.yml
  roles/httpd/tasks/install.yml
  roles/httpd/tasks/main.yml
  roles/idmgr/tasks/main.yml
  roles/iiab-admin/tasks/access.yml
  roles/iiab-admin/tasks/main.yml
  roles/kolibri/tasks/main.yml
  roles/lokole/tasks/main.yml
  roles/mediawiki/tasks/enable.yml
  roles/mediawiki/tasks/main.yml
  roles/mongodb/tasks/install.yml
  roles/monit/tasks/install.yml
  roles/moodle/tasks/main.yml
  roles/mosquitto/tasks/install.yml
  roles/mosquitto/tasks/main.yml
  roles/munin/tasks/enable.yml
  roles/munin/tasks/install.yml
  roles/munin/tasks/main.yml
  roles/mysql/tasks/main.yml
  roles/network/tasks/computed_network.yml
  roles/network/tasks/dansguardian.yml
  roles/network/tasks/ifcfg_mods.yml
  roles/network/tasks/main.yml
  roles/network/tasks/restart.yml
  roles/nginx/tasks/disable.yml.deprecated
  roles/nodered/tasks/main.yml
  roles/postgresql/tasks/main.yml
  roles/samba/tasks/main.yml
  roles/sugar-stats/tasks/main.yml
  roles/sugarizer/tasks/main.yml
  roles/teamviewer/tasks/install.yml
  roles/vnstat/tasks/main.yml
Labels: enhancement

#2149 Fix for Admin Console login popup loop: install NGINX after Apache & MySQL
  roles/3-base-server/tasks/main.yml
Labels: admin console, bug

#2151 Increase Apache timeout from 120-sec to its 300-sec default, to mitigate Kiwix search proxy timeout failures
  roles/httpd/templates/010-iiab.conf.j2
Labels: bug

#2153 Recommend Ansible 2.9.3
  scripts/ansible
  scripts/ansible-2.8.x
  scripts/ansible-2.9.x
Labels: enhancement

#2158 Cleanup of NGINX/Apache log file PRs #2155, #2156 & begin streamlining Munin playbook (WIP)
  install-support.yml.deprecated
  roles/2-common/tasks/fl.yml
  roles/9-local-addons/tasks/main.yml
  roles/awstats/templates/awstats.schoolserver.conf.j2
  roles/captiveportal/tasks/main.yml
  roles/captiveportal/templates/capture-wsgi.py.j2
  roles/captiveportal/templates/iiab-divert-to-nginx
  roles/mediawiki/tasks/install.yml
  roles/munin/tasks/enable-or-disable.yml
  roles/munin/tasks/install.yml
  roles/munin/tasks/main.yml
  roles/nginx/tasks/install.yml
  roles/nginx/tasks/main.yml
  roles/nginx/templates/nginx.conf.j2
  roles/nginx/templates/ports.conf.j2
  roles/nginx/templates/server.conf.j2
  roles/sugarizer/tasks/install.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2155 point to nginx log file [AWStats]
  roles/awstats/templates/awstats.schoolserver.conf.j2
Labels: enhancement

#2159 Mediawiki 1.34.0 strictly disallows password 'changeme' so for now let's use 'changeme2020'
  roles/mediawiki/defaults/main.yml
Labels: bug

#2160 KA Lite temp patch so IIAB once again installs on RPi: mv /etc/pip.conf /etc/pip.conf.see-iiab-issue-2139
  roles/kalite/tasks/install.yml
Labels: bug

#2163 KA Lite workaround: fix quotes
  roles/kalite/tasks/install.yml
Labels: bug

#2165 Gitea 1.10.2 -> 1.10.3 security release
  roles/gitea/defaults/main.yml
Labels: enhancement

#2166 Wordpress & Munin scaffolding (WIP)
  roles/munin/tasks/main.yml
  roles/wordpress/defaults/main.yml
  roles/wordpress/tasks/enable-or-disable.yml
  roles/wordpress/tasks/enable.yml
  roles/wordpress/tasks/install.yml
  roles/wordpress/tasks/main.yml
  roles/wordpress/tasks/setup.yml
  roles/wordpress/templates/get-iiab-wp-salts.j2
Labels: enhancement, question

#2167 Wordpress/Munin Scaffolding: tiny enhancements
  roles/osm-vector-maps/tasks/main.yml
  roles/wordpress/tasks/install.yml
Labels: enhancement

#2169 Wordpress/Munin Scaffolding: tighten up as possible (super)model playbooks
  roles/munin/defaults/main.yml
  roles/munin/tasks/install.yml
  roles/transmission/defaults/main.yml
  roles/wordpress/tasks/install.yml
  vars/default_vars.yml
Labels: enhancement

#2173 Revert iiab#2160 in kalite/tasks/install.yml [piwheels' setuptools python issue]
  roles/kalite/tasks/install.yml
Labels: bug

#2174 Calibre-Web: master -> 0.6.5
  roles/calibre-web/defaults/main.yml
Labels: enhancement

#2176 Recommend Ansible 2.9.4
  scripts/ansible
  scripts/ansible-2.9.x
Labels: enhancement

#2177 Lokole 0.5.4 -> 0.5.5
  roles/lokole/defaults/main.yml
Labels: enhancement

#2178 Lokole 0.5.5 -> 0.5.6
  roles/lokole/defaults/main.yml
Labels: enhancement

#2179 WIP: Validate 46+46 boolean vars in 0-init (*_install + *_enabled). Similarly when invoking {Munin, WordPress} to fine-tune this for other playbooks etc
  roles/0-init/tasks/main.yml
  roles/0-init/tasks/validate_vars.yml
  roles/5-xo-services/tasks/main.yml
  roles/munin/tasks/main.yml
  roles/network/defaults/main.yml
  roles/wordpress/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2180 Explanatory Error Msgs for var validation in 0-init/tasks/validate_vars.yml, munin/tasks/main.yml, wordpress/tasks/main.yml etc
  roles/0-init/tasks/main.yml
  roles/0-init/tasks/validate_vars.yml
  roles/munin/tasks/main.yml
  roles/wordpress/tasks/main.yml
Labels: enhancement

#2181 Lokole 0.5.6 -> 0.5.7
  roles/lokole/defaults/main.yml
Labels: enhancement

#2185 Modularize & Clean @jvonau's PR #2171 - uWSGI for Captive Portal & Admin Console on NGINX
  roles/2-common/tasks/fl.yml
  roles/captiveportal/tasks/enable-or-disable.yml
  roles/captiveportal/tasks/install.yml
  roles/captiveportal/tasks/main.yml
  roles/captiveportal/templates/capture-wsgi.py.j2
  roles/nginx/tasks/install.yml
  roles/nginx/tasks/main.yml
  roles/nginx/templates/admin-console-apache.conf.unused
  roles/nginx/templates/admin-console-nginx.conf.unused
  roles/nginx/templates/admin-console.ini.unused
  roles/nginx/templates/uwsgi.service.unused
  roles/nodejs/tasks/main.yml
Labels: enhancement

#2187 validation_vars.yml - build on @jvonau's #2183 [DISALLOW "XYZ_install: False" WHEN "XYZ_installed is defined" IN /etc/iiab/iiab_state.yml]
  roles/0-init/tasks/main.yml
  roles/0-init/tasks/validate_vars.yml
  roles/captiveportal/tasks/main.yml
  roles/munin/tasks/main.yml
  roles/sugarizer/templates/sugarizer.service
  roles/wordpress/tasks/main.yml
  vars/default_vars.yml
Labels: enhancement

#2188 make mw use current host instead of localhost [MediaWiki]
  roles/mediawiki/tasks/install.yml
Labels: bug

#2190 Refine @jvonau's PR #2134 - avoid dependency dups for speed / bugfix
  roles/0-init/tasks/main.yml
  roles/1-prep/tasks/main.yml
  roles/3-base-server/tasks/main.yml
  roles/4-server-options/tasks/main.yml
  roles/5-xo-services/tasks/main.yml
  roles/6-generic-apps/tasks/main.yml
  roles/7-edu-apps/tasks/main.yml
  roles/8-mgmt-tools/tasks/main.yml
  roles/moodle/tasks/enable.yml
  roles/moodle/tasks/install.yml
  roles/mysql/tasks/main.yml
  roles/nodejs/tasks/main.yml
  roles/nodered/meta/main.yml
  roles/nodered/tasks/install.yml
  roles/pathagar/tasks/main.yml
  roles/pbx/meta/main.yml
  roles/pbx/tasks/main.yml
  roles/sugarizer/meta/main.yml
  roles/sugarizer/tasks/enable.yml
  roles/sugarizer/tasks/install.yml
Labels: enhancement

#2189 Scaffolding 2.0 for supermodel playbooks e.g. wordpress, munin, captiveportal
  roles/0-init/tasks/main.yml
  roles/9-local-addons/tasks/main.yml
  roles/captiveportal/tasks/main.yml
  roles/captiveportal/templates/capture-wsgi.py.j2
  roles/httpd/tasks/main.yml
  roles/httpd/tasks/php-stem.yml.deprecated
  roles/munin/tasks/apache.yml
  roles/munin/tasks/enable-or-disable.yml
  roles/munin/tasks/main.yml
  roles/munin/tasks/nginx.yml
  roles/mysql/tasks/main.yml
  roles/nginx/README.md
  roles/nodejs/tasks/main.yml
  roles/openvpn/tasks/main.yml
  roles/phpmyadmin/tasks/main.yml
  roles/postgresql/tasks/main.yml
  roles/transmission/tasks/main.yml
  roles/vnstat/tasks/main.yml
  roles/wordpress/tasks/apache.yml
  roles/wordpress/tasks/enable-or-disable.yml
  roles/wordpress/tasks/main.yml
  roles/wordpress/tasks/nginx.yml
  runrole
Labels: enhancement

#2191 Rename var nginx_config_dir to nginx_conf_dir
  roles/awstats/tasks/enable.yml
  roles/calibre-web/tasks/enable.yml
  roles/dokuwiki/tasks/enable.yml
  roles/elgg/tasks/enable.yml
  roles/gitea/tasks/enable.yml
  roles/kiwix/tasks/enable.yml
  roles/kolibri/tasks/enable.yml
  roles/lokole/tasks/enable.yml
  roles/mediawiki/tasks/enable.yml
  roles/moodle/tasks/enable.yml
  roles/munin/tasks/nginx.yml
  roles/nextcloud/tasks/enable.yml
  roles/nginx/defaults/main.yml
  roles/nginx/tasks/main.yml
  roles/nginx/tasks/uses_apache.yml.deprecated
  roles/nginx/templates/server.conf.j2
  roles/nodered/tasks/enable.yml
  roles/osm-vector-maps/tasks/main.yml
  roles/sugarizer/tasks/enable.yml
  roles/wordpress/tasks/nginx.yml
  vars/default_vars.yml
Labels: enhancement

#2192 Clean {MIN, MEDIUM, BIG} local_vars.yml files, pre-announce future deprecations
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2196 Quick doc clean for NGINX, PostgreSQL, MongoDB, Node.js
  roles/mongodb/defaults/main.yml
  roles/nginx/README.md
  roles/nodejs/defaults/main.yml
  roles/postgresql/defaults/main.yml
  roles/postgresql/tasks/main.yml
Labels: enhancement

#2198 Php stem
  roles/httpd/tasks/main.yml
  roles/httpd/tasks/php-stem.yml
  roles/nginx/tasks/install.yml
Labels: enhancement

#2201 Refine @jvonau's osm-split PR #2199
  roles/captiveportal/tasks/main.yml
  roles/munin/tasks/main.yml
  roles/osm-vector-maps/files/test-index.redirect
  roles/osm-vector-maps/tasks/enable-or-disable.yml.deprecated
  roles/osm-vector-maps/tasks/install.yml
  roles/osm-vector-maps/tasks/main.yml
  roles/osm-vector-maps/tasks/nginx.yml
  roles/osm-vector-maps/templates/osm-vector-maps-nginx.conf.j2
  roles/wordpress/tasks/main.yml
Labels: enhancement

#2202 Fix 2-common/tasks/fl.yml 'downloads' dirs
  roles/2-common/tasks/fl.yml
Labels: bug

#2206 Cleaner local_vars.yml files
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2211 Var Validation Explained: Error msgs that tell you what's happening & what to do
  roles/0-init/tasks/validate_vars.yml
  roles/captiveportal/tasks/main.yml
  roles/munin/tasks/main.yml
  roles/osm-vector-maps/tasks/main.yml
  roles/wordpress/tasks/main.yml
Labels: enhancement

#2214 Lokole 0.5.7 -> 0.5.8
  roles/lokole/defaults/main.yml
Labels: enhancement

#2215 Lokole 0.5.8 -> 0.5.9
  roles/lokole/defaults/main.yml
Labels: enhancement

#2213 Mitra's tweaks to mediawiki install
  roles/mediawiki/defaults/main.yml
  roles/mediawiki/tasks/install.yml
  roles/mediawiki/templates/mediawiki-nginx.conf.j2
Labels: enhancement

#2216 Lokole 0.5.9 -> 0.5.10
  roles/lokole/defaults/main.yml
Labels: enhancement
