Repository iiab/iiab, pull requests merged in 2020-05, with the labels that each got.

#2380 Ap0+wifi up down rebased [simultaneous WiFi-as-hotspot AND WiFi-as-client]
  iiab-network
  roles/2-common/templates/iiab-startup.sh
  roles/network/defaults/main.yml
  roles/network/tasks/NM-debian.yml
  roles/network/tasks/computed_network.yml
  roles/network/tasks/computed_services.yml
  roles/network/tasks/detected_network.yml
  roles/network/tasks/enable_services.yml
  roles/network/tasks/fedora/NM.yml
  roles/network/tasks/fedora/create_ifcfg.yml.deprecated
  roles/network/tasks/fedora/detected_redhat.yml
  roles/network/tasks/fedora/edit_ifcfg.yml
  roles/network/tasks/fedora/enable_wan.yml
  roles/network/tasks/fedora/hosts.yml.deprecated
  roles/network/tasks/fedora/ifcfg_mods.yml
  roles/network/tasks/fedora/redetect.yml
  roles/network/tasks/fedora/static.yml
  roles/network/tasks/hostapd.yml
  roles/network/tasks/main.yml
  roles/network/tasks/netplan.yml
  roles/network/tasks/restart.yml
  roles/network/tasks/sysd-netd-debian.yml
  roles/network/templates/hostapd/00-iiab-debug
  roles/network/templates/hostapd/50-hostapd
  roles/network/templates/hostapd/70-persistent-net.rules
  roles/network/templates/hostapd/hostapd.conf.j2
  roles/network/templates/hostapd/hostapd.legacy.j2
  roles/network/templates/hostapd/hostapd.service.j2
  roles/network/templates/hostapd/iiab-hostapd.conf.j2
  roles/network/templates/hostapd/netd-disp
  roles/network/templates/network/ap0-manage.conf
  roles/network/templates/network/dhcpcd.conf.j2
  roles/network/templates/network/dnsmasq.sh.j2
  roles/network/templates/network/iiab-hotspot-off
  roles/network/templates/network/iiab-hotspot-on
  roles/network/templates/network/manage.conf.j2
  roles/network/templates/network/rpi.j2
  roles/network/templates/network/systemd-br0-network.j2
  roles/network/templates/network/systemd-br0-slave.j2
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2383 2382 [hostapd / restart / dnsmasq / systemd-networkd refinement]
  roles/network/tasks/hostapd.yml
  roles/network/tasks/restart.yml
  roles/network/tasks/sysd-netd-debian.yml
Labels: enhancement

#2388 Calibre-Web 0.6.6 -> 0.6.7
  roles/calibre-web/defaults/main.yml
Labels: enhancement

#2392 Disable Captive Portal by default
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: bug

#2393 2384 rebase
  roles/network/tasks/computed_network.yml
  roles/network/tasks/hostapd.yml
  roles/network/tasks/main.yml
  roles/network/tasks/restart.yml
  roles/network/tasks/rpi_debian.yml
  roles/network/tasks/sysd-netd-debian.yml
  roles/network/templates/hostapd/50-hostapd
  roles/network/templates/hostapd/README.ap0
  roles/network/templates/hostapd/clone-wifi.service.j2
  roles/network/templates/hostapd/hostapd.service.j2
  roles/network/templates/hostapd/netd-disp
  roles/network/templates/hostapd/netd-disp2
  roles/network/templates/hostapd/test-wifi
  roles/network/templates/hostapd/wifi-test.service.j2
  roles/network/templates/network/iiab-hotspot-off
  roles/network/templates/network/iiab-hotspot-on
  roles/network/templates/network/systemd-br0-network.j2
Labels: enhancement

#2397 Gitea 1.11.4 -> 1.11.5
  roles/gitea/defaults/main.yml
Labels: enhancement

#2396 Clarify (1) gateway "passthrough" in vars/* (2) no_net_restart in network/tasks/main.yml
  roles/network/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2398 while testing 2395 - handle no wifi
  roles/network/tasks/sysd-netd-debian.yml
Labels: bug

#2400 Fix #2399: legacy var {{ nextcloud_required_ip }} is still invoked for doc purposes
  roles/nextcloud/defaults/main.yml
Labels: bug

#2395 install and start dnsmasq early - add option to set upstream dns server
  roles/1-prep/tasks/main.yml
  roles/3-base-server/tasks/main.yml
  roles/network/tasks/dnsmasq.yml
  roles/network/tasks/enable_services.yml
  roles/network/templates/network/dnsmasq-iiab
  roles/network/templates/network/dnsmasq.conf.j2
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement, question

#2403 selective rfkill unblock for raspbian
  roles/network/templates/hostapd/test-wifi
Labels: enhancement

#2404 added video MIME support for Nextcloud/Nginx per #2262
  roles/nextcloud/templates/nextcloud-nginx.conf.j2
Labels: bug

#2405 Try doubling hostapd_wait: to 10 sec, so dnsmasq restart works during IIAB install
  roles/network/defaults/main.yml
Labels: bug

#2406 tuning of 52c0f2aaea2fa19c3ade8ed50b978acd59733d32 [internal WiFi hotspot is not working]
  roles/network/templates/hostapd/50-hostapd
Labels: bug

#2411 Calibre-Web: fresh new app.db (customized for Calibre-Web 0.6.7 with IIAB)
  roles/calibre-web/files/app.db
  roles/calibre-web/templates/calibre-web.service.j2
Labels: bug

#2413 TK Issue: install Apache on demand in ./runrole elgg|lokole|moodle|nodered|cups
  roles/0-init/defaults/main.yml
  roles/0-init/tasks/main.yml
  roles/3-base-server/tasks/main.yml
  roles/4-server-options/tasks/main.yml
  roles/9-local-addons/tasks/main.yml
  roles/awstats/tasks/install.yml
  roles/calibre-web/tasks/install.yml
  roles/cups/tasks/main.yml
  roles/elgg/tasks/install.yml
  roles/gitea/tasks/install.yml
  roles/httpd/tasks/install.yml
  roles/httpd/tasks/main.yml
  roles/internetarchive/tasks/install.yml
  roles/internetarchive/tasks/main.yml
  roles/kalite/tasks/install.yml
  roles/kiwix/tasks/install.yml
  roles/kolibri/tasks/install.yml
  roles/lokole/tasks/install.yml
  roles/mediawiki/tasks/install.yml
  roles/mongodb/tasks/install.yml
  roles/moodle/tasks/install.yml
  roles/munin/tasks/install.yml
  roles/mysql/tasks/install.yml
  roles/nextcloud/tasks/install.yml
  roles/nginx/README.md
  roles/nginx/tasks/enable-or-disable.yml
  roles/nginx/tasks/install.yml
  roles/nodered/tasks/install.yml
  roles/phpmyadmin/tasks/main.yml
  roles/sugarizer/tasks/install.yml
  roles/usb_lib/tasks/apache.yml
  roles/usb_lib/tasks/install.yml
  roles/usb_lib/tasks/main.yml
  roles/usb_lib/tasks/nginx.yml
  roles/wordpress/tasks/install.yml
  roles/www_base/tasks/main.yml
  roles/www_options/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: admin console, bug, question

#2415 kiwix-tools 3.1.1
  roles/kiwix/defaults/main.yml
Labels: enhancement

#2418 Eliminate install of 'apache2' (from Stage 9)
  roles/9-local-addons/tasks/main.yml
  vars/default_vars.yml
Labels: admin console, enhancement

#2419 kiwix-tools 3.1.1 -> 3.1.1-0
  roles/kiwix/defaults/main.yml
Labels: enhancement

#2425 Cleaner local_vars.yml & default_vars.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2426 use /etc/rpi-issue for raspbian test
  scripts/local_facts.fact
Labels: enhancement
