Repository iiab/iiab, pull requests merged in 2020-09, with the labels that each got.

#2501 Proposed enhancements to PR #2499: Mint might need static mapping to Ubuntu [For MongoDB. And get real admitting we no longer support 11 distros/versions...to strengthen support for our 4 core OS's]
  roles/mongodb/tasks/install.yml
  scripts/ansible
  scripts/local_facts.fact
  vars/default_vars.yml
  vars/linuxmint-20.yml
Labels: enhancement

#2504 Gitea 1.12.3 -> 1.12.4
  roles/gitea/defaults/main.yml
Labels: enhancement

#2509 Warning about 5 GHz sabotaging IIAB's internal WiFi was not being read. So raise it within local_vars.yml & MAKE IT LOUDER
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2510 Connecting IIAB to 5 GHz WiFi effectively sabotages IIAB's internal hotspot: warn implementers loudly/broadly
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2508 add warning for 5Ghz NOT CHANGING HOSTAPD
  roles/network/templates/hostapd/50-hostapd
  roles/network/templates/hostapd/test-wifi
Labels: enhancement, question

#2514 Lokole sync, building on PRs #2507 & #2513
  roles/lokole/tasks/install.yml
  roles/lokole/tasks/main.yml
  roles/lokole/templates/celery.service.j2
  roles/lokole/templates/celerybeat.service.j2
  roles/lokole/templates/lokole_restarter.service.j2
Labels: enhancement

#2515 detect secondary gateway on wifi interface for no_net_restart
  roles/network/tasks/detected_network.yml
  roles/network/tasks/main.yml
Labels: enhancement

#2516 better usage explanation of no_net_restart
  roles/network/tasks/main.yml
Labels: enhancement

#2518 Begin transition to Ansible 2.10 (now that ansible-base 2.10.1 is released & appears solid!)
  scripts/ansible
  scripts/ansible.md
Labels: enhancement

#2519 2515 fix [for non-WiFi situations]
  roles/network/tasks/detected_network.yml
Labels: bug

#2520 Improve Ansible 2.10 installer's output/explanations
  scripts/ansible
Labels: enhancement

#2524 2515 fix [another "secondary gateway" precaution]
  roles/network/defaults/main.yml
  roles/network/tasks/detected_network.yml
Labels: enhancement

#2527 Communicate Ansible 2.10 options, to implementers & maintainers
  scripts/ansible
Labels: enhancement

#2529 update test.yml
  tests/test.yml
Labels: enhancement

#2530 Hostapd ctl
  roles/network/templates/hostapd/hostapd.conf.j2
Labels: enhancement, question

#2500 Infastructure for proper versioning.
  roles/0-init/defaults/main.yml
  roles/0-init/tasks/main.yml
  roles/9-local-addons/tasks/main.yml
  scripts/local_facts.fact
  upgrade_roles
  upgrade_roles.txt
  vars/default_vars.yml
Labels: enhancement, question

#2531 Structural merges at the end of a release cycle are Not Ok
  roles/0-init/defaults/main.yml
  roles/0-init/tasks/main.yml
  roles/9-local-addons/tasks/main.yml
  scripts/local_facts.fact
  upgrade_roles
  upgrade_roles.txt
  vars/default_vars.yml
Labels: question

#2537 Samba role standardized/modularized, for runrole etc
  roles/1-prep/tasks/main.yml
  roles/3-base-server/tasks/main.yml
  roles/4-server-options/tasks/main.yml
  roles/6-generic-apps/tasks/main.yml
  roles/nginx/README.md
  roles/samba/tasks/enable-or-disable.yml
  roles/samba/tasks/install.yml
  roles/samba/tasks/main.yml
Labels: bug, question

#2543 Sugarizer 1.3.0 -> 1.4.0
  roles/sugarizer/defaults/main.yml
Labels: enhancement

#2545 MediaWiki 1.34.2 -> 1.34.3 Security Patches
  roles/mediawiki/defaults/main.yml
Labels: enhancement

#2544 iiab-diagnostics: collect last 100 lines from iiab-configure.log (generated by ./iiab-configure)
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
Labels: enhancement

#2546 Near-final Release Cleanup of validate_vars, default_vars, local_vars, Stages 0-4, SSHD, Moodle, MediaWiki
  roles/0-init/tasks/main.yml
  roles/0-init/tasks/validate_vars.yml
  roles/1-prep/tasks/main.yml
  roles/2-common/tasks/packages.yml
  roles/3-base-server/tasks/main.yml
  roles/4-server-options/tasks/main.yml
  roles/mediawiki/defaults/main.yml
  roles/moodle/tasks/main.yml
  roles/network/tasks/avahi.yml
  roles/network/templates/gateway/iiab-gen-iptables
  roles/nginx/README.md
  roles/sshd/tasks/enable-or-disable.yml
  roles/sshd/tasks/install.yml
  roles/sshd/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2540 Prune validate
  roles/0-init/tasks/main.yml
  roles/0-init/tasks/validate_vars.yml
  roles/1-prep/tasks/main.yml
  roles/3-base-server/tasks/main.yml
  roles/4-server-options/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2547 MediaWiki 1.34.4 -> 1.35.0 LTS
  roles/mediawiki/defaults/main.yml
Labels: enhancement

#2548 Lint for release: osm-vector-maps indentation/spacing
  roles/osm-vector-maps/tasks/install.yml
  roles/osm-vector-maps/tasks/main.yml
Labels: enhancement

#2549 Further deprecate long-unmaintained roles for IIAB 7.2 release
  roles/0-init/tasks/validate_vars.yml
  tests/test.yml
  unmaintained-roles.txt
Labels: enhancement

#2550 Calibre-Web master -> 0.6.9 for IIAB 7.2 release
  roles/calibre-web/defaults/main.yml
Labels: enhancement

#2551 WIP: What's Changed in Maps for the IIAB 7.2 Release? [OSM]
  roles/osm-vector-maps/README.md
  roles/osm-vector-maps/tasks/install.yml
  roles/osm-vector-maps/tasks/main.yml
  roles/osm-vector-maps/tasks/nginx.yml
Labels: enhancement, question
