Repository iiab/iiab, pull requests merged in 2020-10, with the labels that each got.

#2554 Gitea 1.12.4 -> 1.12.5
  roles/gitea/defaults/main.yml
Labels: enhancement

#2556 Kolibri timeout fix: 90 -> 1200 sec (yes, that's 20 minutes!)
  roles/kolibri/templates/kolibri.service.j2
Labels: bug

#2557 Document that admin_console_install and _enabled now work
  roles/0-init/tasks/validate_vars.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2568 phpMyAdmin 5.0.2 -> 5.0.3
  roles/phpmyadmin/defaults/main.yml
  roles/phpmyadmin/tasks/install.yml
Labels: enhancement

#2569 Sugarizer Server 1.2.0 -> 1.3.0
  roles/sugarizer/defaults/main.yml
Labels: enhancement

#2566 Fix for Graphical and TTY Logins [clean up auto-checking for iiab-admin's published password]
  roles/iiab-admin/tasks/admin-user.yml
  roles/iiab-admin/tasks/main.yml
  roles/iiab-admin/templates/sshpwd-lxde-iiab.sh
  roles/iiab-admin/templates/sshpwd-profile-iiab.sh
  roles/www_options/tasks/main.yml
Labels: bug

#2571 Published password auto-warnings: cleaner bash code & explanations (in sshpwd-profile-iiab.sh and sshpwd-lxde-iiab.sh)
  roles/iiab-admin/templates/sshpwd-lxde-iiab.sh
  roles/iiab-admin/templates/sshpwd-profile-iiab.sh
Labels: enhancement

#2565 maps_from_internet_archive & tidying of iiab-network, default_vars.yml, local_vars.yml, iiab-admin/README.rst, osm-vector-maps/README.md [Aside: iiab_home_url clarif ongoing, recommend ansible-base 2.10.2]
  iiab-network
  roles/4-server-options/tasks/main.yml
  roles/iiab-admin/README.rst
  roles/osm-vector-maps/README.md
  scripts/ansible
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2562 For TK alter use of second_gateway_found.changed
  roles/network/tasks/detected_network.yml
Labels: bug

#2575 phpMyAdmin 5.0.3 -> 5.0.4 [and change download site from d.iiab.io/packages to phpmyadmin.net/files/*]
  roles/phpmyadmin/defaults/main.yml
  roles/phpmyadmin/tasks/install.yml
Labels: bug, enhancement

#2573 Let's consider variable "iiab_admin_can_sudo: True" & support "admin_console_group: iiab-admin" and explain them for all in roles/iiab-admin/README.rst
  roles/2-common/tasks/packages.yml
  roles/iiab-admin/README.rst
  roles/iiab-admin/defaults/main.yml
  roles/iiab-admin/tasks/access.yml
  roles/iiab-admin/tasks/admin-user.yml
  roles/iiab-admin/tasks/main.yml
  roles/iiab-admin/tasks/pwd-warnings.yml
  roles/iiab-admin/tasks/sudo-prereqs.yml
  roles/iiab-admin/templates/sshpwd-lxde-iiab.sh
  roles/iiab-admin/templates/sshpwd-profile-iiab.sh
  roles/nginx/tasks/install.yml
  roles/pbx/defaults/main.yml
  roles/transmission/defaults/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: admin console, enhancement, question

#2577 Moodle git repo *VERY* slow: revert to GitHub repo
  roles/moodle/defaults/main.yml
Labels: enhancement

#2579 Lint for release: scripts/local_facts.fact & remove legacy "tags:" from 6 remaining files (.yml's)
  iiab-from-cmdline.yml
  iiab-from-console.yml
  iiab-network.yml
  iiab-stages.yml
  install-support.yml
  run-one-role.yml
  scripts/local_facts.fact
Labels: admin console, enhancement

#2586 gui_desired_network_role is defined in systemd.j2 [solves two Debian 11 issues?]
  roles/network/templates/network/systemd.j2
Labels: bug

#2588 Typos in iiab-hotspot-on, iiab-hotspot-off, systemd-static-net.j2 [networking]
  roles/network/templates/network/iiab-hotspot-off
  roles/network/templates/network/iiab-hotspot-on
  roles/network/templates/network/systemd-static-net.j2
Labels: bug

#2589 iiab-diagnostics: stronger password redaction & 'iw list' to show if a laptop (etc) is capable of Dual-WiFi (ap0)
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
Labels: enhancement

#2591 python3-packaging apt package to avoid Ansible pink warning
  scripts/ansible
Labels: enhancement

#2593 NetworkManager (NM) detection for Ubuntu 20.10&All + remove long-deprecated phplib_dir + Linux Mint /etc/os-release fix
  roles/0-init/tasks/main.yml
  scripts/local_facts.fact
Labels: admin console, bug

#2594 Bluetooth changes on Ubuntu 20.10
  roles/bluetooth/tasks/install.yml
Labels: bug

#2596 Fix $OS in scripts/local_facts.fact for Mint
  scripts/local_facts.fact
Labels: bug

#2595 MongoDB for Ubuntu 20.10 (Groovy Gorilla)
  roles/mongodb/tasks/install.yml
Labels: enhancement

#2597 scripts/local_facts.fact: quoting vars is safer...on these 3 lines
  scripts/local_facts.fact
Labels: enhancement

#2599 4 renames: network-manager -> NetworkManager for Ubuntu 20.10
  roles/network/tasks/NM-debian.yml
  roles/network/tasks/hostapd.yml
  roles/network/templates/hostapd/clone-wifi.service.j2
  roles/network/templates/hostapd/hostapd.service.j2
  roles/network/templates/hostapd/wifi-test.service.j2
Labels: bug

#2600 PostgreSQL on Debian 10 & 11
  roles/postgresql/tasks/install.yml
Labels: enhancement

#2605 Remove quotes from ./runrole's run-one-role.yml as with all other .yml's
  run-one-role.yml
Labels: enhancement

#2606 Node.js 12 -> 14 LTS for Node-RED, Sugarizer and Internet Archive
  roles/internetarchive/tasks/install.yml
  roles/nodered/tasks/install.yml
  vars/default_vars.yml
Labels: enhancement
