Repository iiab/iiab, pull requests merged in 2020-08, with the labels that each got.

#2474 Initialize /etc/iiab/iiab_state.yml warning operators not to mess with it!
  iiab-install
  runrole
Labels: enhancement

#2476 New pastebin service for iiab-diagnostics, as dpaste.com stopped working
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
Labels: enhancement

#2471 RPiOS - use dhcpcd hooks to restart hostapd when br0 appears [for Ubuntu too]
  roles/network/tasks/enable_services.yml
  roles/network/templates/hostapd/50-hostapd
  roles/network/templates/network/dnsmasq.sh.j2
Labels: enhancement

#2472 RFC Firmware downgrading [WiFi hotspot capacity workaround, for Raspberry Pi]
  roles/firmware/tasks/install.yml
  roles/firmware/tasks/main.yml
  roles/firmware/templates/check-firmware.service
  roles/firmware/templates/check-firmware.sh
  roles/firmware/templates/fw_warn.sh
  roles/network/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2477 Dual WiFi WARNING: 5 GHz connection from internal WiFi to Internet...ends up sabotaging legacy WiFi client devices that require 2.4GHz !
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2478 Raspbian renamed to Raspberry Pi OS / RaspiOS: so clean up IIAB's default_vars.yml & its 3 main local_vars.yml files [& rename 'RPi_firmware_retrieved' to 'rpi_firmware_downloaded']
  roles/firmware/tasks/install.yml
  roles/firmware/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2473 Stage1.5 [OSM]
  roles/osm-vector-maps/README.md
  roles/osm-vector-maps/defaults/main.yml
  roles/osm-vector-maps/files/countries.json
  roles/osm-vector-maps/files/fonts/fonts.css
  roles/osm-vector-maps/files/fonts/noto-sans-v8-latin-700.eot
  roles/osm-vector-maps/files/fonts/noto-sans-v8-latin-700.svg
  roles/osm-vector-maps/files/fonts/noto-sans-v8-latin-700.ttf
  roles/osm-vector-maps/files/fonts/noto-sans-v8-latin-700.woff
  roles/osm-vector-maps/files/fonts/noto-sans-v8-latin-700.woff2
  roles/osm-vector-maps/files/fonts/noto-sans-v8-latin-italic.eot
  roles/osm-vector-maps/files/fonts/noto-sans-v8-latin-italic.svg
  roles/osm-vector-maps/files/fonts/noto-sans-v8-latin-italic.ttf
  roles/osm-vector-maps/files/fonts/noto-sans-v8-latin-italic.woff
  roles/osm-vector-maps/files/fonts/noto-sans-v8-latin-italic.woff2
  roles/osm-vector-maps/files/fonts/noto-sans-v8-latin-regular.eot
  roles/osm-vector-maps/files/fonts/noto-sans-v8-latin-regular.svg
  roles/osm-vector-maps/files/fonts/noto-sans-v8-latin-regular.ttf
  roles/osm-vector-maps/files/fonts/noto-sans-v8-latin-regular.woff
  roles/osm-vector-maps/files/fonts/noto-sans-v8-latin-regular.woff2
  roles/osm-vector-maps/files/init.json
  roles/osm-vector-maps/files/map_functions.js
  roles/osm-vector-maps/files/osm-fixup.py
  roles/osm-vector-maps/files/test-index.redirect
  roles/osm-vector-maps/tasks/install.yml
  roles/osm-vector-maps/tasks/main.yml
  roles/osm-vector-maps/templates/iiab-update-map
  roles/osm-vector-maps/templates/index.html
  roles/osm-vector-maps/templates/main.js
  roles/osm-vector-maps/templates/osm-vector-maps-nginx.conf.j2
  roles/osm-vector-maps/templates/osm-vector-maps.conf
  vars/default_vars.yml
Labels: enhancement

#2480 Regions
  roles/osm-vector-maps/tasks/install.yml
Labels: bug

#2482 scripts/ansible: temp workaround (revert to Ansible 2.9.6) mitigating #2481
  scripts/ansible
Labels: bug

#2488 MariaDB [rework security, eliminate {{ mysql_root_password }}]
  roles/elgg/tasks/setup.yml
  roles/mysql/defaults/main.yml
  roles/mysql/tasks/install.yml
  roles/mysql/templates/my.cnf.j2
  roles/nextcloud/tasks/setup.yml
  roles/pbx/tasks/freepbx.yml
  vars/default_vars.yml
Labels: bug

#2490 scripts/ansible: revert to RaspiOS's own /etc/apt/sources.list for 64-bit RaspiOS etc
  scripts/ansible
Labels: enhancement

#2489 FreePBX fixes for php7.4 on Ubuntu 20.04
  roles/pbx/defaults/main.yml
  roles/pbx/tasks/freepbx.yml
  roles/pbx/tasks/freepbx_dependencies.yml
  roles/pbx/tasks/freepbx_enable.yml
  roles/pbx/tasks/install.yml
  roles/pbx/tasks/main.yml
  roles/pbx/templates/pbx.patch
  roles/pbx/templates/pbx2.patch
Labels: enhancement

#2492 local_vars_big.yml: set monit_install & monit_enabled to False
  vars/local_vars_big.yml
Labels: bug

#2491 BUGFIX Usbmnt2 [usbmount_0.0.14.1_all.deb -> usbmount_0.0.22_all.deb on Debian]
  roles/2-common/tasks/packages.yml
  roles/usb_lib/tasks/install.yml
Labels: enhancement

#2487 7.2 maps [OSM "Preview World" tileset to zoom level 7]
  roles/osm-vector-maps/tasks/install.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2493 RFC Mongo2 [reinforce MongoDB on most distros, e.g. for Sugarizer]
  roles/mongodb/tasks/install.yml
  roles/mongodb/tasks/main.yml
  roles/mongodb/tasks/main2.yml
  roles/sugarizer/tasks/main.yml
  roles/sugarizer/tasks/main2.yml
Labels: enhancement, question

#2494 fix x86_64 [MongoDB]
  roles/mongodb/tasks/install.yml
Labels: bug

#2495 various fixes
  roles/mongodb/tasks/install.yml
  roles/osm-vector-maps/tasks/install.yml
  roles/postgresql/tasks/install.yml
Labels: enhancement

#2498 Revert "use ansible_userspace_architecture for booted 64bit kernels a…
  roles/mongodb/tasks/install.yml
Labels: bug
