Repository iiab/iiab, pull requests merged in 2020-07, with the labels that each got.

#2460 Kiwix-tools 3.1.2
  roles/kiwix/defaults/main.yml
Labels: enhancement

#2465 change resize service to use growpart, which must be installed for raspios
  roles/1-prep/tasks/raspberry_pi.yml
  roles/1-prep/templates/iiab-rpi-max-rootfs.sh
Labels: enhancement

#2464 More php [fix for OSM]
  roles/httpd/tasks/install.yml
  roles/mysql/tasks/install.yml
  roles/osm-vector-maps/tasks/install.yml
  roles/www_base/tasks/main.yml
Labels: admin console, bug, question

#2466 Calibre-Web 0.6.8 -> master
  roles/calibre-web/defaults/main.yml
Labels: enhancement

#2467 Gitea 1.12.1 -> 1.12.2
  roles/gitea/defaults/main.yml
Labels: enhancement

#2468 7.2 kiwix apk
  roles/kiwix/tasks/install.yml
  roles/kiwix/tasks/kiwix-apk.yml
  roles/nginx/tasks/install.yml
  roles/nginx/templates/iiab.conf.j2
  roles/nginx/templates/mime.types.j2
  vars/default_vars.yml
  vars/local_vars_medical.yml
Labels: enhancement

#2470 No /etc/network/interfaces.d/iiab [fixes RPi 3 B+, allowing WiFi firmware & hostapd to launch reliably on boot]
  roles/network/tasks/rpi_debian.yml
  roles/network/templates/network/dnsmasq-iiab
Labels: bug
