Repository iiab/iiab, pull requests merged in 2020-11, with the labels that each got.

#2604 Clean MongoDB/Sugarizer for Debian 11/Sid & All OS's
  roles/0-init/tasks/main.yml
  roles/mongodb/tasks/enable-or-disable.yml
  roles/mongodb/tasks/install.yml
  roles/mongodb/tasks/main.yml
  roles/sugarizer/tasks/apache.yml
  roles/sugarizer/tasks/enable-or-disable.yml
  roles/sugarizer/tasks/install.yml
  roles/sugarizer/tasks/main.yml
  roles/sugarizer/tasks/main2.yml
  roles/sugarizer/tasks/nginx.yml
  roles/sugarizer/templates/sugarizer.conf.j2.deprecated
  vars/default_vars.yml
Labels: enhancement

#2607 drop udev-reload service
  roles/2-common/tasks/main.yml
  roles/2-common/tasks/udev.yml
  roles/2-common/templates/udev-reload.service
  roles/usb_lib/tasks/install.yml
Labels: enhancement

#2608 Report 1-line-installer's /etc/iiab/pr-list-pulled via iiab-diagnostics, to broaden community testing
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
Labels: enhancement

#2609 Autostart -- Bring up home page on console automatically if it's a Rpi desktop [Ubuntu Desktop 20.10 for RPi not ready for primetime...yet?]
  roles/www_options/tasks/main.yml
Labels: enhancement, help wanted, question

#2615 kiwix-tools 3.1.2 -> 3.1.2-3
  roles/kiwix/defaults/main.yml
Labels: enhancement

#2613 Change mongodb_port from 27018 to more standard 27017, following Sugarizer Server's lead
  roles/mongodb/defaults/main.yml
  roles/mongodb/tasks/install.yml
  roles/mongodb/templates/mongod.conf.j2
  roles/sugarizer/tasks/install.yml
  vars/default_vars.yml
Labels: enhancement

#2617 runrole: auto-prompt to pass 'APP_install: True' to Ansible + properly validate 5 dependencies
  roles/0-init/tasks/validate_vars.yml
  roles/nodejs/tasks/main.yml
  runrole
Labels: enhancement

#2619 iiab-diagnostics: 'iw reg get' 'Detected WiFi country code / legal frequencies'
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
Labels: enhancement

#2621 Bump ansible-base recommendation: 2.10.2 -> 2.10.3
  scripts/ansible
Labels: enhancement

#2622 runrole: explain unknown flag (--reinstall) with more context
  runrole
Labels: enhancement

#2623 runrole: consistent "line(s)" grammar across all 3 cases
  runrole
Labels: enhancement

#2629 Kiwix role: fix counting of /library/zims/content/*.zim + in-line clarifs
  roles/kiwix/tasks/enable-or-disable.yml
  roles/kiwix/tasks/install.yml
  roles/kiwix/templates/library.xml.deprecated
Labels: admin console, bug

#2634 pbx/tasks/install.yml: comment out enforcement of any particular Node.js version
  roles/pbx/tasks/install.yml
Labels: enhancement

#2635 Prepare for Ubuntu 21.04 (Hirsute Hippo)
  roles/network/tasks/restart.yml
  scripts/local_facts.fact
  vars/default_vars.yml
  vars/ubuntu-21.yml
Labels: enhancement

#2637 Gitea 1.12.5 -> 1.12.6 Security & Bug Fixes
  roles/gitea/defaults/main.yml
Labels: enhancement

#2640 kiwix-tools 3.1.2-3 -> 3.1.2-4
  roles/kiwix/defaults/main.yml
Labels: enhancement

#2643 Rename 15-openvpn to 15-openvpn.deprecated
  roles/openvpn/templates/15-openvpn.deprecated
Labels: enhancement

#2644 Clean/Shorten openvpn/templates/announcer.j2
  roles/openvpn/templates/announcer.j2
Labels: enhancement

#2645 temp fix for networkd-dispatcher-2.0.1-1 in 'groovy'
  roles/network/defaults/main.yml
  roles/network/tasks/netplan.yml
Labels: bug

#2648 Emergency Workaround for SELinux / Ansible Collection install fail
  roles/1-prep/tasks/main.yml
  scripts/ansible
Labels: bug

#2649 gitea/tasks/install.yml: timeout: 10 -> 200 (for get_url from dl.gitea.org)
  roles/gitea/tasks/install.yml
Labels: bug

#2651 Emergency/Interim Patch + Experiment to help surface which of the 10 sysctl tweaks are still needed + necessary
  roles/2-common/tasks/main.yml
Labels: question

#2652 ansible.posix collection for 2-common sysctl & js-menu synchronize (formerly needed by 1-prep's selinux)
  roles/2-common/tasks/main.yml
  scripts/ansible
Labels: admin console, bug

#2653 scripts/ansible: try --force-with-deps with Ansible Collections
  scripts/ansible
Labels: enhancement

#2655 (1) create /opt/iiab/iiab/collections.yml (2) move Ansible Collections from /root/.ansible to /usr/share/ansible
  collections.yml
  iiab-install
  scripts/ansible
Labels: enhancement

#2654 WIP: AppArmor works with IIAB on Debian 10/11, so is this now also true on Ubuntu?
  roles/1-prep/tasks/main.yml
Labels: enhancement, question
