Repository iiab/iiab, pull requests merged in 2020-04, with the labels that each got.

#2315 numbers should not have quotes now
  roles/nginx/tasks/install.yml
  roles/www_base/tasks/main.yml
Labels: bug

#2316 Ivan Savov's workaround [so Kolibri exercises work]
  roles/kolibri/templates/kolibri-nginx.conf.j2
  roles/kolibri/templates/kolibri.service.j2
Labels: enhancement

#2319 Gitea 1.11.3 -> 1.11.4
  roles/gitea/defaults/main.yml
Labels: enhancement

#2322 pastebinit bugs: try dpaste.com instead (for iiab-diagnostics command)
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
Labels: bug

#2321 wheel issue [for KA Lite, relating to python2 etc]
  roles/kalite/tasks/install.yml
Labels: bug

#2328 helper script to delete symlink in local_content [when teachers remove their USB sticks/drives]
  roles/usb_lib/tasks/install.yml
  roles/usb_lib/templates/iiab-clean-usb.sh
  roles/usb_lib/templates/usbmount@.service.j2
Labels: bug

#2329 Fix to ensure nginx_high_php_limits are enacted (if nginx_enabled)
  roles/www_options/tasks/main.yml
Labels: bug

#2330 Enhance iiab-diagnostics command
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
Labels: enhancement

#2333 kiwix-tools 3.0.3 -> 3.1.0
  roles/kiwix/defaults/main.yml
Labels: enhancement

#2334 remove any possible file before creating regions symlink
  roles/osm-vector-maps/tasks/install.yml
Labels: bug

#2339 iiab-diagnostics command: redact most passwords (WiFi passwords especially)
  roles/transmission/tasks/main.yml
  scripts/iiab-diagnostics
Labels: enhancement

#2340 Recommend Ansible 2.9.7+, Mandate Ansible 2.8.11+
  iiab-install
  scripts/ansible
  scripts/ansible-2.8.x
  scripts/ansible-2.9.x
Labels: enhancement

#2341 https://bugs.launchpad.net/ubuntu/+bug/1872897 [Bluetooth on Ubuntu]
  roles/1-prep/tasks/raspberry_pi.yml
Labels: bug

#2342 google is almost an essential url, so do not divert it
  roles/captiveportal/templates/checkurls
Labels: enhancement

#2343 Comment out both kolibri.service timeout settings
  roles/kolibri/templates/kolibri.service.j2
Labels: enhancement

#2344 kiwix-tools 3.1.0 -> 3.1.0-1
  roles/kiwix/defaults/main.yml
Labels: enhancement

#2345 Med vars & php-stem error handling
  roles/nginx/tasks/install.yml
  roles/www_base/tasks/main.yml
  vars/local_vars_medical.yml
Labels: enhancement

#2350 centralize map catalog for use by osm and admin console
  roles/osm-vector-maps/tasks/install.yml
Labels: enhancement

#2351 rm *.deprecated (24 files) [& restore iiab-support.yml for iiab-support command]
  install-support.yml
  roles/awstats/templates/cron.d.awstats.deprecated
  roles/httpd/files/osm.conf.deprecated
  roles/httpd/templates/httpd.j2.deprecated
  roles/httpd/templates/iiab-http.deprecated
  roles/httpd/templates/iiab-http.j2.deprecated
  roles/httpd/templates/iiab-info.conf.j2.deprecated
  roles/httpd/templates/php.ini.j2.deprecated
  roles/kalite/tasks/assessment.yml.deprecated
  roles/kalite/templates/settings.py.j2.deprecated
  roles/kiwix/templates/iiab-make-kiwix-lib.py.deprecated
  roles/network/tasks/create_ifcfg.yml.deprecated
  roles/network/tasks/hosts.yml.deprecated
  roles/network/templates/network/iiab.j2.deprecated
  roles/nginx/tasks/disable.yml.deprecated
  roles/nginx/tasks/only_nginx.yml.deprecated
  roles/nginx/tasks/uses_apache.yml.deprecated
  roles/nginx/templates/dokuwiki-nginx.conf.deprecated
  roles/nginx/templates/mediawiki-nginx.conf.j2.deprecated
  roles/nginx/templates/wordpress-nginx.conf.deprecated
  roles/openvpn/templates/iiab-handle.j2.deprecated
  roles/openvpn/templates/start.j2.deprecated
  roles/openvpn/templates/up_wan.deprecated
  roles/sugarizer/templates/sugarizer.ini.j2.deprecated
  roles/sugarizer/templates/sugarizer.js.deprecated
Labels: enhancement

#2353 /usr/bin/iiab-diagnostics: redact most all passwords, if line does not begin with '#'
  scripts/iiab-diagnostics
Labels: enhancement

#2356 Softcoding kolibri-nginx.conf
  roles/kolibri/templates/kolibri-nginx.conf.j2
Labels: enhancement

#2359 kiwix-tools 3.1.0-1 -> 3.1.0-2
  roles/kiwix/defaults/main.yml
Labels: enhancement

#2357 Make http://box/js-menu publicly browsable [except where code/security is a risk]
  roles/nginx/templates/iiab.conf.j2
Labels: admin console, enhancement, question

#2365 changed Pi guide download location
  roles/www_base/templates/iiab-refresh-wiki-docs.sh
Labels: enhancement

#2369 vnStat workaround for #2367
  roles/vnstat/tasks/main.yml
Labels: admin console, bug

#2368 move pylib.yml to stage 4
  roles/2-common/tasks/main.yml
  roles/4-server-options/tasks/main.yml
  roles/pylibs/tasks/main.yml
  roles/pylibs/templates/iiab_const.py.j2
  roles/pylibs/templates/iiab_env.py.j2
  roles/pylibs/templates/iiab_lib.py
Labels: enhancement

#2349 Php 386 [& php-stem with PHP 7.4+ prep?]
  roles/nginx/tasks/install.yml
  roles/www_base/tasks/main.yml
  roles/www_base/tasks/php-stem.yml
Labels: enhancement, question

#2373 Fix PR #2349 stem / WikiHow search: move www_base below nginx (in 3-base-server)
  roles/3-base-server/tasks/main.yml
Labels: bug

#2374 runrole - emit 'Usage' when --reinstall is in the wrong position
  runrole
Labels: enhancement

#2376 Fix path to Lokole repository
  roles/lokole/README.rst
  roles/lokole/tasks/install.yml
Labels: bug

#2378 Cleaner roles: Calibre (its conversion tool can supplement Calibre-Web) & KA Lite
  roles/calibre/tasks/enable.yml
  roles/calibre/tasks/install.yml
  roles/calibre/tasks/main.yml
  roles/kalite/tasks/enable.yml.unused
  roles/kalite/tasks/install-f18.yml.unused
  roles/kalite/tasks/install-old.yml.unused
  roles/kalite/tasks/main.yml
  roles/kalite/tasks/setup-f18.yml.unused
  roles/kalite/tasks/setup.yml.unused
  roles/nginx/README.md
  scripts/calibre-install-latest-rpi-plus.sh.unused
  scripts/calibre-install-latest.sh.unused
  scripts/calibre-install-packages.sh.unusued
  scripts/calibre-install-pinned-rpi.sh.unused
  scripts/calibre-install-unstable.sh.unused
  vars/centos-7.yml
  vars/debian-10.yml
  vars/debian-8.yml
  vars/debian-9.yml
  vars/fedora-18.yml
  vars/fedora-22.yml
  vars/raspbian-10.yml
  vars/raspbian-8.yml
  vars/raspbian-9.yml
  vars/ubuntu-16.yml
  vars/ubuntu-17.yml
  vars/ubuntu-18.yml
  vars/ubuntu-19.yml
  vars/ubuntu-20.yml
Labels: enhancement
