Repository iiab/iiab, pull requests merged in 2021-08, with the labels that each got.

#2893 Modularize and explain Stage 1 (1-prep) of IIAB install
  roles/1-prep/README.rst
  roles/1-prep/tasks/hardware.yml
  roles/1-prep/tasks/main.yml
  roles/1-prep/tasks/raspberry_pi.yml
  roles/1-prep/tasks/ubermix.yml
  roles/1-prep/tasks/uuid.yml
  roles/2-common/tasks/main.yml
  roles/2-common/tasks/packages.yml
  roles/4-server-options/tasks/main.yml
Labels: enhancement

#2894 jupyterhub/tasks/enable-or-disable.yml: Cleaner 'daemon_reload: yes'
  roles/jupyterhub/tasks/enable-or-disable.yml
Labels: enhancement

#2896 pbx/defaults/main.yml: Asterisk 16.x -> 18.x
  roles/pbx/defaults/main.yml
Labels: enhancement

#2895 Cleanup of roles/openvpn and roles/mysql
  roles/2-common/tasks/packages.yml
  roles/mysql/tasks/centos.yml.unused
  roles/mysql/tasks/fedora.yml.unused
  roles/mysql/tasks/install.yml
  roles/openvpn/tasks/install.yml
Labels: enhancement

#2900 Explain where/why sudo gets installed
  roles/2-common/tasks/packages.yml
  roles/iiab-admin/tasks/sudo-prereqs.yml
  roles/openvpn/tasks/install.yml
Labels: enhancement

#2898 Update roles/pbx/README.rst, announcing Asterisk 16.x -> 18.x but also warning about PHP 7.4 etc! [Announce transition to FreePBX 16 Beta is now underway, moving away from PHP 7.3]
  roles/pbx/README.rst
Labels: enhancement, question

#2901 Lint pbx/tasks/asterisk.yml to a common baseline, as Apache extrication/isolation work continues
  roles/pbx/tasks/asterisk.yml
Labels: enhancement

#2902 pbx/tasks/asterisk.yml: Experiment w/o aptitude
  roles/pbx/tasks/asterisk.yml
Labels: enhancement

#2903 Tighten up Asterisk deps + Remember to Enable/Disable Asterisk + Move PBX from Stage 6 to 9
  roles/6-generic-apps/tasks/main.yml
  roles/9-local-addons/tasks/main.yml
  roles/pbx/tasks/asterisk.yml
  roles/pbx/tasks/asterisk_dependencies.yml.unused
  roles/pbx/tasks/enable-or-disable.yml
  roles/pbx/tasks/freepbx_enable.yml
  roles/pbx/tasks/install.yml
  roles/pbx/tasks/main.yml
Labels: enhancement

#2906 Spring Cleaning: pbx, nodejs, openvpn, local_vars, default_vars.yml
  roles/nodejs/tasks/install.yml
  roles/openvpn/tasks/install.yml
  roles/pbx/tasks/asterisk.yml
  roles/pbx/tasks/freepbx.yml
  roles/pbx/templates/71-freepbx-framework.patch.unused
  roles/pbx/templates/pbx.patch.unused
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2907 Update pbx/tasks/chan_dongle.yml explanations
  roles/pbx/tasks/chan_dongle.yml
Labels: enhancement

#2909 local_vars & default_vars.yml: Move roles/iiab-admin explanation down a bit
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2908 Does something like 'RestartSec=3' in /etc/systemd/system/freepbx.service help Asterisk start reliably? (WIP)
  roles/pbx/tasks/enable-or-disable.yml
  roles/pbx/templates/freepbx.service.j2
Labels: enhancement, question

#2885 Move packages 'python3-*' & 'virtualenv' (for Python 2) from scripts/ansible to roles that need them, e.g. {mysql, postgresql, munin, kalite}
  roles/2-common/tasks/packages.yml
  roles/calibre-web/tasks/install.yml
  roles/jupyterhub/tasks/install.yml
  roles/kalite/tasks/install.yml
  roles/munin/tasks/install.yml
  roles/mysql/tasks/install.yml
  roles/postgresql/tasks/install.yml
  scripts/ansible
  scripts/ansible.md.unused
Labels: enhancement, question

#2910 Revert 'RestartSec=3' in /etc/systemd/system/freepbx.service
  roles/pbx/tasks/enable-or-disable.yml
  roles/pbx/templates/freepbx.service.j2
Labels: enhancement

#2912 little heavy handed but it works [workaround for FreePBX's "Unable to run Pre-Asterisk hooks, because Asterisk is already running"]
  roles/pbx/tasks/freepbx.yml
Labels: enhancement

#2913 roles/pbx magic [overall cleanup, moving us forward with Asterisk + FreePBX workaround PR #2912]
  roles/pbx/defaults/main.yml
  roles/pbx/tasks/asterisk.yml
  roles/pbx/tasks/enable-or-disable.yml
  roles/pbx/tasks/freepbx.yml
  roles/pbx/tasks/install.yml
  roles/pbx/templates/freepbx.service
  roles/pbx/templates/odbc.ini
Labels: enhancement

#2915 Run 'systemctl restart freepbx" twice, so http://box:83/freepbx works right away on install, prior to reboot
  roles/pbx/tasks/asterisk.yml
  roles/pbx/tasks/asterisk_dependencies.yml.unused
  roles/pbx/tasks/freepbx.yml
Labels: enhancement

#2916 Experiment: FreePBX on NGINX -- anybody can explore this, using flag 'pbx_try_nginx: True' in /etc/iiab/local_vars.yml
  roles/pbx/defaults/main.yml
  roles/pbx/tasks/asterisk.yml
  roles/pbx/tasks/enable-or-disable.yml
  roles/pbx/tasks/freepbx.yml
  roles/pbx/tasks/freepbx_dependencies.yml
  roles/pbx/tasks/install.yml
  roles/pbx/templates/freepbx-nginx.conf.j2
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2917 Patch pbx/tasks/install.yml & freepbx.yml syntax error 'block:' -> '- block:'
  roles/pbx/tasks/freepbx.yml
  roles/pbx/tasks/install.yml
Labels: bug

#2892 Refine roles/jupyterhub/README.md
  roles/jupyterhub/README.md
  roles/jupyterhub/templates/jupyterhub_config.py
Labels: enhancement

#2920 Install apache2 + its 'rewrite' mod in freepbx_dependencies.yml -- so roles/httpd can be phased out
  roles/nginx/tasks/install.yml
  roles/pbx/tasks/asterisk.yml
  roles/pbx/tasks/freepbx.yml
  roles/pbx/tasks/freepbx_dependencies.yml
  roles/pbx/tasks/install.yml
Labels: enhancement

#2922 freepbx.yml: 'ignore_errors: yes' for 'killall -9 safe_asterisk'
  roles/pbx/tasks/freepbx.yml
Labels: bug

#2850 WIP: Extricate IIAB from 2 web servers complexity
  roles/0-DEPRECATED-ROLES/elgg/README.rst
  roles/0-DEPRECATED-ROLES/elgg/defaults/main.yml
  roles/0-DEPRECATED-ROLES/elgg/tasks/apache.yml.unused
  roles/0-DEPRECATED-ROLES/elgg/tasks/install.yml
  roles/0-DEPRECATED-ROLES/elgg/tasks/main.yml
  roles/0-DEPRECATED-ROLES/elgg/tasks/nginx.yml
  roles/0-DEPRECATED-ROLES/elgg/tasks/setup.yml
  roles/0-DEPRECATED-ROLES/elgg/templates/elgg-nginx.conf.j2
  roles/0-DEPRECATED-ROLES/elgg/templates/elgg.conf.unused
  roles/0-DEPRECATED-ROLES/elgg/templates/elggdb.sql.j2
  roles/0-DEPRECATED-ROLES/elgg/templates/settings.php.j2
  roles/0-DEPRECATED-ROLES/httpd/README.md
  roles/0-DEPRECATED-ROLES/httpd/defaults/main.yml
  roles/0-DEPRECATED-ROLES/httpd/tasks/homepage.yml
  roles/0-DEPRECATED-ROLES/httpd/tasks/install.yml
  roles/0-DEPRECATED-ROLES/httpd/tasks/main.yml
  roles/0-DEPRECATED-ROLES/httpd/templates/010-iiab.conf.j2
  roles/0-DEPRECATED-ROLES/httpd/templates/iiab-homepage.conf
  roles/0-DEPRECATED-ROLES/httpd/templates/proxy_ajp.conf.j2
  roles/0-init/tasks/validate_vars.yml
  roles/6-generic-apps/tasks/main.yml
  roles/calibre/tasks/install.yml
  roles/calibre/templates/calibre.conf.unused
  roles/internetarchive/tasks/apache.yml.unused
  roles/internetarchive/tasks/install.yml
  roles/internetarchive/tasks/main.yml
  roles/internetarchive/templates/internetarchive.conf.unused
  roles/kalite/tasks/install.yml
  roles/nginx/README.md
  roles/nginx/tasks/enable-or-disable.yml
  roles/nginx/tasks/install.yml
  roles/nginx/templates/apache-ports.conf
  roles/nginx/templates/stock-apache-ports.conf.unused
  roles/phpmyadmin/tasks/enable-or-disable.yml
  roles/phpmyadmin/tasks/install.yml
  roles/phpmyadmin/tasks/main.yml
  roles/phpmyadmin/templates/phpmyadmin.j2.unused
  roles/usb_lib/tasks/apache.yml.unused
  roles/usb_lib/tasks/install.yml
  roles/usb_lib/tasks/main.yml
  tests/test.yml
  unmaintained-roles.txt
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
  vars/local_vars_olpc.yml.unused
Labels: enhancement, question

#2929 Cleaner filesystem when Apache is not installed, using roles/pbx/tasks/apache.yml + local_vars_unittest.yml
  roles/nginx/tasks/install.yml
  roles/pbx/tasks/apache.yml
  roles/pbx/tasks/asterisk.yml
  roles/pbx/tasks/freepbx.yml
  roles/pbx/tasks/freepbx_dependencies.yml.unused
  roles/pbx/tasks/install.yml
  roles/pbx/templates/ports.conf
  vars/local_vars_unittest.yml
Labels: enhancement

#2927 cleaner filesystem when apache is not installed
  roles/nginx/tasks/install.yml
  roles/pbx/tasks/freepbx_dependencies.yml
Labels: enhancement

#2931 WIP: Contextualize @jvonau's /etc/php/7.4/fpm/pool.d/asterisk.conf (PR #2930) for FreePBX on NGINX
  roles/nginx/templates/server.conf.j2
  roles/pbx/tasks/enable-or-disable.yml
  roles/pbx/tasks/freepbx.yml
  roles/pbx/templates/asterisk.conf
  roles/pbx/templates/asterisk.conf.diff
  roles/pbx/templates/asterisk.conf.patch
  roles/pbx/templates/freepbx-nginx.conf.j2
  roles/pbx/templates/freepbx.service
Labels: enhancement

#2930 Fpm asterisk
  roles/pbx/tasks/enable-or-disable.yml
  roles/pbx/tasks/freepbx.yml
  roles/pbx/templates/asterisk.conf
  roles/pbx/templates/freepbx-nginx.conf.j2
  roles/pbx/templates/freepbx.service
Labels: enhancement, question

#2932 Apache service
  roles/nginx/tasks/install.yml
  roles/pbx/tasks/enable-or-disable.yml
Labels: enhancement

#2936 The OSs have finally caught up - the default timeout value is 900 seconds now
  roles/mysql/tasks/install.yml
Labels: enhancement

#2938 freepbx.yml: Run 'fwconsole ma upgradeall' on installed FreePBX modules [e.g. 16 default modules, of about 70 total modules available]
  roles/pbx/tasks/freepbx.yml
Labels: enhancement

#2940 freepbx.yml: Ansible comment error + typo
  roles/pbx/tasks/freepbx.yml
Labels: bug

#2941 @lemueldsouza's new pbx/README.adoc + 8 screenshots, with some quick editing
  roles/pbx/README.adoc
  roles/pbx/README.rst
  roles/pbx/README.rst.unused
  roles/pbx/files/add_extn_01_top.jpg
  roles/pbx/files/add_extn_02.jpg
  roles/pbx/files/advanced_settings.jpg
  roles/pbx/files/asterisk_sip_settings.jpg
  roles/pbx/files/linphone_connected.jpg
  roles/pbx/files/linphone_setup.jpg
  roles/pbx/files/password_change.jpg
  roles/pbx/files/pwdless_login.jpg
Labels: enhancement

#2905 Update README.rst [roles/pbx for Asterisk & FreePBX]
  roles/pbx/README.adoc
  roles/pbx/README.rst
  roles/pbx/files/add_extn_01.jpg
  roles/pbx/files/add_extn_02.jpg
  roles/pbx/files/advanced_settings.jpg
  roles/pbx/files/asterisk_sip_settings.jpg
  roles/pbx/files/linphone_connected.jpg
  roles/pbx/files/linphone_setup.jpg
  roles/pbx/files/password_change.jpg
  roles/pbx/files/pwdless_login.jpg
Labels: enhancement, help wanted, good 1st issue

#2944 Contextualize {AzuraCast, MediaWiki, Kolibri, AWStats, Monit, Munin, vnStat} in local_vars.yml / default_vars.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
  vars/local_vars_unittest.yml
Labels: enhancement

#2945 Fix outdated explanations/order in Stages 3 & 4 of local_vars.yml, default_vars.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
  vars/local_vars_unittest.yml
Labels: enhancement

#2947 Clarify that dnsmasq is installed in Stage 1 not Stage 4
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
  vars/local_vars_unittest.yml
Labels: enhancement

#2950 @jvonau's ODBC compiling for FreePBX CDR + linting, explanations & small mods
  roles/pbx/defaults/main.yml
  roles/pbx/tasks/asterisk.yml
  roles/pbx/tasks/freepbx.yml
  roles/pbx/templates/cdr_mysql.conf.j2
  roles/pbx/templates/odbc.ini
  roles/pbx/templates/odbc.ini.j2
  roles/pbx/templates/odbcinst.ini
  scripts/mk-odbc-connector
Labels: enhancement

#2942 Fix Freepbx CDR backend
  roles/pbx/tasks/freepbx.yml
  roles/pbx/templates/cdr_mysql.conf
  roles/pbx/templates/odbcinst.ini
  scripts/mk-odbc-connector
Labels: enhancement

#2948 Deprecate DansGuardian & WonderShaper + overhaul Squid -- in future let's consider fortifying, removing or replacing Squid (some prefer Varnish as a proxy/cache)
  roles/0-init/defaults/main.yml
  roles/0-init/tasks/validate_vars.yml
  roles/4-server-options/tasks/main.yml
  roles/network/defaults/main.yml
  roles/network/tasks/computed_network.yml
  roles/network/tasks/computed_services.yml
  roles/network/tasks/dansguardian.yml.unused
  roles/network/tasks/enable_services.yml
  roles/network/tasks/main.yml
  roles/network/tasks/restart.yml
  roles/network/tasks/squid.yml
  roles/network/tasks/wondershaper.yml.unused
  roles/network/templates/squid/allow_dst_domains
  roles/network/templates/squid/allow_url_regexs
  roles/network/templates/squid/allowregex.rules.unused
  roles/network/templates/squid/dansguardian.conf.centos.j2.unused
  roles/network/templates/squid/dansguardian.conf.debian.j2.unused
  roles/network/templates/squid/dansguardian.conf.j2.unused
  roles/network/templates/squid/denyregex.rules.unused
  roles/network/templates/squid/dstaddress.rules.unused
  roles/network/templates/squid/iiab-httpcache.j2.unused
  roles/network/templates/squid/sites.whitelist.txt.unused
  roles/network/templates/squid/squid-iiab.conf.j2.unused
  roles/network/templates/squid/squid.conf.j2
  roles/network/templates/squid/squid.sysconfig.unused
  roles/network/templates/wondershaper.unused/wondershaper.conf
  roles/network/templates/wondershaper.unused/wondershaper.j2
  roles/network/templates/wondershaper.unused/wondershaper.service
  tests/test.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
  vars/local_vars_unittest.yml
Labels: enhancement

#2952 asterisk-test-script
  roles/pbx/templates/asterisk_test
  roles/pbx/templates/extensions_custom.conf
  roles/pbx/templates/pjsip_custom.conf
Labels: enhancement

#2955 Add details about asterisk_test to pbx/README.adoc
  roles/pbx/README.adoc
Labels: enhancement

#2954 FreePBX: side-by-side testing of Apache & NGINX + easy './runrole pbx' mods, using a more dynamic iiab-gen-iptables
  iiab-support
  roles/0-init/defaults/main.yml
  roles/0-init/tasks/network.yml
  roles/2-common/tasks/network.yml
  roles/2-common/templates/iptables.unused
  roles/firmware/templates/iiab-check-firmware
  roles/network/templates/gateway/iiab-gen-iptables
  roles/pbx/README.adoc
  roles/pbx/defaults/main.yml
  roles/pbx/tasks/asterisk.yml
  roles/pbx/tasks/enable-or-disable.yml
  roles/pbx/tasks/freepbx.yml
  roles/pbx/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
  vars/local_vars_unittest.yml
Labels: enhancement

#2951 Freepbx - dual mode - for side by side testing [of Apache & NGINX]
  roles/pbx/defaults/main.yml
  roles/pbx/tasks/enable-or-disable.yml
  roles/pbx/tasks/freepbx.yml
  roles/pbx/tasks/main.yml
Labels: enhancement

#2956 Released: ansible-core 2.11.4, ansible-base 2.10.13, ansible 2.9.25
  scripts/ansible
Labels: enhancement

#2957 Major cleanup of roles/openvpn, openvpn_handle SSOT
  install-support.yml
  roles/firmware/templates/iiab-check-firmware
  roles/network/templates/gateway/iiab-gen-iptables
  roles/openvpn/tasks/install.yml
  roles/openvpn/tasks/main.yml
  roles/openvpn/templates/15-openvpn.unused
  roles/openvpn/templates/announcer
  roles/openvpn/templates/announcer.j2
  roles/openvpn/templates/iiab-remote-off
  roles/openvpn/templates/iiab-support
  roles/openvpn/templates/iiab-support.older
  roles/openvpn/templates/openvpn_handle.j2.unused
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
  test.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
  vars/local_vars_unittest.yml
Labels: enhancement, admin console

#2874 Gitea 1.15 is imminent ⁠— basic testing with IIAB would be great!
  roles/gitea/defaults/main.yml
Labels: enhancement, good 1st issue

#2923 Update roles/samba/README.rst and review IIAB's /etc/samba/smb.conf
  roles/samba/README.rst
Labels: enhancement, question

#2962 default_vars.yml & local_vars.yml: Caution that 'squid_enabled: True' acts like 'iiab_gateway_enabled: True' (but only for Port 80)
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
  vars/local_vars_unittest.yml
Labels: enhancement

#2963 Squid: Contextualize /etc/squid/squid.conf + allowlists for new implementers (HTTP/80 whitelists) + optimize its install in Stage 4-server-options
  roles/4-server-options/tasks/main.yml
  roles/network/tasks/squid.yml
  roles/network/templates/squid/allow_dst_domains
  roles/network/templates/squid/allow_url_regexs
Labels: enhancement

#2964 Explain how to turn off overzealous WiFi firmware warnings
  roles/firmware/templates/iiab-check-firmware
  roles/firmware/templates/iiab-firmware-warn.sh
Labels: enhancement

#2966 Friendlier /usr/bin/iiab-support command: make OpenVPN tun0 IP address visible upfront
  roles/openvpn/templates/iiab-support
Labels: enhancement

#2970 Check passwds hashed w/ 'yescrypt' etc too, in /etc/shadow -- /etc/profile.d/sshpwd-profile-iiab.sh and /etc/xdg/lxsession/LXDE-pi/sshpwd-lxde-iiab.sh
  roles/iiab-admin/tasks/pwd-warnings.yml
  roles/iiab-admin/templates/sshpwd-lxde-iiab.sh.j2
  roles/iiab-admin/templates/sshpwd-profile-iiab.sh.j2
Labels: bug

#2972 Remove 'when: internet_available' from 25 files [preserving it in network/tasks/netplan.yml + www_options/tasks/main.yml for now]
  roles/1-prep/tasks/hardware.yml
  roles/azuracast/tasks/install.yml
  roles/calibre-web/tasks/install.yml
  roles/calibre/tasks/create-db.yml
  roles/calibre/tasks/debs.yml
  roles/calibre/tasks/py-installer.yml
  roles/gitea/tasks/install.yml
  roles/internetarchive/tasks/install.yml
  roles/internetarchive/tasks/main.yml
  roles/jupyterhub/tasks/install.yml
  roles/kalite/tasks/install.yml
  roles/kiwix/tasks/install.yml
  roles/kiwix/tasks/kiwix-apk.yml
  roles/kolibri/tasks/install.yml
  roles/lokole/tasks/install.yml
  roles/mediawiki/tasks/install.yml
  roles/network/tasks/netplan.yml
  roles/nextcloud/tasks/install.yml
  roles/nodered/tasks/install.yml
  roles/pbx/tasks/asterisk.yml
  roles/pbx/tasks/chan_dongle.yml
  roles/pbx/tasks/freepbx.yml
  roles/phpmyadmin/tasks/install.yml
  roles/sugarizer/tasks/install.yml
  roles/wordpress/tasks/install.yml
  roles/yarn/tasks/install.yml
Labels: enhancement
