Repository iiab/iiab, pull requests merged in 2021-07, with the labels that each got.

#2841 WIP: Moodle on NGINX not Apache
  roles/moodle/defaults/main.yml
  roles/moodle/tasks/apache.yml.unused
  roles/moodle/tasks/install.yml
  roles/moodle/tasks/main.yml
  roles/moodle/tasks/mathjax.yml
  roles/moodle/templates/022-moodle.jv.unused
  roles/moodle/templates/moodle-nginx.conf.j2
  roles/moodle/templates/moodle-nginx.conf.j2.native
  roles/moodle/templates/moodle-nginx.conf.j2.unused
  roles/moodle/templates/moodle_installer
Labels: enhancement

#2843 Node-RED on NGINX not Apache
  roles/nginx/README.md
  roles/nodered/tasks/install.yml
  roles/nodered/tasks/main.yml
  roles/nodered/templates/nodered-nginx.conf.j2
  roles/nodered/templates/nodered.conf.j2.unused
Labels: enhancement

#2840 Nodered no apache
  roles/nginx/README.md
  roles/nodered/tasks/install.yml
  roles/nodered/tasks/main.yml
  roles/nodered/templates/nodered-nginx.conf.j2
Labels: enhancement, help wanted

#2794 Lokole with less Apache
  roles/lokole/tasks/apache.yml.unused
  roles/lokole/tasks/install.yml
  roles/lokole/tasks/main.yml
  roles/nginx/README.md
Labels: enhancement

#2845 Spring Cleaning for Nextcloud 22+
  roles/nextcloud/tasks/F18.yml.unused
  roles/nextcloud/tasks/apache.yml.unused
  roles/nextcloud/tasks/install.yml
  roles/nextcloud/tasks/main.yml
  roles/nextcloud/tasks/setup.yml
  roles/nextcloud/templates/nextcloud-nginx.conf.j2
  roles/nextcloud/templates/nextcloud.conf.j2.unused
  roles/nginx/README.md
  roles/nginx/templates/nginx.conf.j2
Labels: enhancement

#2846 Clean Kolibri role for NGINX not Apache
  roles/kolibri/tasks/apache.yml.unused
  roles/kolibri/tasks/install.yml
  roles/kolibri/tasks/main.yml
  roles/kolibri/templates/kolibri.conf.j2.unused
  roles/nginx/README.md
Labels: enhancement

#2847 MediaWiki + Sugarizer + WordPress w/o Apache
  roles/mediawiki/tasks/apache.yml.unused
  roles/mediawiki/tasks/install.yml
  roles/mediawiki/tasks/main.yml
  roles/mediawiki/templates/mediawiki.conf.j2.unused
  roles/nginx/README.md
  roles/sugarizer/tasks/enable-or-disable.yml
  roles/sugarizer/tasks/install.yml
  roles/sugarizer/tasks/main2.yml
  roles/sugarizer/templates/sugarizer-nginx.conf
  roles/sugarizer/templates/sugarizer-nginx.conf.j2
  roles/sugarizer/templates/sugarizer.conf.j2.unused
  roles/wordpress/tasks/apache.yml.unused
  roles/wordpress/tasks/install.yml
  roles/wordpress/tasks/main.yml
  roles/wordpress/templates/wordpress.conf.j2.unused
Labels: enhancement

#2848 sugarizer/tasks/install.yml: Clarify git clone d/l sizes
  roles/sugarizer/tasks/install.yml
Labels: enhancement

#2849 AWStats + Calibre-Web + Gitea + Kiwix + Munix w/o Apache
  roles/awstats/tasks/apache.yml.unused
  roles/awstats/tasks/install.yml
  roles/awstats/tasks/main.yml
  roles/awstats/templates/apache-awstats.conf.unused
  roles/awstats/templates/apache.conf.unused
  roles/awstats/templates/logrotate.d.apache2.unused
  roles/calibre-web/tasks/apache.yml.unused
  roles/calibre-web/tasks/install.yml
  roles/calibre-web/tasks/main.yml
  roles/calibre-web/templates/calibre-web.conf.j2.unused
  roles/gitea/defaults/main.yml
  roles/gitea/tasks/apache.yml.unused
  roles/gitea/tasks/install.yml
  roles/gitea/tasks/main.yml
  roles/gitea/templates/gitea.conf.j2.unused
  roles/kiwix/tasks/apache.yml.unused
  roles/kiwix/tasks/enable-or-disable.yml
  roles/kiwix/tasks/install.yml
  roles/kiwix/templates/kiwix.conf.j2.unused
  roles/munin/tasks/apache.yml.unused
  roles/munin/tasks/install.yml
  roles/munin/tasks/main.yml
  roles/munin/templates/munin24.conf.j2.unused
  roles/nginx/README.md
Labels: enhancement

#2858 CUPS Printing: Spring Cleaning + NGINX fix for URL's like http://box/print + hardening of URL's like http://box/print/admin
  roles/cups/README.md
  roles/cups/tasks/enable-or-disable.yml
  roles/cups/tasks/install.yml
  roles/cups/tasks/main.yml
  roles/cups/tasks/nginx.yml
  roles/cups/templates/cups.conf
  roles/cups/templates/cups.conf.j2
  roles/cups/templates/cupsd.conf.j2.unused
  roles/gitea/templates/gitea-nginx.conf.j2
  roles/kiwix/templates/kiwix-nginx.conf.j2
  roles/kolibri/templates/kolibri-nginx.conf.j2
  roles/lokole/templates/lokole-nginx.conf.j2
  roles/mediawiki/templates/mediawiki-nginx.conf.j2
  roles/munin/templates/munin24-nginx.conf.j2
  roles/nginx/README.md
  roles/nginx/templates/iiab.conf.j2
  roles/osm-vector-maps/templates/osm-vector-maps-nginx.conf.j2
  roles/sugarizer/templates/sugarizer-nginx.conf.j2
  roles/wordpress/templates/wordpress-nginx.conf.j2
  test.yml
Labels: enhancement

#2775 Reverse Proxy Cups with Nginx
  roles/cups/tasks/nginx.yml
  roles/cups/templates/cups.conf
  roles/cups/templates/cupsd.conf
Labels: enhancement

#2861 Update freepbx.yml
  roles/pbx/tasks/freepbx.yml
Labels: bug

#2837 Enable php-stem installation for armv6l machine type
  roles/www_base/tasks/php-stem.yml
Labels: bug

#2865 [NEEDSFIX] Azuracast fix
  roles/azuracast/defaults/main.yml
  roles/azuracast/tasks/install.yml
  roles/azuracast/templates/docker-compose.override.yml.j2
Labels: bug

#2867 Clean kalite/install.yml, including softcode of venv
  roles/kalite/tasks/install.yml
Labels: enhancement

#2869 Softcode Moodle & poppler-utils pdftoppm to convert PDF to PNG
  roles/moodle/defaults/main.yml
  roles/moodle/tasks/install.yml
  roles/moodle/templates/moodle_installer
Labels: enhancement

#2870 dhcpcd.conf.j2: denyinterfaces IF {{ iiab_wireless_lan_iface }} defined — for Raspberry Pi OS on PC/Mac
  roles/network/templates/network/dhcpcd.conf.j2
Labels: enhancement

#2871 rpi_debian.yml: clone-wifi when: discovered_wireless_iface != "none" — for RaspiOS on PC
  roles/network/tasks/rpi_debian.yml
Labels: enhancement

#2872 Clarify 5 roles that use Node.js
  roles/nodejs/defaults/main.yml
  vars/default_vars.yml
Labels: enhancement

#2877 Update 4-server-options/tasks/main.yml explanations
  roles/4-server-options/tasks/main.yml
Labels: enhancement

#2878 2-common: Annotate 6 lesser-maintained sections
  roles/2-common/tasks/main.yml
Labels: enhancement

#2880 iiab-diagnostics: dpkg --print-architecture && dpkg --print-foreign-acrhitectures
  scripts/iiab-diagnostics
Labels: enhancement

#2882 Explain networking packages in 1-prep and 2-common -- and experimentally deprecate exfat-fuse, exfat-utils, ntfs-3g -- mandating 5.4+ kernels
  roles/1-prep/tasks/raspberry_pi.yml
  roles/2-common/tasks/network.yml
  roles/2-common/tasks/packages.yml
Labels: enhancement, question

#2881 Experimentally remove /usr/sbin from non-root users' $PATH, per distro usability/security norms [i.e. do not install /etc/profile.d/zzz_iiab.sh]
  roles/1-prep/tasks/raspberry_pi.yml
  roles/2-common/tasks/main.yml
  roles/2-common/templates/zzz_iiab.sh.unused
  roles/captiveportal/tasks/enable-or-disable.yml
  roles/captiveportal/tasks/install.yml
  roles/firmware/tasks/install.yml
  roles/firmware/templates/iiab-check-firmware.service
  roles/firmware/templates/iiab-firmware-warn.sh
  roles/iiab-admin/tasks/admin-user.yml
  roles/network/tasks/hostapd.yml
  roles/network/tasks/rpi_debian.yml
  roles/network/tasks/sysd-netd-debian.yml
  roles/network/templates/hostapd/README.ap0
  roles/network/templates/hostapd/hostapd.service.j2
  roles/network/templates/hostapd/iiab-clone-wifi.service.j2
  roles/network/templates/hostapd/iiab-test-wifi.j2
  roles/network/templates/hostapd/iiab-wifi-test.service.j2
  roles/network/templates/network/iiab-hotspot-off
  roles/network/templates/network/iiab-hotspot-on
  roles/usb_lib/tasks/install.yml
Labels: enhancement, question

#2883 Modernize 2-common
  roles/0-init/README.rst
  roles/1-prep/README.rst
  roles/2-common/README.rst
  roles/2-common/tasks/centos.yml.unused
  roles/2-common/tasks/fedora.yml.unused
  roles/2-common/tasks/main.yml
  roles/2-common/tasks/net_mods.yml.unused
  roles/2-common/tasks/network.yml
  roles/2-common/tasks/prep.yml.unused
  roles/2-common/tasks/xo.yml.unused
  roles/2-common/tasks/yum-historical.yml.unused
  roles/2-common/templates/ansible.repo.unused
  roles/2-common/templates/iiab-centos.repo.unused
  roles/2-common/templates/iiab-extra.repo.unused
  roles/2-common/templates/iiab-testing.repo.unused
  roles/2-common/templates/iptables-config.unused
  roles/2-common/templates/li.nux.ro.repo.unused
  roles/2-common/templates/local.repo.unused
  roles/2-common/templates/rpmfusion-free-updates.repo.unused
  roles/3-base-server/README.rst
  roles/4-server-options/README.rst
  roles/5-xo-services/README.rst
Labels: enhancement

#2884 roles/1-prep/tasks/raspberry_pi.yml touchup
  roles/1-prep/tasks/raspberry_pi.yml
Labels: enhancement

#2886 Make IIAB's bootstrapping role (0-init) more understandable
  roles/0-init/tasks/create_iiab_ini.yml
  roles/0-init/tasks/first_run.yml
  roles/0-init/tasks/hostname.yml
  roles/0-init/tasks/main.yml
  roles/0-init/tasks/network.yml
  roles/0-init/tasks/tz.yml
  roles/1-prep/tasks/main.yml
  roles/1-prep/tasks/raspberry_pi.yml
  roles/3-base-server/tasks/main.yml
  roles/5-xo-services/tasks/main.yml
  roles/6-generic-apps/tasks/main.yml
  roles/7-edu-apps/tasks/main.yml
  roles/8-mgmt-tools/tasks/main.yml
  roles/9-local-addons/tasks/main.yml
  scripts/local_facts.fact
Labels: enhancement

#2888 0-init/tasks/network.yml: Clarify var FQDN_changed falling into disuse?
  roles/0-init/tasks/main.yml
  roles/0-init/tasks/network.yml
Labels: enhancement

#2887 NGINX Security Risk: Remove /cgi-bin access to /usr/lib ?
  roles/nginx/templates/server.conf.j2
Labels: bug, question

#2889 0-init/defaults/main.yml: reconcile & document many stale vars
  roles/0-init/defaults/main.yml
  roles/0-init/tasks/create_iiab_ini.yml
  roles/0-init/tasks/main.yml
  roles/1-prep/defaults/main.yml
  roles/network/tasks/computed_network.yml
  scripts/local_facts.fact
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2890 Cleaner roles/0-init and roles/1-prep
  roles/0-init/defaults/main.yml
  roles/1-prep/templates/chrony.conf.j2.unused
Labels: enhancement

#2891 Desupport Debian 10 + lay groundwork for Debian 12 (Bookworm)
  scripts/local_facts.fact
  vars/debian-12.yml
  vars/default_vars.yml
Labels: enhancement
