Repository iiab/iiab, pull requests merged in 2021-12, with the labels that each got.

#3055 pip install latest PRE-release of JupyterHub — until JupyterHub 2.0.0 is released very shortly
  roles/jupyterhub/tasks/install.yml
Labels: enhancement

#3059 scripts/iiab-diagnostics: Run 'rfkill list' to clarify whether WiFi & Bluetooth are SOFT/HARD blocked (or enabled)
  scripts/iiab-diagnostics
Labels: enhancement

#3061 Add 'lspci -nn' to iiab-diagnostics, and remove iiab-gen-iptables that's no longer useful
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
Labels: enhancement

#3063 Recommend ansible-core 2.12.1 + clarify latest Ansible repos/docs
  scripts/ansible
Labels: enhancement

#3066 MediaWiki Security Release 1.37.1 (coming Wednesday)
  roles/mediawiki/defaults/main.yml
Labels: enhancement

#2965 Experiment w/ kiwix-tools nightly 2021-12-17 (requires libzim 7.0.0 and then libkiwix 10.0.0)
  roles/kiwix/defaults/main.yml
Labels: enhancement, question, good 1st issue

#3073 Test adding allow all
  roles/kiwix/templates/kiwix-nginx.conf.j2
Labels: bug

#3074 kiwix-nginx.conf.j2: Avoid "403 Forbidden" for articles that begin with a dot
  roles/kiwix/templates/kiwix-nginx.conf.j2
Labels: bug

#3076 kiwix/defaults/main.yml: Experiment w/ kiwix-tools 2021-12-21
  roles/kiwix/defaults/main.yml
Labels: enhancement

#3078 Update iiab-test-wifi.j2
  roles/network/templates/hostapd/iiab-test-wifi.j2
Labels: enhancement

#3079 Experiment with kiwix-tools 2021-12-24 nightly build
  roles/kiwix/defaults/main.yml
Labels: enhancement

#3080 Simplify www_base/tasks/php-stem.yml for stem-armhf-7.4.so on RasPiOS 11 — for 12.6GB es-wikihow (2015 RACHEL module)
  roles/www_base/tasks/main.yml
  roles/www_base/tasks/php-stem.yml
Labels: enhancement

#3081 roles/www_base/tasks/php-stem.yml: Clarify... php_extension: "{{ php_extensions[php_version] }}"
  roles/www_base/tasks/php-stem.yml
Labels: enhancement

#3082 www_base/tasks/php-stem.yml needs phpX.Y-sqlite3 (es-wikihow search was failing when osm-vector-maps was not installed)
  roles/osm-vector-maps/tasks/install.yml
  roles/www_base/tasks/php-stem.yml
Labels: bug

#3084 remoteit/defaults/main.yml: 4.13.5 -> 4.13.6 (remote.it support)
  roles/remoteit/README.md
  roles/remoteit/defaults/main.yml
Labels: enhancement

#3083 osm_vector_maps was repeatedly failing to install, so use 'timeout: "{{ download_timeout }}"' with get_url (in 10 roles!) [& change IIAB's 'download_timeout: 200' to 100 sec]
  roles/azuracast/tasks/install.yml
  roles/firmware/tasks/download.yml
  roles/gitea/tasks/install.yml
  roles/minetest/tasks/minetest_install_mods.yml
  roles/network/tasks/netplan.yml
  roles/nodered/tasks/rpi_desk.yml
  roles/osm-vector-maps/tasks/install.yml
  roles/phpmyadmin/tasks/install.yml
  roles/remoteit/tasks/install.yml
  roles/www_base/tasks/php-stem.yml
  vars/default_vars.yml
  vars/local_vars_large.yml
  vars/local_vars_medium.yml
  vars/local_vars_small.yml
Labels: enhancement, question

#3085 roles/www_base: Cleaner/Safer php-stem
  roles/www_base/tasks/main.yml
  roles/www_base/tasks/php-stem.yml
Labels: enhancement

#3086 Cleaner output for local_facts.fact on Raspberry Pi & similar, by hiding the null byte in /proc/device-tree/model
  scripts/local_facts.fact
Labels: enhancement

#3087 local_facts.fact: Stop supporting Ubuntu 21.04
  scripts/local_facts.fact
Labels: enhancement

#3088 local_vars_medium.yml: Let's give Kolibri a shot
  vars/local_vars_medium.yml
Labels: enhancement
