Repository iiab/iiab, pull requests merged in 2021-05, with the labels that each got.

#2774 Recommend ansible-base 2.10.9
  .travis.yml
  scripts/ansible
Labels: enhancement

#2776 Lokole nginx only
  roles/lokole/defaults/main.yml
  roles/lokole/tasks/install.yml
  roles/lokole/tasks/main.yml
  roles/lokole/templates/lokole-nginx.conf.j2
  roles/lokole/templates/webapp_secrets.sh.j2
  roles/nginx/README.md
  vars/debian-10.yml
  vars/debian-11.yml
  vars/linuxmint-20.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
  vars/ubuntu-20.yml
  vars/ubuntu-21.yml
Labels: enhancement

#2778 Begin to document 'lokole_sim_type: LocalOnly' & 'lokole_sim_type: Ethernet'
  roles/lokole/defaults/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2779 munin - drop apache dependency and use stock munin.conf
  roles/munin/tasks/install.yml
  roles/munin/templates/munin.conf.j2.unused
Labels: enhancement

#2780 Lokole install blocked on RaspiOS, so add 'python_ver: 3.7' to vars/raspbian-10.yml
  vars/raspbian-10.yml
Labels: bug

#2781 Monit - do no harm
  roles/monit/tasks/install.yml
  roles/monit/templates/ejabberd.unused
  roles/monit/templates/httpd.unused
  roles/monit/templates/idmgr.unused
  roles/monit/templates/monitrc.unused
  roles/monit/templates/postgresql.unused
  roles/monit/templates/squid.unused
  roles/monit/templates/sshd.unused
Labels: enhancement

#2784 Moodle 3.11 Released: In future we might want to set 'max_input_vars = 5000' in /etc/php/X.Y/fpm/php.ini and also in /etc/php/X.Y/apache2/php.ini etc?
  roles/moodle/defaults/main.yml
  roles/moodle/tasks/install.yml
  roles/www_options/tasks/main.yml
Labels: enhancement

#2787 add pid to unit file
  roles/kalite/templates/kalite-serve.service.j2
Labels: bug

#2782 Create lokole user
  roles/lokole/defaults/main.yml
  roles/lokole/tasks/install.yml
  roles/lokole/templates/celery.service.j2
  roles/lokole/templates/settings.env.j2
  roles/lokole/templates/webapp_secrets.sh.j2
Labels: enhancement, question

#2788 Further clarify lokole_sim_type options
  roles/lokole/defaults/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2743 Interim/Alternative to PR #2742 accelerates testing w/ "pip3 install ansible-core" (2.11+) in both places
  .travis.yml
  scripts/ansible
Labels: enhancement, question

#2789 OPWEN_SETTINGS
  roles/lokole/defaults/main.yml
  roles/lokole/tasks/install.yml
  roles/lokole/templates/celery.service.j2
  roles/lokole/templates/celerybeat.service.j2
  roles/lokole/templates/lokole.service.j2
  roles/lokole/templates/lokole_restarter.service.j2
  roles/lokole/templates/settings.env.j2
  roles/lokole/templates/webapp_secrets.sh.j2
Labels: enhancement, question

#2791 Lokole User Guide URL fix
  roles/lokole/tasks/install.yml
Labels: enhancement

#2793 awstats/tasks/install.yml: sorting out Apache vs. NGINX dependencies (WIP)
  roles/awstats/tasks/install.yml
Labels: enhancement, question

#2796 Don't softcode in local_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2798 Mandate nginx_high_php_limits in www_options/tasks/main.yml if moodle_install (as required by Moodle 3.11 w/ PHP 8). For /etc/php/{{ php_version }}/fpm/php.ini
  roles/moodle/tasks/install.yml
  roles/www_options/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2801 Released: ansible-core 2.11.1, ansible-base 2.10.10, ansible 2.9.22
  scripts/ansible
Labels: enhancement

#2803 ansible - install dependencies before pip
  scripts/ansible
Labels: enhancement

#2802 Lok merge
  roles/lokole/defaults/main.yml
  roles/lokole/tasks/install.yml
  roles/lokole/tasks/main.yml
  roles/lokole/tasks/setup.yml
  roles/lokole/templates/celery.service.unused
  roles/lokole/templates/celerybeat.service.unused
  roles/lokole/templates/lokole.service.unused
  roles/lokole/templates/lokole_celery_beat.conf
  roles/lokole/templates/lokole_celery_worker.conf
  roles/lokole/templates/lokole_gunicorn.conf
  roles/lokole/templates/lokole_restarter.conf
  roles/lokole/templates/lokole_restarter.service.unused
  roles/lokole/templates/settings.env.j2
  roles/lokole/templates/webapp.sh.unused
  roles/lokole/templates/webapp_secrets.sh.unused
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement

#2804 Modernize iiab-support so that it only installs OpenVPN when truly nec
  iiab-support
Labels: enhancement

#2805 scripts/ansible attempts to upgrade Ansible (functionality restored)
  scripts/ansible
Labels: enhancement

#2806 MediaWiki 1.36.0
  roles/mediawiki/defaults/main.yml
Labels: enhancement
