Repository iiab/iiab, pull requests merged in 2021-04, with the labels that each got.

#2722 MediaWiki 1.35.1 -> 1.35.2 LTS (security patch)
  roles/mediawiki/defaults/main.yml
Labels: enhancement

#2725 Gitea 1.14.0 released: so change IIAB branch from 1.13 to 1.14
  roles/gitea/defaults/main.yml
Labels: enhancement

#2726 Illegal tab character in captiveportal/tasks/main.yml (ansible-core 2.11 requires legal .yml's)
  roles/captiveportal/tasks/main.yml
Labels: bug

#2728 PR #2727 w/ on-screen warnings for iiab-internet-on|off
  roles/network/tasks/computed_network.yml
  roles/network/tasks/enable_services.yml
  roles/network/tasks/restart.yml
  roles/network/templates/gateway/iiab-gen-iptables
  roles/network/templates/gateway/iiab-internet-off
  roles/network/templates/gateway/iiab-internet-on
Labels: enhancement

#2727 Don't load legacy modules & New feature rapid changing of client internet access
  roles/network/tasks/computed_network.yml
  roles/network/tasks/enable_services.yml
  roles/network/tasks/restart.yml
  roles/network/templates/gateway/iiab-gen-iptables
  roles/network/templates/gateway/iiab-internet-off
  roles/network/templates/gateway/iiab-internet-on
Labels: enhancement

#2729 Correctly record Ansible versions like "[core 2.11.0rc2]" (e.g. when installing pre-releases using 'pip3 install ansible-core')
  iiab-install
  scripts/ansible
  scripts/local_facts.fact
Labels: bug

#2730 iiab-internet-on / iiab-internet-off: Link to IIAB's firewall (iptables) doc
  roles/network/templates/gateway/iiab-internet-off
  roles/network/templates/gateway/iiab-internet-on
Labels: enhancement

#2731 sysd-netd-debian.yml typo in comment?
  roles/network/tasks/sysd-netd-debian.yml
Labels: enhancement, question

#2732 sysd-netd-debian.yml & rpi_debian.yml: Restore explanation of hostapd restart
  roles/network/tasks/rpi_debian.yml
  roles/network/tasks/sysd-netd-debian.yml
Labels: enhancement

#2733 Packaging for PR #2719 to promote JupyterHub programming with Notebooks
  .gitignore
  roles/0-init/tasks/validate_vars.yml
  roles/6-generic-apps/tasks/main.yml
  roles/jupyterhub/README.md
  roles/jupyterhub/defaults/main.yml
  roles/jupyterhub/tasks/enable-or-disable.yml
  roles/jupyterhub/tasks/install.yml
  roles/jupyterhub/tasks/main.yml
  roles/jupyterhub/templates/jupyterhub-nginx.conf
  roles/jupyterhub/templates/jupyterhub.service
  roles/jupyterhub/templates/jupyterhub_config.py
  roles/network/templates/gateway/iiab-gen-iptables
  roles/nginx/README.md
  vars/default_vars.yml
  vars/local_vars_big.yml
  vars/local_vars_medium.yml
  vars/local_vars_min.yml
Labels: enhancement, question

#2719 Jupyter Notebooks
  .gitignore
  roles/jupyterhub/defaults/main.yml
  roles/jupyterhub/docs/README.md
  roles/jupyterhub/tasks/enable-or-disable.yml
  roles/jupyterhub/tasks/install.yml
  roles/jupyterhub/tasks/main.yml
  roles/jupyterhub/templates/jupyterhub-nginx.conf
  roles/jupyterhub/templates/jupyterhub.service
  roles/jupyterhub/templates/jupyterhub_config.py
  roles/network/templates/gateway/iiab-gen-iptables
  vars/default_vars.yml
Labels: enhancement

#2734 Elgg 2.3.16 -> 2.3.17
  roles/elgg/defaults/main.yml
Labels: enhancement

#2737 Lint jupyterhub-nginx.conf & nginx.conf
  roles/jupyterhub/tasks/enable-or-disable.yml
  roles/jupyterhub/tasks/install.yml
  roles/jupyterhub/templates/jupyterhub-nginx.conf
  roles/nginx/templates/nginx.conf.j2
Labels: enhancement

#2736 Jhubfix
  roles/jupyterhub/templates/jupyterhub-nginx.conf
  roles/nginx/templates/nginx.conf.j2
Labels: bug

#2746 Update ubuntu-21.yml [for PostgreSQL 13]
  vars/ubuntu-21.yml
Labels: enhancement

#2751 WIP: Lint & explain lesser-known packages in 2-common/tasks/packages.yml
  roles/2-common/tasks/packages.yml
Labels: enhancement

#2754 update bootstrap 3 and 4 and jquery to latest versions
  roles/www_base/files/html/css/bootstrap-theme.css
  roles/www_base/files/html/css/bootstrap-theme.css.map
  roles/www_base/files/html/css/bootstrap-theme.min.css
  roles/www_base/files/html/css/bootstrap-theme.min.css.map
  roles/www_base/files/html/css/bootstrap.css
  roles/www_base/files/html/css/bootstrap.css.map
  roles/www_base/files/html/css/bootstrap.min.css
  roles/www_base/files/html/css/bootstrap.min.css.map
  roles/www_base/files/html/css/bootstrap4.min.css
  roles/www_base/files/html/fonts/glyphicons-halflings-regular.eot
  roles/www_base/files/html/fonts/glyphicons-halflings-regular.svg
  roles/www_base/files/html/fonts/glyphicons-halflings-regular.ttf
  roles/www_base/files/html/fonts/glyphicons-halflings-regular.woff
  roles/www_base/files/html/js/bootstrap.js
  roles/www_base/files/html/js/bootstrap.min.js
  roles/www_base/files/html/js/bootstrap4.min.js
  roles/www_base/files/html/js/jquery.min.js
Labels: enhancement

#2750 scripts/ansible: apt-key command is going away, so load .gpg key from repo
  scripts/ansible
  scripts/iiab-ansible-keyring.gpg
Labels: enhancement

#2755 Sugarizer 1.4.0 -> 1.5.0
  roles/sugarizer/defaults/main.yml
Labels: enhancement

#2757 lokole/tasks/main.yml: fix illegal char EM DASH \u2014 in iiab.ini description
  roles/lokole/tasks/main.yml
Labels: bug

#2760 00-create cleanup
  roles/usb_lib/tasks/install.yml
  roles/usb_lib/tasks/main.yml
Labels: bug, help wanted

#2759 Drop bridge-utils [and deprecate br0.j2]
  iiab-network
  roles/2-common/tasks/packages.yml
  roles/network/tasks/restart.yml
  roles/network/templates/network/br0.j2.deprecated
  scripts/iiab-diagnostics
Labels: enhancement

#2693 Debian mate
  roles/2-common/tasks/iptables.yml
  roles/2-common/tasks/main.yml
  roles/2-common/tasks/network.yml
  roles/2-common/tasks/packages.yml
  roles/network/tasks/NM-debian.yml
  roles/network/tasks/netplan.yml
  roles/network/tasks/sysd-netd-debian.yml
Labels: enhancement

#2761 cups - drop apache
  roles/cups/tasks/enable-or-disable.yml
  roles/cups/tasks/install.yml
  roles/nginx/README.md
Labels: enhancement

#2764 /etc/iiab/iiab.ini norms: install / enabled -> ROLE_install / ROLE_enabled
  roles/awstats/tasks/main.yml
  roles/bluetooth/tasks/enable-or-disable.yml
  roles/bluetooth/tasks/main.yml
  roles/calibre-web/tasks/main.yml
  roles/captiveportal/tasks/main.yml
  roles/cups/tasks/install.yml
  roles/cups/tasks/main.yml
  roles/elgg/tasks/main.yml
  roles/gitea/tasks/main.yml
  roles/kalite/tasks/main.yml
  roles/kiwix/tasks/main.yml
  roles/kolibri/tasks/main.yml
  roles/lokole/tasks/main.yml
  roles/mediawiki/tasks/main.yml
  roles/minetest/tasks/enable-or-disable.yml
  roles/minetest/tasks/main.yml
  roles/mongodb/tasks/main.yml
  roles/moodle/tasks/main.yml
  roles/mosquitto/tasks/main.yml
  roles/munin/tasks/main.yml
  roles/mysql/tasks/main.yml
  roles/network/tasks/computed_services.yml
  roles/network/tasks/dansguardian.yml
  roles/network/tasks/enable_services.yml
  roles/network/tasks/squid.yml
  roles/network/tasks/wondershaper.yml
  roles/nextcloud/tasks/main.yml
  roles/openvpn/tasks/main.yml
  roles/osm-vector-maps/tasks/main.yml
  roles/phpmyadmin/tasks/main.yml
  roles/postgresql/tasks/main.yml
  roles/samba/tasks/main.yml
  roles/sshd/tasks/main.yml
  roles/sugarizer/tasks/main2.yml
  roles/usb_lib/tasks/main.yml
  roles/vnstat/tasks/main.yml
  roles/wordpress/tasks/main.yml
Labels: enhancement

#2769 rename current_host_channel -> current_client_channel and record
  roles/network/tasks/computed_services.yml
  roles/network/tasks/hostapd.yml
Labels: enhancement
