Repository iiab/iiab, pull requests merged in 2022-08, with the labels that each got.

#3329 Live w/ red errors to set can_be_ap ('failed_when: False' was too strong)
  roles/network/tasks/detected_network.yml
Labels: bug

#3331 Explain iiab-network alert: "WiFi chipset/firmware NOT CAPABLE of AP Mode (details above)"
  roles/network/tasks/detected_network.yml
Labels: enhancement

#3332 iiab-diagnostics: sudo ufw status verbose
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
Labels: enhancement

#3334 detected_network.yml: Disallow multi-line var second_gateway_found ~= exclude_devices (to avoid polluting /etc/iiab/iiab.ini)
  roles/network/tasks/detected_network.yml
Labels: bug, admin console

#3333 iiab-diagnostics: dmesg | grep -i <about 9 WiFi patterns> | head -100 (firmware/driver msgs)
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
Labels: enhancement, question

#3336 Revert "1-prep/templates/iiab-expand-rootfs: Avoid reboot"
  roles/1-prep/templates/iiab-expand-rootfs
Labels: bug

#3341 /usr/bin/iiab-support-off: Disable openvpn service AND openvpn_enabled in local_vars.yml
  roles/openvpn/templates/iiab-remote-off
Labels: enhancement

#3304 Cwivagg/matomo 20220618
  roles/0-init/tasks/validate_vars.yml
  roles/8-mgmt-tools/tasks/main.yml
  roles/matomo/README.adoc
  roles/matomo/defaults/main.yml
  roles/matomo/tasks/install.yml
  roles/matomo/tasks/main.yml
  roles/matomo/tasks/nginx.yml
  roles/matomo/templates/matomo-nginx.conf.j2
  vars/default_vars.yml
  vars/local_vars_large.yml
  vars/local_vars_medium.yml
  vars/local_vars_small.yml
  vars/local_vars_unittest.yml
Labels: enhancement

#3342 Recommend ansible-core 2.13.3
  scripts/ansible
Labels: enhancement

#3344 kiwix/defaults/main.yml: New kiwix-tools version 3.3.0-1
  roles/kiwix/defaults/main.yml
Labels: enhancement

#3347 kolibri/tasks/install.yml: PPA special cases for Mint 20 (focal) + Mint 21 (jammy)
  roles/kolibri/tasks/install.yml
Labels: bug

#3351 iiab-diagnostics: Display /etc/fstab as external disks get more popular
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
Labels: enhancement

#3354 Cwivagg timezone patch [Matomo]
  roles/matomo/tasks/install.yml
Labels: bug

#2946 Get Azuracast baseline - Fix port reassignment - WIP - needs testing
  prod.env.j2
  roles/azuracast/README.rst
  roles/azuracast/docker-compose.override.yml.j2.unused
  roles/azuracast/env.j2.unused
  roles/azuracast/tasks/install.yml
  roles/azuracast/templates/azuracast-nginx.conf.j2
  roles/azuracast/templates/azuracast.env
  roles/azuracast/templates/azuracast.sample.env
  roles/azuracast/upstream/azuracast.sample.env
  roles/azuracast/upstream/docker-compose.sample.yml
  roles/azuracast/upstream/docker.sh
  roles/azuracast/upstream/notes.txt
  roles/azuracast/upstream/sample.env
  vars/default_vars.yml
Labels: question

#3353 6-generic-apps/tasks/main.yml: AzuraCast restoration prep
  roles/6-generic-apps/tasks/main.yml
  roles/9-local-addons/tasks/main.yml
  roles/azuracast/README.rst
Labels: enhancement, question

#3355 azuracast/tasks/main.yml: skip_role_on_error
  roles/azuracast/tasks/main.yml
  test.yml
Labels: enhancement
