Repository iiab/iiab, pull requests merged in 2022-06, with the labels that each got.

#3233 mediawiki/defaults/main.yml: new release 1.38.0
  roles/mediawiki/defaults/main.yml
Labels: enhancement

#3234 MediaWiki 1.38.1 fixes problems with last week's 1.38.0
  roles/mediawiki/defaults/main.yml
Labels: enhancement

#3237 test.yml: Document ansible_local.local_facts, ansible_architecture etc
  test.yml
Labels: enhancement

#3238 WIP: MongoDB Spring Cleaning (bug fixes) for #3236
  roles/mongodb/tasks/install.yml
  roles/mongodb/templates/iiab-mongodb-repair-if-no-lock.j2
  roles/mongodb/templates/mongodb.service.j2
Labels: enhancement

#3239 test.yml: Document ansible_facts['distribution'] etc — "avoid ansible_distribution since Ansible 2.7"
  test.yml
Labels: enhancement

#3246 nodered/tasks/rpi_desk.yml: Interim patch comments out 'pi' on RasPiOS
  roles/nodered/tasks/rpi_desk.yml
Labels: bug

#3248 Rework + modernize Node-RED's roles/nodered install routine (no more 'pi', ETC!)
  roles/calibre-web/tasks/enable-or-disable.yml
  roles/calibre-web/tasks/main.yml
  roles/cups/tasks/install.yml
  roles/kolibri/tasks/enable-or-disable.yml
  roles/kolibri/tasks/main.yml
  roles/nextcloud/tasks/main.yml
  roles/nodered/defaults/main.yml
  roles/nodered/tasks/apache.yml.unused
  roles/nodered/tasks/enable-or-disable.yml
  roles/nodered/tasks/group.yml
  roles/nodered/tasks/install.yml
  roles/nodered/tasks/main.yml
  roles/nodered/tasks/os-integration.yml
  roles/nodered/tasks/rpi_desk.yml
  roles/nodered/tasks/settings.yml
  roles/nodered/templates/nodered.service.j2.unused
  roles/nodered/templates/settings.js.j2.unused
  roles/pbx/tasks/freepbx.yml
  roles/sugarizer/tasks/main2.yml
Labels: enhancement

#3241 WIP: Tighten up roles/mongodb — runs 'apt-mark hold mongodb-org mongodb-org-server' on 64-bit RPi if installing MongoDB >= 5.0
  roles/mongodb/defaults/main.yml
  roles/mongodb/tasks/install.yml
  roles/mongodb/tasks/main.yml
Labels: enhancement

#3250 Use moodle/tasks/enable-or-disable.yml like in other roles
  roles/moodle/tasks/enable-or-disable.yml
  roles/moodle/tasks/main.yml
Labels: enhancement

#3251 iiab-diagnostics: 'df -ah' for disk usage detail
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
Labels: enhancement

#3235 kiwix-tools 3.3.0 is coming very soon (with "opensearch")
  roles/kiwix/defaults/main.yml
Labels: enhancement

#3254 7.3.4 usb mount
  roles/usb_lib/templates/mount.d/70-usb-library
  roles/usb_lib/templates/umount.d/70-usb-library
  vars/local_vars_none.yml
Labels: enhancement

#3255 Prototype 'skip_role_on_error: True' in 4 roles {lokole, moodle, mongodb, sugarizer}
  roles/7-edu-apps/tasks/main.yml
  roles/lokole/tasks/main.yml
  roles/mongodb/tasks/main.yml
  roles/moodle/tasks/main.yml
  roles/sugarizer/tasks/main.yml
  vars/default_vars.yml
Labels: enhancement

#3256 Support skip_role_on_error in 23+3 more roles (Stages 6-9)
  roles/awstats/tasks/main.yml
  roles/calibre-web/tasks/main.yml
  roles/calibre/tasks/enable-or-disable.yml
  roles/calibre/tasks/main.yml
  roles/captiveportal/tasks/main.yml
  roles/gitea/tasks/enable-or-disable.yml
  roles/gitea/tasks/main.yml
  roles/internetarchive/tasks/enable-or-disable.yml
  roles/internetarchive/tasks/main.yml
  roles/jupyterhub/tasks/main.yml
  roles/kalite/tasks/enable-or-disable.yml
  roles/kalite/tasks/main.yml
  roles/kiwix/tasks/main.yml
  roles/kolibri/tasks/main.yml
  roles/mediawiki/tasks/main.yml
  roles/minetest/tasks/main.yml
  roles/mongodb/tasks/enable-or-disable.yml
  roles/mongodb/tasks/main.yml
  roles/monit/tasks/main.yml
  roles/mosquitto/tasks/main.yml
  roles/munin/tasks/enable-or-disable.yml
  roles/munin/tasks/main.yml
  roles/nextcloud/tasks/main.yml
  roles/nodejs/tasks/main.yml
  roles/nodered/tasks/main.yml
  roles/osm-vector-maps/tasks/main.yml
  roles/pbx/tasks/main.yml
  roles/phpmyadmin/tasks/main.yml
  roles/postgresql/tasks/enable-or-disable.yml
  roles/postgresql/tasks/main.yml
  roles/transmission/tasks/main.yml
  roles/vnstat/tasks/main.yml
  roles/wordpress/tasks/main.yml
  roles/yarn/tasks/main.yml
Labels: enhancement

#3257 /usr/bin/iiab-apps-to-be-installed: Quick scan to see what's asked for but not yet installed
  roles/0-init/tasks/main.yml
  roles/1-prep/tasks/main.yml
  scripts/iiab-apps-to-be-installed
Labels: enhancement

#3258 iiab-diagnostics: Fix cat_cmd output + grep -B2 "SEE ERROR ABOVE" /opt/iiab/iiab/*.log + speed up prompt
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
Labels: enhancement

#3260 Force string python_ver: "3.10" in ubuntu-2204.yml & ubuntu-2210.yml [also update debian-12.yml "Bookworm"]
  vars/debian-12.yml
  vars/ubuntu-2204.yml
  vars/ubuntu-2210.yml
Labels: bug

#3261 test.yml: float (drops outer zeros) vs AnsibleUnicode (String)
  test.yml
Labels: enhancement

#3262 Try 'skip_role_on_error: True' in default_vars.yml for more uninterrupted installs of IIAB Apps ['./iiab-install --risky' if you want to live on the wild side, forcing it too to use 'skip_role_on_error: True']
  iiab-from-cmdline.yml
  iiab-from-console.yml
  iiab-install
  iiab-network.yml
  iiab-stages.yml
  install-support.yml.unused
  run-one-role.yml
  runrole
  runroles-base.yml
  test.yml
  vars/default_vars.yml
Labels: enhancement, admin console

#3265 22.04 & Mint 21: Avoid Sugarizer+Moodle initially (TEMPORARY)
  roles/7-edu-apps/tasks/main.yml
  vars/linuxmint-21.yml
Labels: enhancement

#3267 Highlight recent git tags (e.g. "8.0-preview-2" and "v0.5.5.9") in /usr/bin/iiab-summary, iiab-diagnostics etc [and remote URLs, branch names, PR count / commit count since tag...]
  roles/0-init/tasks/create_iiab_ini.yml
  roles/0-init/tasks/main.yml
  roles/1-prep/tasks/main.yml
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
  scripts/iiab-summary
  scripts/local_facts.fact
Labels: enhancement

#3269 remoteit/tasks/install.yml: Remove "IIAB_LIKE=Ubuntu" after workaround, for Ansible OS detection
  roles/remoteit/tasks/install.yml
Labels: bug

#3271 awstats.schoolserver.conf.j2: Set AllowFullYearView=3 not 2
  roles/awstats/templates/awstats.schoolserver.conf.j2
Labels: enhancement

#3270 Record branch's actual Git remote (URL) to iiab.ini (in 2 places) + cleaner /usr/bin/iiab-summary when Admin Console is missing
  roles/0-init/tasks/create_iiab_ini.yml
  roles/0-init/tasks/main.yml
  scripts/iiab-summary
  scripts/local_facts.fact
Labels: enhancement, admin console

#3272 Speed up roles/0-init by almost 50% (by moving 2 things to detected_network.yml)
  roles/0-init/defaults/main.yml
  roles/0-init/tasks/main.yml
  roles/0-init/tasks/network.yml
  roles/1-prep/tasks/main.yml
  roles/network/defaults/main.yml
  roles/network/tasks/detected_network.yml
  roles/phpmyadmin/tasks/install.yml
  roles/vnstat/tasks/install.yml
  roles/www_options/tasks/main.yml
Labels: enhancement

#3274 @jvonau's PR #3273 with obsolete groovy (Ubuntu 20.10) code block commented out & clarified [drop ping altogether, and vars internet_available & gw_active]
  roles/network/defaults/main.yml
  roles/network/tasks/detected_network.yml
  roles/network/tasks/netplan.yml
  roles/vnstat/tasks/install.yml
  roles/www_options/tasks/main.yml
  vars/default_vars.yml
Labels: enhancement
