Repository iiab/iiab, pull requests merged in 2022-10, with the labels that each got.

#3388 0-init: Skip validate_vars.yml on Zero W & Zero 2 W (slow Raspberry Pi's)
  roles/0-init/tasks/main.yml
Labels: enhancement, question

#3390 3385 Ignore detected wifi device from LAN detection when not currently active.
  roles/network/defaults/main.yml
  roles/network/tasks/detected_network.yml
  roles/network/tasks/rpi_debian.yml
  roles/network/tasks/sysd-netd-debian.yml
  roles/network/templates/network/systemd-br0-slave.j2
Labels: bug, enhancement

#3391 Auto-install latest/official kiwix-tools + tighten up code
  roles/kiwix/defaults/main.yml
  roles/kiwix/tasks/enable-or-disable.yml
  roles/kiwix/tasks/install.yml
  roles/kiwix/tasks/main.yml
Labels: enhancement

#3392 Move 'hooks' to their respective backends
  roles/network/tasks/enable_services.yml
  roles/network/tasks/hostapd.yml
  roles/network/tasks/install.yml
  roles/network/tasks/rpi_debian.yml
  roles/network/tasks/sysd-netd-debian.yml
Labels: bug

#3395 Refine remote.it operations, now that connectd system service is gone, and considering 3 valid states for /etc/remoteit/registration
  roles/remoteit/README.md
  roles/remoteit/defaults/main.yml
  roles/remoteit/tasks/enable-or-disable.yml
  roles/remoteit/tasks/install.yml
  roles/remoteit/tasks/main.yml
  roles/remoteit/templates/iiab-remoteit
  roles/remoteit/templates/iiab-remoteit-off
Labels: enhancement

#3396 Recommend ansible-core 2.13.5
  scripts/ansible
Labels: enhancement

#3397 mongodb/tasks/install.yml: Force libssl1.1 on is_linuxmint_21 too (for Sugarizer)
  roles/mongodb/tasks/install.yml
Labels: bug

#3402 Copy Node-RED's default settings.js from /usr/lib/... OR /usr/local/lib/…
  roles/nodered/tasks/settings.yml
Labels: bug

#3405 Refine published password warnings, avoiding Mint 21 pop-up
  roles/iiab-admin/templates/sshpwd-lxde-iiab.sh.j2
  roles/iiab-admin/templates/sshpwd-profile-iiab.sh.j2
Labels: bug

#3400 2-common/tasks/packages.yml: Debian 12 needs 'apt install cron'
  roles/2-common/tasks/packages.yml
Labels: bug

#3407 MongoDB 4.4 -> 6.0; force libssl1.1 for Debian 12 (for Sugarizer)
  roles/mongodb/defaults/main.yml
  roles/mongodb/tasks/install.yml
Labels: enhancement

#3410 Use OS's Node.js & npm if Nodesource dragging (+ always wipe prior versions)
  roles/nodejs/README.md
  roles/nodejs/tasks/install.yml
Labels: enhancement

#3411 Force-install libssl1.1 on ARM64 Ubuntu 22.04+ for MongoDB 5+ & Sugarizer
  roles/mongodb/defaults/main.yml
  roles/mongodb/tasks/install.yml
Labels: enhancement

#3413 Modernize install of Kolibri PPA for Ubuntu 22.04+ (e.g. 23.04, 23.10, etc)
  roles/kolibri/tasks/install.yml
Labels: enhancement

#3414 Debian 12 Bookworm uses PostgreSQL 15 (released 2022-10-13)
  vars/debian-12.yml
Labels: enhancement

#3415 Preliminary support for Ubuntu 23.04 Lunar Lobster
  roles/kalite/tasks/install.yml
  roles/monit/tasks/main.yml
  roles/network/tasks/avahi.yml
  roles/network/tasks/debian.yml
  roles/network/tasks/detected_network.yml
  roles/network/tasks/dhcpd.yml.unused
  roles/network/tasks/main.yml
  roles/network/tasks/sysd-netd-debian.yml
  scripts/local_facts.fact
  vars/debian-11.yml
  vars/debian-12.yml
  vars/default_vars.yml
  vars/linuxmint-20.yml
  vars/linuxmint-21.yml
  vars/raspbian-11.yml
  vars/ubuntu-2004.yml
  vars/ubuntu-2204.yml
  vars/ubuntu-2210.yml
Labels: enhancement
