Repository iiab/iiab, pull requests merged in 2022-12, with the labels that each got.

#3431 Install the new MediaWiki 1.39.0 LTS
  roles/mediawiki/defaults/main.yml
Labels: enhancement

#3432 Recommend ansible-core 2.14.1
  scripts/ansible
Labels: enhancement

#3435 Rename .travis.yml to .travis.yml.unused
  .travis.yml.unused
Labels: enhancement

#3436 Clean .gitignore: XS bitrot, space pollution, emacs support
  .gitignore
Labels: enhancement

#3437 .gitignore enhanced for emacs, which generates even more tmp files since 2022
  .gitignore
Labels: enhancement

#3438 Dynamically extract python_ver & postgresql_version
  roles/0-init/tasks/main.yml
  roles/lokole/tasks/install.yml
  roles/nextcloud/tasks/install.yml
  roles/postgresql/tasks/install.yml
  scripts/iiab-diagnostics
  scripts/local_facts.fact
  vars/debian-11.yml
  vars/debian-12.yml
  vars/linuxmint-20.yml
  vars/linuxmint-21.yml
  vars/raspbian-11.yml
  vars/ubuntu-2004.yml.unused
  vars/ubuntu-2204.yml
  vars/ubuntu-2210.yml
  vars/ubuntu-2304.yml
Labels: enhancement

#3439 Dynamically extract php_version & python_version
  iiab-install
  roles/0-init/tasks/main.yml
  roles/jupyterhub/tasks/install.yml
  roles/lokole/tasks/install.yml
  roles/lokole/tasks/setup.yml
  roles/lokole/templates/lokole-nginx.conf.j2
  runrole
  scripts/local_facts.fact
  vars/debian-11.yml
  vars/debian-12.yml
  vars/linuxmint-20.yml.unused
  vars/linuxmint-21.yml
  vars/raspbian-11.yml
  vars/ubuntu-2004.yml.unused
  vars/ubuntu-2204.yml
  vars/ubuntu-2210.yml
  vars/ubuntu-2304.yml
Labels: enhancement

#3440 Put vars/<OS-VER>.yml files on a diet, moving stale vars to default_vars.yml or roles/X/defaults
  roles/kiwix/defaults/main.yml
  roles/sshd/defaults/main.yml
  vars/debian-11.yml
  vars/debian-12.yml
  vars/default_vars.yml
  vars/linuxmint-21.yml
  vars/raspbian-11.yml
  vars/ubuntu-2204.yml
  vars/ubuntu-2210.yml
  vars/ubuntu-2304.yml
Labels: enhancement

#3445 iiab-admin/templates/sshpwd-lxde-iiab.sh.j2: Fix {{ sshd_service }}
  roles/iiab-admin/templates/sshpwd-lxde-iiab.sh.j2
Labels: bug

#3443 Fix for Issue #3441
  roles/matomo/tasks/install.yml
Labels: bug

#3446 Put Kiwix var {{ systemctl_program }} to rest — simple is almost always better
  roles/kiwix/defaults/main.yml
  roles/kiwix/tasks/enable-or-disable.yml
  roles/kiwix/templates/iiab-make-kiwix-lib
Labels: enhancement

#3447 Somewhat higher PHP limits for Matomo — similar to Nextcloud, PBX, WordPress
  roles/www_options/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_large.yml
  vars/local_vars_medium.yml
  vars/local_vars_small.yml
  vars/local_vars_unittest.yml
Labels: enhancement

#3448 Several updates to make Matomo experience cleaner
  roles/matomo/README.adoc
  roles/matomo/tasks/install.yml
  roles/matomo/templates/matomo-nginx.conf.j2
Labels: bug, enhancement

#3449 PHP Limits Dependency Cleanup: www_options/tasks/set-php-limits.yml run on demand (by 5 relevant roles)
  roles/matomo/tasks/install.yml
  roles/moodle/tasks/install.yml
  roles/nextcloud/tasks/install.yml
  roles/pbx/tasks/freepbx.yml
  roles/wordpress/tasks/install.yml
  roles/www_options/tasks/main.yml
  roles/www_options/tasks/set-php-limits.yml
  vars/default_vars.yml
  vars/local_vars_large.yml
  vars/local_vars_medium.yml
  vars/local_vars_small.yml
  vars/local_vars_unittest.yml
Labels: bug, enhancement

#3451 Use the new 'gitea_version: 1.18' (instead of 1.17)
  roles/gitea/defaults/main.yml
Labels: enhancement

#3453 Store actual System TZ (not Ansible's ambiguous TZ abbreviations) into fpm/php.ini & cli/php.ini — for Matomo etc
  roles/0-init/tasks/main.yml
  roles/0-init/tasks/tz.yml.unused
  roles/matomo/tasks/install.yml
  roles/moodle/tasks/install.yml
  roles/nextcloud/tasks/install.yml
  roles/pbx/tasks/freepbx.yml
  roles/wordpress/tasks/install.yml
  roles/www_options/tasks/main.yml
  roles/www_options/tasks/php-settings.yml
  vars/default_vars.yml
  vars/local_vars_large.yml
  vars/local_vars_medium.yml
  vars/local_vars_small.yml
  vars/local_vars_unittest.yml
Labels: enhancement
