Repository iiab/iiab, pull requests merged in 2022-09, with the labels that each got.

#3356 kolibri/tasks/install.yml: Modern apt keyring approach [& apt upgrading Kolibri very risky!]
  roles/kolibri/tasks/install.yml
Labels: enhancement

#3361 Allow for NM with RPiOS
  roles/network/tasks/main.yml
Labels: enhancement

#3363 remoteit/tasks/enable-or-disable.yml: Don't fail if svc(s) missing
  roles/remoteit/tasks/enable-or-disable.yml
Labels: bug

#3360 Update AzuraCast stale inline docs. Prepare to revise "azuracast_port_range_prefix: 10" (i.e. ports 10xxx for now, including blocked port 10080) as AzuraCast recommendations evolve.
  roles/azuracast/defaults/main.yml
  vars/default_vars.yml
  vars/local_vars_large.yml
  vars/local_vars_medium.yml
  vars/local_vars_small.yml
  vars/local_vars_unittest.yml
Labels: enhancement

#3364 Recommend ansible-core 2.13.4
  scripts/ansible
Labels: enhancement

#3365 plocate: Faster & smaller than locate & mlocate
  roles/2-common/tasks/packages.yml
Labels: enhancement

#3368 Published Password warnings work better with 'sudo -n'
  roles/iiab-admin/templates/sshpwd-lxde-iiab.sh.j2
  roles/iiab-admin/templates/sshpwd-profile-iiab.sh.j2
Labels: bug, enhancement

#3369 add utility scripts
  iiab-setup
  iiab-upgrade
Labels: enhancement

#3370 iiab-install: mkdir -p /etc/iiab/install-flags
  iiab-install
Labels: bug, enhancement

#3371 rectification of names
  adm-upgrade
Labels: enhancement

#3373 Better description of current configuration when networking is disabled
  roles/network/templates/hostapd/iiab-hotspot-off
  roles/network/templates/hostapd/iiab-hotspot-on
Labels: enhancement

#3337 Straw Man 1-prep/templates/iiab-expand-rootfs.service based on 2020's PR #2522 + /usr/sbin/iiab-expand-rootfs "bash -xe" exit-on-error (to defer deleting /.expand-rootfs)
  roles/1-prep/templates/iiab-expand-rootfs
  roles/1-prep/templates/iiab-expand-rootfs.service
Labels: bug, help wanted, question

#3380 Force-install libssl1.1 if MongoDB needed on Ubuntu >= 22.04 (for Sugarizer)
  iiab-install
  iiab-setup
  roles/0-init/tasks/main.yml
  roles/7-edu-apps/tasks/main.yml
  roles/mongodb/defaults/main.yml
  roles/mongodb/tasks/install.yml
  roles/mongodb/tasks/main.yml
Labels: enhancement

#3382 Encourage pre-release testing of Moodle 4.1 LTS if PHP >= 8.1
  roles/7-edu-apps/tasks/main.yml
  roles/moodle/defaults/main.yml
  roles/moodle/tasks/install.yml
Labels: enhancement, help wanted, good 1st issue

#3383 mediawiki/defaults/main.yml: Version 1.38.3
  roles/mediawiki/defaults/main.yml
Labels: enhancement

#3379 Fix hostapd for Raspberry Pi Zero W (systemd unit files, so it doesn't start too early!)
  roles/network/templates/hostapd/hostapd.legacy.j2
  roles/network/templates/hostapd/iiab-clone-wifi.service.j2
Labels: bug, help wanted

#3384 AzuraCast 'stable' instead of 'latest' + Simplify install + Document './runrole --reinstall azuracast' manual workaround
  roles/azuracast/README.rst
  roles/azuracast/tasks/install.yml
  roles/azuracast/templates/azuracast-nginx.conf.j2.unused
  roles/azuracast/templates/azuracast.env.j2
Labels: enhancement

#3386 mediawiki/defaults/main.yml: Version 1.38.4
  roles/mediawiki/defaults/main.yml
Labels: enhancement
