Repository iiab/iiab, pull requests merged in 2022-07, with the labels that each got.

#3280 scripts/iiab-summary: Clarify when PR's are auto-pulled
  scripts/iiab-summary
Labels: enhancement

#3282 iiab-summary: Path for iiab-apps-to-be-installed (so it works early on)
  scripts/iiab-summary
Labels: enhancement

#3284 iiab-apps-to-be-installed: rm tmp file (so diff users can later run this cleanly)
  scripts/iiab-apps-to-be-installed
Labels: bug

#3285 /usr/bin/iiab-apps-to-be-installed: double square brackets (safer for string compare)
  scripts/iiab-apps-to-be-installed
Labels: bug

#3291 Extract IIAB_REMOTE_URL from 1 of 2 places, for both Git repos {iiab, iiab-admin-console} and...
  roles/0-init/tasks/create_iiab_ini.yml
  roles/0-init/tasks/main.yml
  scripts/iiab-apps-to-be-installed
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
  scripts/iiab-summary
  scripts/local_facts.fact
Labels: enhancement

#3292 Small revisions for 3 commands: iiab-apps-to-be-installed, iiab-summary, iiab-diagnostics
  roles/0-init/tasks/main.yml
  roles/1-prep/tasks/main.yml
  scripts/iiab-diagnostics
  scripts/iiab-summary
Labels: enhancement

#3295 jupyterhub/tasks/install.yml: Use --no-cache-dir w/o --pre [AND stop patching firstuseauthenticator.py]
  roles/jupyterhub/tasks/install.yml
  roles/jupyterhub/templates/getsite.py.j2.unused
  roles/jupyterhub/templates/patch_FUA.sh.j2.unused
Labels: enhancement

#3299 Transition from 172.18.96.1 to 10.10.10.10 thanks to PR #3281
  roles/captiveportal/tasks/install.yml
  roles/captiveportal/templates/iiab-divert-to-nginx.j2
  roles/cups/tasks/install.yml
  roles/cups/templates/cups.conf.j2
  roles/network/tasks/enable_services.yml
  roles/network/tasks/named.yml
  roles/network/templates/dhcp/dhcpd-iiab.conf.j2
  roles/network/templates/gateway/iiab-gen-iptables
  roles/network/templates/named/school.internal.zone.db
  roles/network/templates/named/school.internal.zone.db.j2
  roles/network/templates/named/school.local.zone.db.j2
  roles/network/templates/network/bridge-br0
  roles/network/templates/network/dhcpcd.conf.j2
  roles/network/templates/network/dnsmasq.conf.j2
  roles/network/templates/network/systemd-br0-network.j2
  roles/nextcloud/README.md
  roles/samba/templates/smb.conf.j2
  roles/transmission/defaults/main.yml
  vars/default_vars.yml
Labels: enhancement

#3281 10.10.10..10 server address
  roles/captiveportal/templates/iiab-divert-to-nginx
  roles/cups/tasks/install.yml
  roles/cups/templates/cups.conf.j2
  roles/network/templates/dhcp/dhcpd-iiab.conf.j2
  roles/network/templates/gateway/iiab-gen-iptables
  roles/network/templates/named/school.internal.zone.db
  roles/network/templates/named/school.local.zone.db
  roles/network/templates/network/bridge-br0
  roles/network/templates/network/dhcpcd.conf.j2
  roles/network/templates/network/dnsmasq.conf.j2
  roles/network/templates/network/systemd-br0-network.j2
  roles/nextcloud/README.md
  roles/samba/templates/smb.conf.j2
  roles/transmission/defaults/main.yml
  vars/default_vars.yml
Labels: enhancement

#3301 drop old olpc fedora paths
  roles/2-common/tasks/fl.yml
Labels: enhancement

#3302 Allow for network role to be fully optional, building on PR #3173
  roles/0-init/tasks/hostname.yml
  roles/0-init/tasks/main.yml
  roles/0-init/tasks/network.yml
  roles/0-init/tasks/validate_vars.yml
  roles/1-prep/tasks/main.yml
  roles/2-common/tasks/main.yml
  roles/4-server-options/tasks/main.yml
  roles/network/tasks/computed_network.yml
  roles/network/tasks/hostapd.yml
  roles/network/tasks/install.yml
  roles/network/tasks/main.yml
  vars/default_vars.yml
Labels: enhancement

#3306 scripts/local_facts.fact: Stop supporting Ubuntu 21.10 (Impish Indri)
  scripts/local_facts.fact
Labels: enhancement

#3308 Network helper
  iiab-network
  roles/1-prep/tasks/main.yml
  scripts/iiab-network
Labels: enhancement

#3310 default_vars.yml: kiwix-3.5.0.apk from 2022-05-31
  vars/default_vars.yml
Labels: enhancement

#3311 Download kiwix.apk instead of kiwix-3.5.0.apk
  roles/kiwix/tasks/kiwix-apk.yml
  vars/default_vars.yml
Labels: enhancement

#3316 roles/osm-vector-maps: Download three 25-48MB files from new repo iiab/maps-assets
  roles/osm-vector-maps/defaults/main.yml
  roles/osm-vector-maps/tasks/install.yml
Labels: enhancement

#3317 Create roles/nodejs/README.md consolidating Node.js and npm configuration issues
  roles/nodejs/README.md
Labels: enhancement

#3318 /usr/local/sbin/netwarn pop-ups (if iiab-network needs to be run) on MATE & RasPiOS with desktop + roles/network refactoring
  iiab-network
  roles/network/tasks/avahi.yml
  roles/network/tasks/detected_network.yml
  roles/network/tasks/enable_services.yml
  roles/network/tasks/hostapd.yml
  roles/network/tasks/install.yml
  roles/network/tasks/main.yml
  roles/network/tasks/netplan.yml
  roles/network/tasks/netwarn.yml
  roles/network/tasks/restart.yml
  roles/network/templates/netwarn/netwarn
  roles/network/templates/netwarn/netwarn-iiab-network.desktop
  roles/network/templates/network/ifcfg-WAN.j2.unused
  roles/network/templates/network/ifcfg-slave.j2.unused
  roles/network/templates/network/ifcfg.j2.unused
  roles/network/templates/network/sysconfig.network.j2.unused
  roles/www_options/tasks/main.yml
  scripts/iiab-network
Labels: enhancement, help wanted

#3313 Net warn
  roles/network/tasks/enable_services.yml
  roles/network/tasks/hostapd.yml
  roles/network/tasks/install.yml
  roles/network/tasks/main.yml
  roles/network/templates/network/ifcfg-WAN.j2.unsued
  roles/network/templates/network/ifcfg-slave.j2.unused
  roles/network/templates/network/ifcfg.j2.usused
  roles/network/templates/network/sysconfig.network.j2.unused
  scripts/iiab-network
  scripts/netwarn-iiab-network.desktop
  scripts/netwarn.sh
Labels: enhancement

#3319 Set default for use in netplan.yml and wording
  roles/network/tasks/install.yml
  roles/network/tasks/netplan.yml
  roles/network/tasks/sysd-netd-debian.yml
Labels: bug

#3323 network/tasks/detected_network.yml: can_be_ap grep failed on absence of regex
  roles/network/tasks/detected_network.yml
Labels: bug

#3326 Use the new 'gitea_version: 1.17' instead of 1.16
  roles/gitea/defaults/main.yml
Labels: enhancement

#3327 Install Kolibri using PPA, which promises auto-upgrades (when you apt update?)
  roles/kolibri/defaults/main.yml
  roles/kolibri/tasks/install.yml
  vars/local_vars_large.yml
  vars/local_vars_medium.yml
  vars/local_vars_small.yml
  vars/local_vars_unittest.yml
Labels: enhancement
