Repository iiab/iiab, pull requests merged in 2022-04, with the labels that each got.

#3156 Always install the latest remote.it Device Package (instead of hard-coding a new version# every 1-2 months!)
  roles/remoteit/defaults/main.yml
  roles/remoteit/tasks/install.yml
Labels: enhancement

#3157 vars files: Update remote.it & OpenVPN tips
  vars/default_vars.yml
  vars/local_vars_large.yml
  vars/local_vars_medium.yml
  vars/local_vars_small.yml
  vars/local_vars_unittest.yml
Labels: enhancement

#3160 1-prep/templates/iiab-expand-rootfs: Avoid reboot
  roles/1-prep/templates/iiab-expand-rootfs
Labels: enhancement

#3151 9-local-addons: Do not install php-pear
  roles/9-local-addons/tasks/main.yml
Labels: enhancement

#3161 New command /usr/bin/iiab-remoteit to quickly obtain a new Claim Code for https://remote.it (allows remote connections to manage an IIAB)
  roles/remoteit/README.md
  roles/remoteit/defaults/main.yml
  roles/remoteit/tasks/enable-or-disable.yml
  roles/remoteit/tasks/install.yml
  roles/remoteit/templates/iiab-remoteit
  roles/remoteit/templates/iiab-remoteit-off
  roles/remoteit/templates/iiab-remoteit.old
Labels: enhancement

#3163 iiab-diagnostics: Run '/opt/iiab/kiwix/bin/kiwix-serve --version' to help with kiwix-tools debugging
  scripts/iiab-diagnostics
Labels: enhancement

#3164 Fix 5 typos: /etc/iiab/iiab_state.yml -> /etc/iiab/iiab.ini
  roles/gitea/tasks/main.yml
  roles/lokole/tasks/main.yml
  roles/nodejs/tasks/main.yml
  roles/postgresql/tasks/main.yml
  roles/yarn/tasks/main.yml
Labels: bug

#3167 Stop & Disable any remoteit@* services (via Ansible or iiab-remoteit-off)
  roles/remoteit/tasks/enable-or-disable.yml
  roles/remoteit/templates/iiab-remoteit-off
Labels: bug

#3168 Fix explanations in /usr/bin/iiab-remoteit & /usr/bin/iiab-remoteit-off
  roles/remoteit/templates/iiab-remoteit
  roles/remoteit/templates/iiab-remoteit-off
Labels: enhancement

#3175 kiwix-tools 3.2.0-3: kiwix-serve fix(es) for full-text search and articleCount?
  roles/kiwix/defaults/main.yml
Labels: bug

#3176 remoteit/templates/iiab-remoteit touch-ups
  roles/remoteit/templates/iiab-remoteit
Labels: enhancement

#3178 Install apt pkg 'smbclient' instead of virtual pkg 'samba-client' (in samba/tasks/install.yml)
  roles/samba/tasks/install.yml
Labels: enhancement

#3183 templates/iiab-remoteit: Warn if /etc/remoteit/config.json exists...and try it if operator really wants to?
  roles/remoteit/README.md
  roles/remoteit/templates/iiab-remoteit
Labels: enhancement

#3184 Moodle 4.0 is now official
  roles/moodle/defaults/main.yml
  roles/moodle/tasks/install.yml
Labels: enhancement

#3187 FreePBX 16 now officially works with Asterisk 19 (so remove temp patch)
  roles/pbx/README.adoc
  roles/pbx/tasks/freepbx.yml
Labels: enhancement

#3186 Try out Node.js 18.x (now released, becomes LTS on 2022-10-25)
  roles/internetarchive/tasks/install.yml
  roles/nodejs/defaults/main.yml
  vars/default_vars.yml
Labels: enhancement

#3189 Stage 6/7 bypass of apps not yet compatible w/ Ubuntu 22.04 (Kolibri, Nextcloud, Moodle, Sugarizer)
  roles/6-generic-apps/tasks/main.yml
  roles/7-edu-apps/tasks/main.yml
Labels: enhancement

#3165 Branch Maps7.3 -- includes 2020 OSM data and 2020 satellite images
  roles/osm-vector-maps/README.md
  roles/osm-vector-maps/defaults/main.yml
  roles/osm-vector-maps/tasks/install.yml
Labels: enhancement

#3191 Recommend ansible-core 2.12.5
  scripts/ansible
Labels: enhancement

#3196 Revert "install fonts to '/viewer/assets/'"
  roles/osm-vector-maps/tasks/install.yml
Labels: question

#3198 Revert "upstream fonts.css does not have mapping to 'common'"
  roles/osm-vector-maps/tasks/install.yml
Labels: bug

#3200 Fix vars/local_vars_unittest.yml: 'download_timeout: 100' (not 200)
  vars/local_vars_unittest.yml
Labels: bug

#3201 Workaround to induce remote.it install on Linux Mint
  roles/remoteit/tasks/install.yml
Labels: enhancement

#3202 remoteit/tasks/install.yml: Refine PR #3201 using Ansible not bash
  roles/remoteit/tasks/install.yml
Labels: enhancement

#3204 osm-vector-maps: Lint + clarify for readability e.g. map_installer_url -- and speed up initial install of 48MB planet_z0-z6_2020.mbtiles + 25MB satellite_z0-z6_2020.mbtiles
  roles/osm-vector-maps/defaults/main.yml
  roles/osm-vector-maps/tasks/install.yml
Labels: enhancement

#3203 copy fonts.css to maps assets
  roles/osm-vector-maps/tasks/install.yml
Labels: bug
