Repository iiab/iiab, pull requests merged in 2022-05, with the labels that each got.

#3205 Begin updating osm-vector-maps/README.md e.g. "How to upgrade IIAB Maps" (ENTIRELY AT YOUR OWN RISK)
  roles/osm-vector-maps/README.md
Labels: enhancement

#3208 Nextcloud 24.0.0 works w/ PHP 8.1 on Ubuntu 22.04
  roles/6-generic-apps/tasks/main.yml
  roles/nextcloud/tasks/install.yml
Labels: enhancement

#3209 scripts/iiab-diagnostics: Redact wep-key[0-3]=PASSWORD (for old WiFi routers)
  scripts/iiab-diagnostics
Labels: enhancement

#3212 kiwix-tools 3.2.0-4: fixes for diacritics (accents) etc
  roles/kiwix/defaults/main.yml
Labels: enhancement

#3213 default_vars.yml: 'kiwix_apk_src: [full URL]/kiwix-android/kiwix-3.4.5.apk' for now
  vars/default_vars.yml
Labels: bug

#3214 mongodb/tasks/install.yml: Try 5.0.x (was 4.4.x) on all four 64-bit OS's (for Sugarizer)
  roles/mongodb/tasks/install.yml
Labels: enhancement, question

#3215 nextcloud/README.md: Warn about Nextcloud News app's 32-bit requirement
  roles/nextcloud/README.md
Labels: enhancement

#3218 phpMyAdmin 5.1.3 -> 5.2.0
  roles/phpmyadmin/defaults/main.yml
Labels: enhancement

#3219 iiab-diagnostics: journalctl -t IIAB-CMDSRV
  scripts/iiab-diagnostics
Labels: enhancement

#3222 Check hardware for AP and if so record 'can_be_ap = True' to /etc/iiab/iiab.ini
  roles/network/defaults/main.yml
  roles/network/tasks/detected_network.yml
  roles/network/tasks/hostapd.yml
Labels: enhancement

#3070 Detect, record if wifi can be AP and suppress installing supporting files
  roles/network/defaults/main.yml
  roles/network/tasks/detected_network.yml
  roles/network/tasks/hostapd.yml
Labels: enhancement

#3223 Tolerate Ubuntu 22.10 Kinetic Kudu to help with testing
  scripts/local_facts.fact
  vars/default_vars.yml
  vars/ubuntu-2210.yml
Labels: enhancement

#3225 7-edu-apps: TEMPORARY 'and not is_ubuntu_2210' for #3189
  roles/7-edu-apps/tasks/main.yml
Labels: bug

#3179 set 'host_country_code' to value found in wpa_supplicant.conf [on Raspberry Pi OS only, deferring Ubuntu/Debian upstream issues]
  roles/network/tasks/hostapd.yml
  roles/network/tasks/restart.yml
  roles/network/tasks/rpi_debian.yml
  roles/network/tasks/sysd-netd-debian.yml
  roles/network/templates/hostapd/50-hostapd
  roles/network/templates/hostapd/iiab-hotspot-off
  roles/network/templates/hostapd/iiab-hotspot-on
  vars/default_vars.yml
  vars/local_vars_large.yml
  vars/local_vars_medium.yml
  vars/local_vars_small.yml
  vars/local_vars_unittest.yml
Labels: enhancement, question

#3229 freepbx-16.0-latest.tgz STALE so git clone to /opt/iiab/freepbx
  roles/pbx/README.adoc
  roles/pbx/defaults/main.yml
  roles/pbx/tasks/asterisk.yml
  roles/pbx/tasks/freepbx.yml
  roles/pbx/tasks/install.yml
  vars/default_vars.yml
  vars/local_vars_large.yml
  vars/local_vars_medium.yml
  vars/local_vars_small.yml
  vars/local_vars_unittest.yml
Labels: enhancement

#3230 iiab-diagnostics: 4 fixes/cleanups
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
Labels: enhancement
