Repository iiab/iiab, pull requests merged in 2023-01, with the labels that each got.

#3460 Update matomo-nginx.conf.j2 ["fix the error private directories are accessible"]
  roles/matomo/templates/matomo-nginx.conf.j2
Labels: enhancement, question

#3461 http://box/info/admin-console offline docs [& fix iiab-refresh-wiki-docs e.g. for scraping of Raspberry Pi Images docs]
  roles/nginx/templates/iiab.conf.j2
  roles/www_base/templates/iiab-refresh-wiki-docs.sh
Labels: enhancement, admin console

#3462 iiab-diagnostics: Highlight /etc/iiab/install-flags sequence
  scripts/iiab-diagnostics
Labels: enhancement

#3464 mediawiki/defaults/main.yml: Version 1.39.1
  roles/mediawiki/defaults/main.yml
Labels: enhancement

#3469 Avoid bolting on libssl1.1, now that MongoDB can use libssl3 (at long last!) [e.g. on Ubuntu 22.04+ & Debian 12]
  roles/mongodb/tasks/install.yml
Labels: enhancement

#3470 Install Moodle dev pre-release (e.g. 4.2dev for now) IFF PHP >= 8.3
  roles/moodle/tasks/install.yml
Labels: enhancement

#3471 Recommend ansible-core 2.14.2
  scripts/ansible
Labels: enhancement
