Repository iiab/iiab, pull requests merged in 2023-04, with the labels that each got.

#3520 Record arch
  roles/0-init/tasks/create_iiab_ini.yml
  roles/mongodb/tasks/main.yml
Labels: enhancement, question

#3521 Modernize Yarn install w/ signed apt/PPA key (prereq for Internet Archive)
  roles/yarn/tasks/install.yml
Labels: enhancement

#3523 EXPERIMENTAL: 'asterisk_rpi_patch: True' option for Raspberry Pi + preliminary path to FreePBX on PHP 8
  roles/pbx/README.adoc
  roles/pbx/defaults/main.yml
  roles/pbx/files/install_prereq.diff
  roles/pbx/tasks/apache.yml
  roles/pbx/tasks/asterisk.yml
  roles/pbx/tasks/enable-or-disable.yml
  roles/pbx/tasks/freepbx.yml
  roles/pbx/tasks/main.yml
  scripts/ansible
  vars/default_vars.yml
  vars/local_vars_large.yml
  vars/local_vars_medium.yml
  vars/local_vars_small.yml
  vars/local_vars_unittest.yml
Labels: enhancement

#3524 asterisk_installed
  roles/pbx/tasks/asterisk.yml
  roles/pbx/tasks/install.yml
Labels: enhancement

#3525 RasPiOS-12
  scripts/local_facts.fact
  vars/raspbian-12.yml
Labels: enhancement

#3527 Python2 fix [for KA Lite on Debian 12 or Ubuntu 23.04 / 23.10]
  roles/kalite/tasks/install.yml
  scripts/install_python2.sh
  scripts/local_facts.fact
  vars/default_vars.yml
  vars/ubuntu-2310.yml
Labels: enhancement

#3529 ka-lite libssl1.1 use raspi repo
  scripts/install_python2.sh
Labels: enhancement

#3531 kalite - dup'd line typo
  scripts/install_python2.sh
Labels: bug

#3532 BUG: no path
  roles/www_options/tasks/main.yml
Labels: enhancement

#3533 Pbx readme [Wave Lite app option, so Android phones actually ring when screen's locked etc]
  roles/pbx/README.adoc
  roles/pbx/files/Wave_sip_phone_connected.png
  roles/pbx/files/wave_sip settings.png
Labels: enhancement

#3503 use --system-site-packages and install package to omit building 'netifaces' wheel [Calibre-Web]
  roles/calibre-web/tasks/install.yml
Labels: enhancement

#3540 Allow rescue/continue if CUPS or Samba installs fail [if skip_role_on_error: True]
  roles/2-common/tasks/packages.yml
  roles/cups/tasks/main.yml
  roles/samba/tasks/main.yml
Labels: enhancement

#3537 RFC 2210 2304 fixed https://bugs.launchpad.net/bugs/1951586 [netplan WiFi country code]
  roles/network/tasks/NM-debian.yml
  roles/network/tasks/restart.yml
  roles/network/tasks/sysd-netd-debian.yml
  roles/network/templates/hostapd/iiab-hotspot-off
  roles/network/templates/hostapd/iiab-hotspot-on
  roles/network/templates/hostapd/iiab-test-wifi.j2
  roles/network/templates/hostapd/netd-disp2
Labels: enhancement, question

#3550 ansible-core 2.14.5 & beefed up for latest 32-bit ARM (armhf) cryptography / piwheels / rust problems
  scripts/ansible
Labels: enhancement

#3551 Moodle 4.2 (new release)
  roles/moodle/defaults/main.yml
  roles/moodle/tasks/install.yml
Labels: enhancement

#3554 Jupyterhub
  roles/calibre-web/tasks/install.yml
  roles/jupyterhub/tasks/install.yml
  roles/lokole/tasks/install.yml
  roles/nodejs/tasks/install.yml
Labels: bug

#3549 Unified PR for WiFi hotspot testing of channel-changing, country code, etc
  roles/network/tasks/NM-debian.yml
  roles/network/tasks/computed_services.yml
  roles/network/tasks/hostapd.yml
  roles/network/tasks/main.yml
  roles/network/tasks/restart.yml
  roles/network/tasks/rpi_debian.yml
  roles/network/tasks/sysd-netd-debian.yml
  roles/network/templates/hostapd/iiab-hotspot-off
  roles/network/templates/hostapd/iiab-hotspot-on
  roles/network/templates/hostapd/iiab-test-wifi.j2
  roles/network/templates/hostapd/iiab-wifi-test.service.j2
  roles/network/templates/hostapd/netd-disp2
  roles/network/templates/network/dnsmasq.sh.j2
Labels: enhancement

#3555 iiab-clone-wifi needs template from hostapd - record wifi_up_down
  roles/network/tasks/hostapd.yml
  roles/network/tasks/restart.yml
  roles/network/tasks/rpi_debian.yml
  roles/network/tasks/sysd-netd-debian.yml
Labels: enhancement

#3559 Revert to Moodle 4.1 if PHP 7 + toughen Moodle/Nextcloud
  roles/moodle/tasks/install.yml
  roles/nextcloud/tasks/install.yml
Labels: enhancement

#3560 Temporarily Enable sysctl's IPv6 during Munin install/enable, so munin-node.service starts
  roles/munin/tasks/enable-or-disable.yml
  roles/munin/tasks/install.yml
  roles/network/tasks/install.yml
Labels: enhancement
