Repository iiab/iiab, pull requests merged in 2023-05, with the labels that each got.

#3562 Toughen up vnStat: Mitigate #3539 db errors, stop using 2011's /etc/vnstat.conf, etc
  roles/vnstat/tasks/install.yml
  roles/vnstat/templates/vnstat.conf.j2.unused
  test.yml
Labels: enhancement

#3564 Allow multiple (timestamped) backups of WiFi firmware originals (as your OS evolves!)
  roles/firmware/tasks/download.yml
Labels: enhancement

#3565 Clarify PR #3564 (pre-download WiFi firmware backups)
  roles/firmware/tasks/download.yml
Labels: enhancement

#3567 If 32-bit OS, bypass Sugarizer & Explain during iiab-install
  roles/7-edu-apps/tasks/main.yml
  roles/mongodb/tasks/main.yml
Labels: enhancement

#3569 GitHub Actions stub .github/workflows/10min-iiab-test-install.yml for CI/CD & QA
  .github/workflows/10min-iiab-test-install.yml
Labels: enhancement

#3575 Try aarch64 version of kiwix-tools 3.5.0+ [WARNING: such microSD cards will no longer be insertable in 32-bit Raspberry Pi Zero W]
  roles/kiwix/defaults/main.yml
Labels: enhancement, question

#3576 Revert to kiwix-tools 3.4.0 if armhf 3.5.0 downloads [for 32-bit Raspberry Pi Zero W]
  roles/kiwix/defaults/main.yml
  roles/kiwix/tasks/install.yml
Labels: bug

#3577 Recommend ansible-core 2.15.0
  iiab-install
  scripts/ansible
Labels: enhancement

#3578 Fix PR #3576, allowing regular Kiwix installs too!
  roles/kiwix/tasks/install.yml
Labels: bug

#3580 Set rpi_model from /proc/cpuinfo for QEMU
  scripts/local_facts.fact
Labels: enhancement

#3579 GitHub Actions .github/workflows/30min-iiab-test-install-raspios.yml for CI/CD & QA
  .github/workflows/10min-iiab-test-install.yml
  .github/workflows/30min-iiab-test-install-raspios.yml
Labels: enhancement

#3582 'pip install virtualenv==20.21.1' for Python 2 required by KA Lite on Ubuntu 23.10
  roles/kalite/tasks/install.yml
  scripts/install_python2.sh
Labels: enhancement

#3587 Pin python3-platformdirs & python3-virtualenv to 22.04 versions, for Python 2 on Ubuntu 23.10+ ? [for KA Lite]
  scripts/install_python2.sh
Labels: enhancement, question

#3590 TEMPORARILY revert ansible-core 2.15.0 to 2.14.6 til the dust settles — e.g. for FreePBX #3588
  scripts/ansible
Labels: bug

#3591 local_vars_medium.yml: Avoid Lokole for now due to #3572
  vars/local_vars_medium.yml
Labels: bug

#3592 Record approx disk usage for 45 roles (to iiab.ini)
  roles/awstats/tasks/install.yml
  roles/azuracast/tasks/install.yml
  roles/calibre-web/tasks/install.yml
  roles/calibre/tasks/install.yml
  roles/captiveportal/tasks/install.yml
  roles/cups/tasks/install.yml
  roles/gitea/tasks/install.yml
  roles/gitea/tasks/main.yml
  roles/iiab-admin/tasks/main.yml
  roles/internetarchive/tasks/install.yml
  roles/jupyterhub/tasks/install.yml
  roles/kalite/tasks/install.yml
  roles/kiwix/tasks/install.yml
  roles/kolibri/tasks/install.yml
  roles/lokole/tasks/install.yml
  roles/matomo/tasks/install.yml
  roles/mediawiki/tasks/install.yml
  roles/minetest/tasks/install.yml
  roles/mongodb/tasks/install.yml
  roles/monit/tasks/install.yml
  roles/moodle/tasks/install.yml
  roles/mosquitto/tasks/install.yml
  roles/munin/tasks/install.yml
  roles/mysql/tasks/install.yml
  roles/network/tasks/install.yml
  roles/nextcloud/tasks/install.yml
  roles/nextcloud/tasks/main.yml
  roles/nginx/tasks/install.yml
  roles/nodejs/tasks/install.yml
  roles/nodered/tasks/install.yml
  roles/openvpn/tasks/install.yml
  roles/osm-vector-maps/tasks/install.yml
  roles/pbx/tasks/install.yml
  roles/phpmyadmin/tasks/install.yml
  roles/postgresql/tasks/install.yml
  roles/pylibs/tasks/main.yml
  roles/remoteit/tasks/install.yml
  roles/samba/tasks/install.yml
  roles/sshd/tasks/install.yml
  roles/sugarizer/tasks/install.yml
  roles/transmission/tasks/install.yml
  roles/usb_lib/tasks/install.yml
  roles/vnstat/tasks/install.yml
  roles/wordpress/tasks/install.yml
  roles/wordpress/tasks/main.yml
  roles/www_base/tasks/main.yml
  roles/www_options/tasks/main.yml
  roles/yarn/tasks/install.yml
Labels: enhancement

#3593 Roughly Estimate iiab_software_disk_usage in /etc/iiab/iiab.ini 'summary' section
  roles/0-init/tasks/create_iiab_ini.yml
  roles/9-local-addons/tasks/main.yml
Labels: enhancement

#3594 Auto-calculate IIAB + EduPack disk space needs, in advance [& design review]
  scripts/iiab-item-size.py
  scripts/iiab-size.py
Labels: enhancement, question
