Repository iiab/iiab, pull requests merged in 2023-03, with the labels that each got.

#3485 MongoDB: Use jammy repo on amd64 (unless Debian 11)
  roles/mongodb/tasks/install.yml
Labels: enhancement

#3488 iiab-diagnostics: Report /lib/firmware/cypress/* not brcm
  scripts/iiab-diagnostics
Labels: enhancement

#3490 Add Haitian Creole (Kreyòl) as Kolibri's 32nd languages
  vars/local_vars_large.yml
  vars/local_vars_medium.yml
  vars/local_vars_small.yml
  vars/local_vars_unittest.yml
Labels: enhancement

#3491 Force 'pip install ansible-core' on Python 3.11+ for Ubuntu 23.04 (Lunar Lobster) & Debian 12 (Bookworm)
  scripts/ansible
Labels: enhancement

#3493 Fix PR #3491 to install ansible-core on all OS's as Python 3.11+ proliferates — accounting for older versions of pip that lack flag `--break-system-packages`
  scripts/ansible
Labels: enhancement

#3496 venv refinements for consideration, to tighten up scripts/ansible, deferring install of pip unless truly nec
  roles/6-generic-apps/tasks/main.yml
  roles/9-local-addons/tasks/main.yml
  roles/calibre-web/tasks/install.yml
  roles/kalite/tasks/install.yml
  roles/lokole/tasks/install.yml
  scripts/ansible
Labels: enhancement, admin console

#3497 Tighten up 9-local-addons thx to iiab/iiab-admin-console#526
  roles/9-local-addons/tasks/main.yml
Labels: enhancement

#3498 calibre-web - compiler and header files only when needed
  roles/calibre-web/tasks/install.yml
Labels: enhancement, question

#3507 Move 2 vars kolibri/defaults to default_vars.yml + Cleaner kolibri homedir in /etc/passwd
  roles/kolibri/defaults/main.yml
  roles/kolibri/tasks/install.yml
  vars/default_vars.yml
Labels: enhancement

#3510 Doc updates for Asterisk 20 & remaining PHP 7.4 OS's (as FreePBX 16 requires)
  roles/pbx/README.adoc
  vars/default_vars.yml
  vars/local_vars_large.yml
  vars/local_vars_medium.yml
  vars/local_vars_small.yml
  vars/local_vars_unittest.yml
Labels: enhancement

#3511 TEMPORARY PATCH: Installs older Nextcloud 25 on PHP 7.4 OS's
  roles/nextcloud/tasks/install.yml
Labels: bug

#3513 Recommend ansible-core 2.14.4
  scripts/ansible
Labels: enhancement

#3515 New Sugarizer 1.7.0
  roles/sugarizer/defaults/main.yml
Labels: enhancement

#3514 kolibri/tasks/install.yml spring cleaning (tighten up code, flow, in-line docs)
  roles/4-server-options/README.rst
  roles/cups/README.md
  roles/kolibri/README.rst
  roles/kolibri/tasks/install.yml
  roles/matomo/README.adoc
  roles/nextcloud/README.md
  roles/nodered/README.rst
  roles/osm-vector-maps/README.md
  roles/pbx/README.adoc
  roles/pbx/README.rst.unused
  roles/phpmyadmin/README.md
  roles/remoteit/README.md
  roles/samba/README.rst
  roles/usb_lib/README.rst
Labels: enhancement

#3519 Block install of MongoDB on 32-bit RasPiOS, when 'dpkg --print-architecture' shows armhf
  roles/mongodb/tasks/install.yml
  roles/mongodb/tasks/main.yml
  test.yml
Labels: enhancement
