Repository iiab/iiab, pull requests merged in 2024-12, with the labels that each got.

#3848 Recommend ansible-core 2.18.1
  iiab-install
  scripts/ansible
Labels: enhancement

#3859 Permit autostart of Chrome browser & pop-up warnings {iiab-netwarn, iiab-pwdwarn-labwc} w/ compositor labwc (no longer Wayfire) on new Raspberry Pi OS
  roles/iiab-admin/tasks/pwd-warnings.yml
  roles/iiab-admin/templates/iiab-pwdwarn-labwc.j2
  roles/network/tasks/netwarn.yml
  roles/network/templates/netwarn/iiab-netwarn
  roles/www_options/tasks/main.yml
Labels: enhancement

#3860 Rename `xklb` to `library` for pipx
  roles/calibre-web/tasks/install.yml
  scripts/iiab-update
Labels: enhancement

#3863 Asterisk 22 (instead of 21, tested on Debian 13)
  roles/pbx/README.adoc
  roles/pbx/defaults/main.yml
Labels: enhancement

#3852 drop netifaces workaround - replaced with netifaces-plus
  roles/calibre-web/tasks/install.yml
Labels: enhancement

#3864 Bypass /etc/ImageMagick-6/policy.xml PDF surgery w/ ImageMagick 7+
  roles/calibre-web/tasks/install.yml
Labels: bug

#3867 Refine PR #3866 to unblock WiFi hotspot on newer RasPiOS with NM (NetworkManager)
  roles/network/tasks/main.yml
  roles/network/tasks/rpi_debian.yml
Labels: bug, enhancement

#3869 rename apache_allow_sudo and make True default
  roles/0-DEPRECATED-ROLES/httpd/defaults/main.yml
  roles/www_options/tasks/main.yml
  roles/www_options/tasks/php-settings.yml
  vars/default_vars.yml
  vars/local_vars_large.yml
  vars/local_vars_medical.yml
  vars/local_vars_medium.yml
  vars/local_vars_small.yml
  vars/local_vars_unittest.yml
Labels: bug, enhancement

#3870 New MediaWiki 1.42.4
  roles/mediawiki/defaults/main.yml
Labels: enhancement

#3872 Update iiab-vpn to fix ANSI color codes on macOS and change text color on blue bg
  roles/tailscale/templates/iiab-vpn
Labels: enhancement
