Repository iiab/iiab, pull requests merged in 2024-10, with the labels that each got.

#3814 MediaWiki 1.42.3 (security & maintenance release)
  roles/mediawiki/defaults/main.yml
Labels: enhancement

#3816 scripts/iiab-update: Also update /usr/bin/iiab-vpn
  scripts/iiab-update
Labels: enhancement

#3815 Experimenting with various apt package installs [e.g. python3-cryptography, so Calibre-Web unit test works on Raspberry Pi OS]
  roles/calibre-web/tasks/install.yml
Labels: enhancement, question

#3817 local_vars_unittest.yml: SKIP roles/network, for FASTER UNIT TESTING
  vars/local_vars_unittest.yml
Labels: enhancement

#3818 RIP apt package `wireless-tools` (Ansible output will auto-highlight distros that increasingly deprecate it, to help us monitor Debian 13/14/etc)
  roles/network/tasks/install.yml
Labels: bug, enhancement

#3826 New Moodle 4.5 LTS
  roles/moodle/defaults/main.yml
  roles/moodle/tasks/install.yml
Labels: enhancement

#3829 iiab-summary: Clean output, when tailscale has no IP
  scripts/iiab-summary
Labels: bug

#3834 Fix iiab-vpn output, when tag:username is missing from any Tailscale peer/node (IP address) — avoiding jq error "Cannot iterate over null (null)"
  roles/tailscale/templates/iiab-vpn
Labels: bug

#3838 Fix tailscale tab completion, when /etc/bash_completion.d does not yet exist
  roles/tailscale/tasks/install.yml
Labels: bug
