Repository iiab/iiab, pull requests merged in 2025-10, with the labels that each got.

#4105 New MediaWiki 1.44.2 (security & maintenance release)
  roles/mediawiki/defaults/main.yml
Labels: enhancement

#4104 apt-mark systemd-zram-generator as manually installed, if installed [FOR NOW: as dphys-swapfile mysteriously sets systemd-zram-generator to "auto-removable" on RPi, or at least on RasPiOS?]
  roles/1-prep/tasks/raspberry_pi.yml
Labels: bug, enhancement, question

#4094 Swap [Q: what to do about RasPiOS apt pkg `dphys-swapfile` forcing apt pkg `systemd-zram-generator` to be "auto-removable" ? A: Migrate to new apt pkg `rpi-swap`]
  roles/1-prep/tasks/raspberry_pi.yml
  vars/default_vars.yml
Labels: enhancement, question

#4106 Revert "apt-mark systemd-zram-generator as manually installed, if installed [FOR NOW: as dphys-swapfile mysteriously sets systemd-zram-generator to "auto-removable" on RPi, or at least on RasPiOS?]"
  roles/1-prep/tasks/raspberry_pi.yml
Labels: enhancement

#4109 Recommend ansible-core 2.19.3
  scripts/ansible
Labels: enhancement
