Repository iiab/iiab, pull requests merged in 2025-03, with the labels that each got.

#3958 iiab-diagnostics: Also record /etc/locale.conf (e.g. for Debian 13 Trixie)
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
Labels: enhancement

#3968 iiab-summary: Cleaner output when /opt/iiab/iiab-admin-console absent
  scripts/iiab-summary
Labels: bug, enhancement

#3973 Recommend ansible-core 2.18.4
  scripts/ansible
Labels: enhancement

#3972 Sugarizer 1.9.0 (upgrade from 1.8.0!)
  roles/sugarizer/defaults/main.yml
Labels: enhancement

#3970 iiab-update quick fix: Copy utility scripts into position in /usr/bin in all cases
  scripts/iiab-update
Labels: bug

#3974 15min CI/QA using SMALL-sized IIAB & clarifs building on PR #3966
  .github/workflows/10min-iiab-test-install.yml
  .github/workflows/15min-iiab-small-install.yml
  .github/workflows/30min-iiab-test-install-deb12-on-rpi3.yml
  .github/workflows/30min-iiab-test-install-raspios-on-zero2w.yml
  .github/workflows/tests/expected_state_none.yml
  .github/workflows/tests/expected_state_small.yml
  .github/workflows/tests/expected_state_unittest.yml
Labels: enhancement

#3966 Improved 10 minute CI run and switched to local_vars_small.yml
  .github/workflows/10min-iiab-test-install.yml
  .github/workflows/20min-iiab-small-install.yml
  .github/workflows/tests/expected_state_none.yml
  .github/workflows/tests/expected_state_small.yml
Labels: enhancement

#3976 Clean up / tighten up 2+2=4 GitHub Actions workflows
  .github/workflows/10min-iiab-unittest-ubuntu.yml
  .github/workflows/15min-iiab-small-ubuntu.yml
  .github/workflows/30min-iiab-none-deb12-on-rpi3.yml
  .github/workflows/30min-iiab-none-raspios-on-zero2w.yml
Labels: enhancement

#3971 Make the upload2usb functionality available directly from /usb/
  roles/nginx/templates/iiab.conf.j2
  roles/usb_lib/files/upload2usb/button.html
  roles/usb_lib/files/upload2usb/header.php
  roles/usb_lib/files/upload2usb/index.php
  roles/usb_lib/files/upload2usb/upload-file.php
  roles/usb_lib/files/upload2usb/upload-simple.php
  roles/usb_lib/files/upload2usb/upload2usb.php
Labels: enhancement

#3977 iiab-diagnostics more resilient
  roles/0-init/tasks/main.yml
  scripts/iiab-diagnostics
Labels: enhancement

#3979 Update 'Upload to USB' to 'Upload' per new functionality.
  roles/usb_lib/README.rst
Labels: enhancement

#3978 Add a MEDIUM-sized IIAB install (GitHub Actions workflow)
  .github/workflows/20min-iiab-medium-ubuntu.yml
  .github/workflows/tests/expected_state_medium.yml
Labels: enhancement
