Repository iiab/iiab, pull requests merged in 2025-02, with the labels that each got.

#3931 Restore both GitHub Actions workflows simulating Raspberry Pi
  roles/usb_lib/tasks/main.yml
  roles/www_options/tasks/php-settings.yml
Labels: enhancement

#3939 70-usb-library.j2: Forcibly delete e.g. stale symlink /library/www/html/local_content/USB0 during USB stick insertion
  roles/usb_lib/templates/mount.d/70-usb-library.j2
Labels: bug

#3942 usb_lib: building on to top of @jvonau's work in #3940. Using existence of /media to determine if a USB stick is mounted or not for both count and upload location; changing tabs to spaces for upload2usb.php
  roles/usb_lib/files/upload2usb/upload2usb.php
  roles/usb_lib/files/usbmount/usbmount
  roles/usb_lib/tasks/install.yml
Labels: enhancement

#3943 usb_lib/tasks/main.yml: update USB_LIB description to be more clear
  roles/usb_lib/tasks/main.yml
Labels: enhancement

#3948 JupHub [JupyterHub fix & cleanup for Debian 13 Trixie, using full path to Python 3.13 in /opt/iiab/iiab/ansible.cfg]
  ansible.cfg
  roles/jupyterhub/tasks/install.yml
Labels: bug, enhancement, question

#3957 Recommend ansible-core 2.18.3
  scripts/ansible
Labels: enhancement
