Repository iiab/iiab, pull requests merged in 2025-01, with the labels that each got.

#3873 New MediaWiki 1.43.0 LTS
  roles/mediawiki/defaults/main.yml
Labels: enhancement

#3874 default_vars.yml: Launch 8.3 Release Cycle
  vars/default_vars.yml
Labels: enhancement

#3879 usb_lib/templates/content_dir.conf.unused: mark unused [Apache] file as such
  roles/usb_lib/templates/content_dir.conf.unused
Labels: enhancement, question

#3887 deal with tailscale0
  roles/network/defaults/main.yml
Labels: enhancement

#3885 Ht new
  roles/network/tasks/detected_network.yml
  roles/network/tasks/hostapd.yml
Labels: enhancement

#3886 dont start hostapd when no_net_restart is True
  roles/network/tasks/restart.yml
Labels: enhancement

#3889 set www_data poweroff false with rename
  roles/0-DEPRECATED-ROLES/httpd/defaults/main.yml
  roles/www_options/tasks/main.yml
  roles/www_options/tasks/php-settings.yml
  roles/www_options/templates/020_www_data_poweroff.j2
  vars/default_vars.yml
  vars/local_vars_large.yml
  vars/local_vars_medical.yml
  vars/local_vars_medium.yml
  vars/local_vars_small.yml
  vars/local_vars_unittest.yml
Labels: enhancement

#3891 Firmware [WiFi]
  roles/network/tasks/detected_network.yml
  roles/network/tasks/main.yml
Labels: enhancement

#3892 don't restart wpa_supplicant when network_manager_active is set
  roles/network/tasks/restart.yml
Labels: bug

#3899 iiab-diagnostics: A bit more logging around wpa_supplicant, NetworkManager, dmesg | grep Firmware, rpi-eeprom-update to show bootloader version
  scripts/iiab-diagnostics
Labels: enhancement, question

#3901 iiab-diagnostics: Cleaner output if COMMAND NOT FOUND
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
Labels: bug

#3902 GitHub Actions CI: Revert ARM tests to run on Ubuntu 22.04 (for now)
  .github/workflows/10min-iiab-test-install.yml
  .github/workflows/30min-iiab-test-install-deb12-on-rpi3.yml
  .github/workflows/30min-iiab-test-install-raspios-on-zero2w.yml
Labels: bug

#3905 replace is_raspbian with dhcpcd_result == enabled
  roles/network/templates/hostapd/iiab-hotspot-off
  roles/network/templates/hostapd/iiab-hotspot-on
Labels: bug, enhancement

#3875 Initial commit of upload2usb App for homework assignments for students and teachers worldwide! [and, upload photos/projects to community's USB stick]
  roles/nginx/templates/iiab.conf.j2
  roles/usb_lib/files/upload/button.html
  roles/usb_lib/files/upload/error.php
  roles/usb_lib/files/upload/footer.php
  roles/usb_lib/files/upload/header.php
  roles/usb_lib/files/upload/index.php
  roles/usb_lib/files/upload/uk-swing.png
  roles/usb_lib/files/upload/upload-file.php
  roles/usb_lib/files/upload/upload2usb.php
  roles/usb_lib/tasks/install.yml
Labels: enhancement

#3908 detect Firmware rejected country setting
  roles/network/defaults/main.yml
  roles/network/tasks/detected_network.yml
Labels: enhancement

#3911 use systemd-udev-trigger.service BUGFIX
  roles/usb_lib/templates/usbmount@.service.j2
Labels: bug, enhancement

#3914 error.php: updating FAQ reference to refer to new upload2usb FAQ
  roles/usb_lib/files/upload/error.php
Labels: enhancement

#3919 upload2usb: moving app out of local_content, relaxing mime type requirements, link swing back to homepage
  roles/nginx/templates/iiab.conf.j2
  roles/usb_lib/files/upload/button.html
  roles/usb_lib/files/upload/header.php
  roles/usb_lib/files/upload/upload2usb.php
  roles/usb_lib/tasks/install.yml
Labels: enhancement

#3922 Recommend ansible-core 2.18.2
  scripts/ansible
Labels: enhancement

#3926 iiab-diagnostics: 3 commands to record locale info
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
Labels: enhancement

#3927 PHP's own defaults are Way Too Low, so run www_options/tasks/php-settings.yml every time
  roles/www_options/tasks/main.yml
Labels: enhancement

#3913 vars/* and usb_lib/*: rename usb_lib_umask0000_for_kolibri
  roles/usb_lib/README.rst
  roles/usb_lib/defaults/main.yml
  roles/usb_lib/files/upload/upload2usb.php
  roles/usb_lib/tasks/install.yml
  roles/usb_lib/tasks/main.yml
  vars/default_vars.yml
  vars/local_vars_large.yml
  vars/local_vars_medical.yml
  vars/local_vars_medium.yml
  vars/local_vars_small.yml
  vars/local_vars_unittest.yml
Labels: enhancement

#3925 1520 [systemctl daemon_reload if not no_net_restart or...]
  iiab-network
  roles/network/tasks/NM-debian.yml
Labels: bug, enhancement

#3928 delay hostapd to allow ap0 to stabilize
  roles/network/tasks/restart.yml
Labels: enhancement

#3929 usb_lib and usbmount refinements built on PR #3916
  roles/usb_lib/files/upload2usb/button.html
  roles/usb_lib/files/upload2usb/error.php
  roles/usb_lib/files/upload2usb/footer.php
  roles/usb_lib/files/upload2usb/header.php
  roles/usb_lib/files/upload2usb/index.php
  roles/usb_lib/files/upload2usb/uk-swing.png
  roles/usb_lib/files/upload2usb/upload-file.php
  roles/usb_lib/files/upload2usb/upload2usb.php
  roles/usb_lib/files/usbmount/copyright
  roles/usb_lib/files/usbmount/usbmount
  roles/usb_lib/files/usbmount/usbmount.conf
  roles/usb_lib/tasks/install.yml
  roles/usb_lib/templates/iiab-clean-usb.sh
  roles/usb_lib/templates/mount.d/70-usb-library.j2
  roles/usb_lib/templates/usbmount.rules.j2
  roles/usb_lib/templates/usbmount@.service.j2
Labels: enhancement

#3930 Invert rejected country red error; Clarify 3 channel / WiFi country code vars for iiab.ini (in detected_network.yml)
  roles/network/tasks/detected_network.yml
Labels: enhancement
