Repository iiab/iiab, pull requests merged in 2025-04, with the labels that each got.

#3965 Fix very flaky IIAB installs with: (1) deferred raspi-config do_wifi_country (2) refined iiab-clone-wifi.service.j2 to add ap0 to correct phyname {phy0, phy1, ...} (3) better WiFi firmware crash logging [e.g. to help when "official" Raspberry Pi OS WiFi firmware cyfmac43455-sdio-standard.bin OFTEN crashes]
  roles/firmware/tasks/warn_fw_crash.yml
  roles/network/tasks/main.yml
  roles/network/templates/hostapd/iiab-clone-wifi.service.j2
  scripts/iiab-diagnostics
  scripts/iiab-diagnostics.README.md
Labels: bug

#3981 Rebalance GitHub Actions workflows: try 4 instead of 5?
  .github/workflows/15min-iiab-small-ubuntu.yml.paused
  .github/workflows/40min-iiab-none-deb12-on-rpi3.yml
  .github/workflows/40min-iiab-unittest-raspios-on-zero2w.yml
Labels: enhancement

#3983 Auto-install Kolibri 0.18.0 Beta 2 if Python >= 3.13 for Ubuntu 25.04, Debian 13, RasPiOS 13, etc (TEMPORARY!)
  roles/kolibri/tasks/install.yml
Labels: enhancement

#3984 Cleaner warn_fw_crash.yml for OS's like Debian where /sys/class/ieee80211/ can be empty
  roles/firmware/tasks/warn_fw_crash.yml
Labels: bug, enhancement

#3987 Revert Upload button (and associated docs) to be 'Upload to USB'
  roles/usb_lib/README.rst
  roles/usb_lib/files/upload2usb/upload-simple.php
Labels: enhancement

#3988 phpMyAdmin 5.2.2
  roles/phpmyadmin/defaults/main.yml
Labels: enhancement

#3989 TEMPORARY: Auto-install Kolibri 0.18.0 Beta 3 if Python >= 3.13
  roles/kolibri/tasks/install.yml
Labels: enhancement

#3990 New MediaWiki 1.43.1 LTS
  roles/mediawiki/defaults/main.yml
Labels: enhancement

#3985 Luanti 5.8+ (was Minetest) from 2023, for new OS's
  roles/0-init/tasks/validate_vars.yml
  roles/9-local-addons/tasks/main.yml
  roles/luanti/NotUsed/calc_vars.yml
  roles/luanti/NotUsed/rpi_minetest_install.yml
  roles/luanti/README.rst
  roles/luanti/defaults/main.yml
  roles/luanti/tasks/enable-or-disable.yml
  roles/luanti/tasks/install.yml
  roles/luanti/tasks/luanti_install.yml
  roles/luanti/tasks/luanti_install_mods.yml
  roles/luanti/tasks/main.yml
  roles/luanti/templates/minetest-server.service.j2.unused
  roles/luanti/templates/minetest.conf.j2.unused
  roles/minetest/README.rst
  roles/minetest/defaults/main.yml
  roles/minetest/tasks/enable-or-disable.yml
  roles/minetest/tasks/install.yml
  roles/minetest/tasks/main.yml
  roles/minetest/tasks/minetest_install.yml
  roles/minetest/tasks/minetest_install_mods.yml
  roles/network/templates/gateway/iiab-gen-iptables
  roles/nginx/README.md
  vars/default_vars.yml
  vars/local_vars_large.yml
  vars/local_vars_medium.yml
  vars/local_vars_small.yml
  vars/local_vars_unittest.yml
Labels: bug, enhancement

#3980 [Upload2USB] Move success/failure response into overlay
  roles/usb_lib/files/upload2usb/upload-file.php
  roles/usb_lib/files/upload2usb/upload-simple.css
  roles/usb_lib/files/upload2usb/upload-simple.php
Labels: enhancement

#3992 New Moodle 5.0, if OS PHP < 8.5
  roles/moodle/defaults/main.yml
  roles/moodle/tasks/install.yml
Labels: enhancement

#3993 TEMPORARY: Auto-install Kolibri 0.18.0 Beta 4 if Python >= 3.13
  roles/kolibri/tasks/install.yml
Labels: enhancement

#3998 Recommy ansible-core 2.18.5
  scripts/ansible
Labels: enhancement

#4000 Kolibri 0.18 RC0 if Python >= 3.13
  roles/kolibri/tasks/install.yml
Labels: enhancement

#4006 Kolibri 0.18.0 is released, so remove Kolibri 0.18.0 pre-release hack
  roles/kolibri/tasks/install.yml
Labels: enhancement
