Repository iiab/iiab, pull requests merged in 2025-07, with the labels that each got.

#4032 New MediaWiki 1.43.3 LTS
  roles/mediawiki/defaults/main.yml
Labels: enhancement

#4034 New MediaWiki 1.44.0
  roles/mediawiki/defaults/main.yml
Labels: enhancement

#4036 Added yamllint configuration for ansible-lint. Added ansible-lint to 10min-iiab-unittest-ubuntu.yml
  .ansible-lint.yml
  .github/workflows/10min-iiab-unittest-ubuntu.yml
  .yamllint
Labels: enhancement

#4037 Remove the full-page upload interface from Upload2USB app. Remove unu…
  roles/usb_lib/files/upload2usb/footer.php
  roles/usb_lib/files/upload2usb/header.php
  roles/usb_lib/files/upload2usb/index.php
  roles/usb_lib/files/upload2usb/upload-file.php
  roles/usb_lib/files/upload2usb/upload2usb.php
Labels: enhancement

#4038 Fixed octal-values for ansible-lint
  .ansible-lint.yml
  roles/2-common/tasks/iiab-startup.yml
  roles/azuracast/tasks/install.yml
  roles/bluetooth/tasks/install.yml
  roles/calibre/tasks/py-installer.yml
  roles/cups/tasks/install.yml
  roles/gitea/tasks/install.yml
  roles/iiab-admin/tasks/sudo-prereqs.yml
  roles/jupyterhub/tasks/install.yml
  roles/lokole/tasks/install.yml
  roles/luanti/NotUsed/rpi_minetest_install.yml
  roles/luanti/tasks/luanti_install.yml
  roles/luanti/tasks/luanti_install_mods.yml
  roles/moodle/tasks/install.yml
  roles/network/tasks/NM-debian.yml
  roles/network/tasks/avahi.yml
  roles/network/tasks/enable_services.yml
  roles/network/tasks/hostapd.yml
  roles/network/tasks/install.yml
  roles/network/tasks/main.yml
  roles/network/tasks/netwarn.yml
  roles/network/tasks/rpi_debian.yml
  roles/network/tasks/squid.yml
  roles/network/tasks/sysd-netd-debian.yml
  roles/nodered/tasks/settings.yml
  roles/osm-vector-maps/tasks/install.yml
  roles/postgresql/tasks/install.yml
  roles/pylibs/tasks/main.yml
  roles/remoteit/tasks/install.yml
  roles/usb_lib/tasks/install.yml
Labels: enhancement

#4040 Fixed key-order[task] violations for ansible-lint
  .ansible-lint.yml
  roles/mongodb/tasks/install.yml
  roles/network/tasks/main.yml
  roles/pbx/tasks/enable-or-disable.yml
  roles/transmission/tasks/install.yml
Labels: enhancement, question

#4041 Recommend ansible-core 2.18.7
  scripts/ansible
Labels: enhancement

#4044 Remove 1 instance of is_ubuntu_2410
  roles/8-mgmt-tools/tasks/main.yml
Labels: bug, enhancement

#4045 roles/network: Ansible hack to fix SUDO_UID for raspi-config wifi country code (required for Raspberry Pi OS with desktop)
  roles/network/tasks/main.yml
Labels: bug, enhancement

#4048 Stronger roles/network hack: SUDO_UID=1000 for raspi-config do_wifi_country (needed for RasPiOS with desktop)
  roles/network/tasks/main.yml
Labels: bug, enhancement
